#!/usr/bin/env bash
# OpenMW 0.51 / TrimUI Smart Pro
# V30 R10-R1: four-ray, three-range interior residency/cull controller.
#
# Starts from the proven R9-R2 renderer-alignment build. R9's light callback
# bypass and Scene-owned topology remain intact; R10 changes only the distance
# envelopes selected by the ray-confirmed space class.
#
# R10 keeps exactly four Lua physics rays per 0.20-second sample. The true
# center ray stays fixed. Left, right, and upper rays sweep an eight-phase
# circular offset around their anchors. A decaying authority score combines
# the three forward depths, the upper opening witness, and R4's current
# navmesh-sector kind/AABB. Long rays carry more weight and expand quickly;
# short rays must agree for a sustained period before VERY_TIGHT is allowed.
#
# Range modes:
#   OPEN:       lights 2600/320Z, ordinary 1100/1450, render bypass 1450
#   TIGHT:      lights 1700/256Z, ordinary 800/1050,  render bypass 1000
#   VERY_TIGHT: lights  850/192Z, ordinary 450/650,   render bypass  500
#
# VERY_TIGHT requires all three forward rays <=700 for 40 samples (8 seconds,
# 160 total ray reports). One contradictory long ray immediately leaves
# VERY_TIGHT; two continuing long samples select OPEN. Old ray evidence fades
# exponentially, and every cell/topology change wipes the evidence slate.
#
# Actions: install (default), collect, rollback

set -u -o pipefail

ACTION="${1:-install}"
CTR="${OPENMW_CONTAINER:-openmw_builder}"
DEV="${TSP_DEVICE:-root@192.168.1.12}"

SRC="/root/openmw-0.51-tsp-src"
BUILD="/root/openmw-0.51-tsp-build"
PACKAGE="/root/openmw-0.51-tsp-package"
SCENE="$SRC/apps/openmw/mwworld/scene.cpp"
ANIM="$SRC/apps/openmw/mwrender/animation.cpp"
VIS="$SRC/apps/openmw/mwrender/interiorvisibility.cpp"
VISH="$SRC/apps/openmw/mwrender/interiorvisibility.hpp"
CAMBIND="$SRC/apps/openmw/mwlua/camerabindings.cpp"
BUILT="$BUILD/openmw"
PACKAGED="$PACKAGE/bin/openmw-0.51"

ROOT="/mnt/SDCARD/data/ports/openmw51"
BIN="$ROOT/bin/openmw-0.51"
LUA="$ROOT/mods/TSPInteriorVisGrid/scripts/TSPInteriorVisGrid/visgrid.lua"
PROFILE="$ROOT/mods/TSPInteriorVisGrid/scripts/TSPInteriorVisGrid/v30_profiles/visgrid-v30-floor-actor-roomwake.lua"
GAMELOG="$ROOT/openmw_051_log.txt"
PERF="$ROOT/openmw51_perf_latest.txt"
TMPBIN="/tmp/openmw-0.51.v30-r10-four-ray"
TMPLUA="/tmp/visgrid-v30-r10-four-ray.lua"
ARM="$ROOT/roomwake-r10-capture-start.line"

DL="$HOME/Downloads"
STAMP="$(date +%Y%m%d-%H%M%S)"
R9_STATE="$DL/openmw51-roomwake-r9.state"
RUNLOG="$DL/openmw51-roomwake-r10-$STAMP.log"
BUILDLOG="$DL/openmw51-roomwake-r10-build-$STAMP.log"
STATE="$DL/openmw51-roomwake-r10.state"
HOSTBIN="$DL/openmw-0.51-v30-r10-four-ray-three-range"
TMP="$(mktemp -d "$DL/.roomwake-r10.XXXXXX")"

SOURCE_BACKUP=""
DEVICE_BACKUP=""
SOURCE_MUTATED=0
DEVICE_DEPLOYED=0
LUA_DEPLOYED=0
EXPECTED_R9_SHA=""
EXPECTED_R4_LUA_SHA=""

fail() {
    local rc="${1:-1}"
    shift || true
    echo "ERROR: $*" >&2
    exit "$rc"
}

need() {
    if ! command -v "$1" >/dev/null 2>&1; then
        fail 10 "required command missing: $1"
    fi
    echo "PASS command: $1"
}

ensure_docker() {
    need docker
    if ! docker inspect "$CTR" >/dev/null 2>&1; then
        fail 11 "Docker container not found: $CTR"
    fi
    local running
    running="$(docker inspect -f '{{.State.Running}}' "$CTR" 2>/dev/null || true)"
    if [ "$running" != "true" ]; then
        if ! docker start "$CTR" >/dev/null; then
            fail 12 "failed to start Docker: $CTR"
        fi
    fi
    echo "PASS Docker: $CTR"
}

ensure_ssh() {
    need ssh
    need scp
    if ! ssh -o BatchMode=yes -o ConnectTimeout=8 "$DEV" true >/dev/null 2>&1; then
        fail 13 "SSH failed: $DEV"
    fi
    echo "PASS SSH: $DEV"
}

load_r9_baseline() {
    if [ ! -s "$R9_STATE" ]; then
        fail 14 "R9 state missing: $R9_STATE"
    fi
    # Generated by the exact R9-R2 controller.
    # shellcheck disable=SC1090
    . "$R9_STATE"
    EXPECTED_R9_SHA="${R9_NEW_SHA:-}"
    EXPECTED_R4_LUA_SHA="${R9_LUA_SHA:-}"
    if ! printf '%s\n' "$EXPECTED_R9_SHA" | grep -Eq '^[0-9a-f]{64}$'; then
        fail 15 "R9 state has invalid R9_NEW_SHA: ${EXPECTED_R9_SHA:-EMPTY}"
    fi
    if ! printf '%s\n' "$EXPECTED_R4_LUA_SHA" | grep -Eq '^[0-9a-f]{64}$'; then
        fail 16 "R9 state has invalid R9_LUA_SHA: ${EXPECTED_R4_LUA_SHA:-EMPTY}"
    fi
}

cleanup() {
    rm -rf "$TMP"
}

restore_source() {
    if [ -z "$SOURCE_BACKUP" ]; then
        echo "FAIL R10 source rollback path empty" >&2
        return 1
    fi
    if ! docker exec -i "$CTR" bash -s -- \
        "$SOURCE_BACKUP" "$SCENE" "$VIS" "$VISH" "$CAMBIND" "$BUILD" <<'REMOTE_RESTORE_SOURCE'
set -u
BACKUP="$1"
SCENE="$2"
VIS="$3"
VISH="$4"
CAMBIND="$5"
BUILD="$6"

for name in scene.cpp interiorvisibility.cpp interiorvisibility.hpp camerabindings.cpp; do
    if [ ! -s "$BACKUP/$name" ]; then
        echo "FAIL rollback source missing: $BACKUP/$name" >&2
        exit 1
    fi
done

if ! cp -f "$BACKUP/scene.cpp" "$SCENE"; then exit 2; fi
if ! cp -f "$BACKUP/interiorvisibility.cpp" "$VIS"; then exit 3; fi
if ! cp -f "$BACKUP/interiorvisibility.hpp" "$VISH"; then exit 4; fi
if ! cp -f "$BACKUP/camerabindings.cpp" "$CAMBIND"; then exit 5; fi

touch "$SCENE" "$VIS" "$VISH" "$CAMBIND"
rm -f \
    "$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwworld/scene.cpp.o" \
    "$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwworld/scene.cpp.o.d" \
    "$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwrender/interiorvisibility.cpp.o" \
    "$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwrender/interiorvisibility.cpp.o.d" \
    "$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwlua/camerabindings.cpp.o" \
    "$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwlua/camerabindings.cpp.o.d"

echo "PASS source rollback restored exact pre-R10 R9 source and invalidated all 3 translation units"
REMOTE_RESTORE_SOURCE
    then
        return 1
    fi
    return 0
}

restore_device() {
    if [ -z "$DEVICE_BACKUP" ]; then
        echo "FAIL R10 device rollback path empty" >&2
        return 1
    fi
    if ! ssh "$DEV" 'bash -s' -- "$DEVICE_BACKUP/openmw-0.51.before-r10" "$BIN" "$EXPECTED_R9_SHA" <<'REMOTE_RESTORE_DEVICE'
set -u
BACKUP="$1"
BIN="$2"
EXPECTED="$3"

if [ ! -s "$BACKUP" ]; then
    echo "FAIL rollback binary missing: $BACKUP" >&2
    exit 1
fi
BACK_SHA="$(sha256sum "$BACKUP" | awk '{print $1}')"
if [ "$BACK_SHA" != "$EXPECTED" ]; then
    echo "FAIL rollback backup SHA expected=$EXPECTED actual=$BACK_SHA" >&2
    exit 2
fi
if ! install -m 755 "$BACKUP" "$BIN"; then
    echo "FAIL restoring R9 binary" >&2
    exit 3
fi
sync
FINAL="$(sha256sum "$BIN" | awk '{print $1}')"
if [ "$FINAL" != "$EXPECTED" ]; then
    echo "FAIL restored R9 SHA expected=$EXPECTED actual=$FINAL" >&2
    exit 4
fi
echo "PASS exact R9 device restored: $FINAL"
REMOTE_RESTORE_DEVICE
    then
        return 1
    fi
    return 0
}

restore_lua() {
    if [ -z "$DEVICE_BACKUP" ]; then
        echo "FAIL R10 Lua rollback path empty" >&2
        return 1
    fi
    if ! ssh "$DEV" 'bash -s' -- "$DEVICE_BACKUP" "$LUA" "$PROFILE" "$EXPECTED_R4_LUA_SHA" <<'REMOTE_RESTORE_LUA'
set -u
BACKUP="$1"
LIVE="$2"
PROFILE="$3"
EXPECTED="$4"
for f in "$BACKUP/visgrid.lua.before-r10" "$BACKUP/profile.lua.before-r10"; do
    if [ ! -s "$f" ]; then echo "FAIL Lua rollback backup missing: $f" >&2; exit 1; fi
done
for f in "$BACKUP/visgrid.lua.before-r10" "$BACKUP/profile.lua.before-r10"; do
    GOT="$(sha256sum "$f" | awk '{print $1}')"
    if [ "$GOT" != "$EXPECTED" ]; then
        echo "FAIL Lua rollback SHA expected=$EXPECTED actual=$GOT file=$f" >&2
        exit 2
    fi
done
install -m 644 "$BACKUP/visgrid.lua.before-r10" "$LIVE" || exit 3
install -m 644 "$BACKUP/profile.lua.before-r10" "$PROFILE" || exit 4
sync
for f in "$LIVE" "$PROFILE"; do
    GOT="$(sha256sum "$f" | awk '{print $1}')"
    if [ "$GOT" != "$EXPECTED" ]; then
        echo "FAIL restored R4 Lua SHA expected=$EXPECTED actual=$GOT file=$f" >&2
        exit 5
    fi
done
echo "PASS exact pre-R10 R4 Lua restored"
REMOTE_RESTORE_LUA
    then
        return 1
    fi
    return 0
}

on_exit() {
    local rc=$?
    trap - EXIT
    if [ "$rc" -ne 0 ]; then
        echo
        echo "===== R10 FAILURE RECOVERY ====="
        if [ "$LUA_DEPLOYED" -eq 1 ]; then
            echo "INFO: restoring exact pre-R10 R4 Lua..."
            restore_lua || echo "WARNING: automatic R10 Lua rollback failed" >&2
        fi
        if [ "$DEVICE_DEPLOYED" -eq 1 ]; then
            echo "INFO: restoring exact R9 device binary..."
            restore_device || echo "WARNING: automatic R10 device rollback failed" >&2
        fi
        if [ "$SOURCE_MUTATED" -eq 1 ]; then
            echo "INFO: restoring exact R9 Docker source..."
            restore_source || echo "WARNING: automatic R10 source rollback failed" >&2
        fi
    fi
    cleanup
    exit "$rc"
}
trap on_exit EXIT

collect_action() {
    ensure_ssh
    local out="$DL/openmw51-roomwake-r10-validation-$STAMP.txt"

    if ! ssh "$DEV" 'bash -s' -- "$GAMELOG" "$PERF" "$BIN" "$LUA" "$ARM" > "$out" <<'REMOTE_COLLECT'
set -u
LOG="$1"
PERF="$2"
BIN="$3"
LUA="$4"
ARM="$5"

echo "===== OPENMW 0.51 V30 R10-R1 FOUR-RAY THREE-RANGE VALIDATION ====="
date
if [ -s "$BIN" ]; then echo "Binary SHA: $(sha256sum "$BIN" | awk '{print $1}')"; fi
if [ -s "$LUA" ]; then echo "Lua SHA:    $(sha256sum "$LUA" | awk '{print $1}')"; fi

if [ ! -f "$LOG" ]; then
    echo "ERROR log missing: $LOG"
    exit 1
fi

TOTAL="$(wc -l < "$LOG" | tr -d '[:space:]')"
START=""
if [ -s "$ARM" ]; then START="$(tr -dc '0-9' < "$ARM")"; fi
case "$START" in
    ''|*[!0-9]*)
        if [ "$TOTAL" -gt 2200 ]; then START=$((TOTAL-2200)); else START=0; fi
        ;;
esac
FIRST=$((START+1))

echo "Log lines: total=$TOTAL capture=$FIRST..$TOTAL"
echo
sed -n "${FIRST},${TOTAL}p" "$LOG" 2>/dev/null \
    | grep -E 'Loading cell|Changing to interior|\[TSP_ROOMRAY_R10\]|\[TSP_ROOMOBJ_V30\]|\[TSP_VISGRID_V30_R4\]|\[TSP_ACTOR_V30\]|\[TSP_VISGRID_V11\]|failed to render|Lua.*error' \
    || true

echo
echo "===== PERF TAIL ====="
if [ -f "$PERF" ]; then tail -120 "$PERF" 2>/dev/null || true; fi
REMOTE_COLLECT
    then
        fail 20 "R10 collect failed"
    fi
    echo "Saved: $out"
}

rollback_action() {
    ensure_docker
    ensure_ssh
    if [ ! -s "$STATE" ]; then
        fail 21 "R10 rollback state missing: $STATE"
    fi
    # shellcheck disable=SC1090
    . "$STATE"
    if [ -z "${R10_SOURCE_BACKUP:-}" ] || [ -z "${R10_DEVICE_BACKUP:-}" ]; then
        fail 22 "R10 rollback state incomplete: $STATE"
    fi
    EXPECTED_R9_SHA="${R10_OLD_SHA:-}"
    EXPECTED_R4_LUA_SHA="${R10_OLD_LUA_SHA:-}"
    if ! printf '%s\n' "$EXPECTED_R9_SHA" | grep -Eq '^[0-9a-f]{64}$'; then fail 23 "invalid R10 old binary SHA"; fi
    if ! printf '%s\n' "$EXPECTED_R4_LUA_SHA" | grep -Eq '^[0-9a-f]{64}$'; then fail 24 "invalid R10 old Lua SHA"; fi
    SOURCE_BACKUP="$R10_SOURCE_BACKUP"
    DEVICE_BACKUP="$R10_DEVICE_BACKUP"
    restore_source || fail 25 "manual R10 source rollback failed"
    restore_device || fail 26 "manual R10 device rollback failed"
    restore_lua || fail 27 "manual R10 Lua rollback failed"
    echo "PASS R10 rollback complete; exact R9 binary + R4 Lua restored."
}

case "$ACTION" in
    collect)
        collect_action
        exit 0
        ;;
    rollback)
        rollback_action
        exit 0
        ;;
    install) ;;
    *) fail 2 "usage: $0 [install|collect|rollback]" ;;
esac

exec > >(tee "$RUNLOG") 2>&1

cat <<'BANNER'
============================================================
OPENMW 0.51 — ROOMWAKE V30 R10-R1
FOUR-RAY / THREE-RANGE ADAPTIVE INTERIOR SAFETY
============================================================
Exactly four rays every 0.20 seconds: left, true center, right, up.
Left/right/up sweep an eight-phase circular offset; center stays fixed.

OPEN:       lights 2600/320Z, ordinary 1100/1450, render 1450
TIGHT:      lights 1700/256Z, ordinary  800/1050, render 1000
VERY_TIGHT: lights  850/192Z, ordinary  450/650,  render  500

VERY_TIGHT requires all 3 forward rays <=700 for 40 samples (8 seconds).
Long rays are weighted 10x faster than shrinking evidence.
First contradictory long sample exits VERY_TIGHT; continuing long evidence opens.
R4 navmesh kind/AABB supplies a live prior; cell changes wipe all history.
============================================================
BANNER

need python3
need sha256sum
need file
ensure_docker
ensure_ssh
load_r9_baseline

if ssh "$DEV" "pgrep -af 'openmw-0\\.51|/openmw([[:space:]]|$)' 2>/dev/null" \
    | grep -v pgrep >/dev/null 2>&1; then
    fail 30 "OpenMW appears to be running; exit the game first"
fi

echo
echo "===== 1/9 VERIFY EXACT INSTALLED R9 / R4 LUA / SOURCE SHAPE ====="

LIVE_SHA="$(ssh "$DEV" "sha256sum '$BIN' | awk '{print \$1}'" 2>/dev/null || true)"
if [ "$LIVE_SHA" != "$EXPECTED_R9_SHA" ]; then
    echo "EXPECTED R9 FROM STATE: $EXPECTED_R9_SHA" >&2
    echo "ACTUAL DEVICE:  $LIVE_SHA" >&2
    fail 31 "device is not on the exact R9 baseline recorded by its installer"
fi
echo "PASS exact state-derived R9 device SHA: $LIVE_SHA"

if ! ssh "$DEV" "grep -Fq 'TSP_VISGRID_LUA_V30_R4_SAME_FLOOR_PROXIMITY' '$LUA' && cmp -s '$LUA' '$PROFILE'"; then
    fail 32 "live/profile Lua is not the exact matching R4 baseline"
fi
LUA_SHA_BEFORE="$(ssh "$DEV" "sha256sum '$LUA' | awk '{print \$1}'" 2>/dev/null || true)"
if [ "$LUA_SHA_BEFORE" != "$EXPECTED_R4_LUA_SHA" ]; then
    echo "EXPECTED R4 LUA FROM STATE: $EXPECTED_R4_LUA_SHA" >&2
    echo "ACTUAL LIVE LUA:            $LUA_SHA_BEFORE" >&2
    fail 33 "live R4 Lua differs from the Lua recorded by R9"
fi
echo "PASS live R4 Lua SHA: $LUA_SHA_BEFORE"

if ! docker exec -i "$CTR" python3 - "$SCENE" "$ANIM" "$VIS" "$VISH" "$CAMBIND" <<'PY_PREFLIGHT'
import sys
scene_path, anim_path, vis_path, vish_path, cambind_path = sys.argv[1:6]

def read(p):
    with open(p, 'r', encoding='utf-8', newline='') as f:
        return f.read()

sc, an, vi, vh, cb = map(read, (scene_path, anim_path, vis_path, vish_path, cambind_path))

scene_required = [
    'TSP_ROOM_RENDER_SAFETY_051_V30_R9',
    'tspRoomLightNearXY = 2800.f',
    'tspRoomLightNearZ = 384.f',
    'tspNearWakeXY = 1100.f',
    'tspNearWakeZ = 320.f',
    'tspNearHoldXY = 1450.f',
    'tspNearHoldZ = 384.f',
    'lightNearXY=2800 lightNearZ=384',
]
for token in scene_required:
    if token not in sc:
        raise SystemExit('FAIL R9 scene token missing: ' + token)

anim_required = [
    'TSP_ROOM_RENDER_SAFETY_051_V30_R9',
    'const bool tspIsLight = mPtr.getType() == ESM::Light::sRecordId;',
    'const bool tspPvsEligible = false;',
    '!tspDiagActor && !tspDiagDoor && !tspIsStatic && !tspIsLight',
]
for token in anim_required:
    if token not in an:
        raise SystemExit('FAIL R9 animation token missing: ' + token)
if 'mPtr.get<ESM::Static>()' in an:
    raise SystemExit('FAIL unsafe Static LiveCellRef cast exists in animation.cpp')

vis_required = [
    'TSP_ROOM_RENDER_SAFETY_051_V30_R9',
    'TSP_ROOM_OBJECT_FLOOR_AUTHORITY_051_V30',
    'void InteriorVisibilityCullCallback::operator()(osg::Node* node, osgUtil::CullVisitor* cv)',
    'tspGameplayCullBypass = 1600.0',
    'tspGameplayNearSurface = std::max(0.0, center.length() - radius)',
    'const double nearestSurface=',
]
for token in vis_required:
    if token not in vi:
        raise SystemExit('FAIL R9 visibility token missing: ' + token)

for text, token, label in (
    (vh, 'bool isInteriorTopologyPvsEnabled();', 'topology header API'),
    (cb, 'setInteriorTopologyPvs', 'camera topology binding'),
    (cb, 'clearInteriorTopologyPvs', 'camera topology clear binding'),
):
    if token not in text:
        raise SystemExit('FAIL missing %s: %s' % (label, token))

for token in ('TSP_ROOM_ADAPTIVE_RANGE_051_V30_R10', 'setInteriorAdaptiveRangeMode',
              'getInteriorAdaptiveRangeMode'):
    if any(token in text for text in (sc, an, vi, vh, cb)):
        raise SystemExit('FAIL R10 token already present before patch: ' + token)

for text, token, label in (
    (sc, 'tspRoomLightNearXY = 2800.f', 'R9 light XY'),
    (sc, 'tspNearWakeXY = 1100.f', 'R9 ordinary wake XY'),
    (sc, 'tspNearHoldXY = 1450.f', 'R9 ordinary hold XY'),
    (sc, '[TSP_ROOMOBJ_V30] lightNearXY=2800 lightNearZ=384', 'R9 aggregate range log prefix'),
    (vi, 'tspGameplayCullBypass = 1600.0', 'R9 gameplay bypass'),
):
    count = text.count(token)
    if count != 1:
        raise SystemExit('FAIL %s count=%d expected 1' % (label, count))

print('PASS exact R9 C++ source shape and bridge anchors')
PY_PREFLIGHT
then
    fail 34 "source is not the exact expected R9 baseline; no source modified"
fi

echo
echo "===== 2/9 BACK UP FOUR SOURCE FILES + R9 DEVICE + R4 LUA ====="

SOURCE_BACKUP="$SRC/.tsp-051-source-backups/roomwake-v30-r10-four-ray-$STAMP"
if ! docker exec -i "$CTR" bash -s -- "$SOURCE_BACKUP" "$SCENE" "$VIS" "$VISH" "$CAMBIND" <<'REMOTE_BACKUP_SOURCE'
set -u
BACKUP="$1"
SCENE="$2"
VIS="$3"
VISH="$4"
CAMBIND="$5"

if ! mkdir -p "$BACKUP"; then
    echo "FAIL creating source backup: $BACKUP" >&2
    exit 1
fi
if ! cp -f "$SCENE" "$BACKUP/scene.cpp"; then exit 2; fi
if ! cp -f "$VIS" "$BACKUP/interiorvisibility.cpp"; then exit 3; fi
if ! cp -f "$VISH" "$BACKUP/interiorvisibility.hpp"; then exit 4; fi
if ! cp -f "$CAMBIND" "$BACKUP/camerabindings.cpp"; then exit 5; fi
sha256sum "$BACKUP/scene.cpp" "$BACKUP/interiorvisibility.cpp" \
    "$BACKUP/interiorvisibility.hpp" "$BACKUP/camerabindings.cpp"
echo "PASS R10 source backup: $BACKUP"
REMOTE_BACKUP_SOURCE
then
    fail 40 "R10 source backup failed"
fi

DEVICE_BACKUP="$ROOT/backups/roomwake-v30-r10-four-ray-$STAMP"
if ! ssh "$DEV" 'bash -s' -- "$BIN" "$LUA" "$PROFILE" "$DEVICE_BACKUP" "$EXPECTED_R9_SHA" "$EXPECTED_R4_LUA_SHA" <<'REMOTE_BACKUP_DEVICE'
set -u
BIN="$1"
LIVE_LUA="$2"
PROFILE="$3"
BACKUP="$4"
EXPECTED_BIN="$5"
EXPECTED_LUA="$6"

if ! mkdir -p "$BACKUP"; then exit 1; fi
LIVE="$(sha256sum "$BIN" | awk '{print $1}')"
if [ "$LIVE" != "$EXPECTED_BIN" ]; then
    echo "FAIL device changed before backup expected=$EXPECTED_BIN actual=$LIVE" >&2
    exit 2
fi
if ! cp -f "$BIN" "$BACKUP/openmw-0.51.before-r10"; then exit 3; fi
if ! cp -f "$LIVE_LUA" "$BACKUP/visgrid.lua.before-r10"; then exit 4; fi
if ! cp -f "$PROFILE" "$BACKUP/profile.lua.before-r10"; then exit 5; fi
if [ "$(sha256sum "$BACKUP/openmw-0.51.before-r10" | awk '{print $1}')" != "$EXPECTED_BIN" ]; then exit 6; fi
if [ "$(sha256sum "$BACKUP/visgrid.lua.before-r10" | awk '{print $1}')" != "$EXPECTED_LUA" ]; then exit 7; fi
if [ "$(sha256sum "$BACKUP/profile.lua.before-r10" | awk '{print $1}')" != "$EXPECTED_LUA" ]; then exit 8; fi
echo "PASS exact R9 binary + R4 Lua device backup: $BACKUP"
REMOTE_BACKUP_DEVICE
then
    fail 41 "R10 device backup failed"
fi

if ! scp -q "$DEV:$PROFILE" "$TMP/visgrid-r4.lua"; then
    fail 42 "could not pull exact R4 profile for R10 patching"
fi
if [ "$(sha256sum "$TMP/visgrid-r4.lua" | awk '{print $1}')" != "$EXPECTED_R4_LUA_SHA" ]; then
    fail 43 "pulled R4 profile SHA differs from recorded/live baseline"
fi

echo
echo "===== 3/9 CREATE + SELFTEST STRUCTURAL R10 C++ PATCHER ====="

cat > "$TMP/patch_r10.py" <<'PY_PATCH'
#!/usr/bin/env python3
import sys

MARK = 'TSP_ROOM_ADAPTIVE_RANGE_051_V30_R10'


def read(path):
    with open(path, 'r', encoding='utf-8', newline='') as f:
        return f.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def replace_one(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise RuntimeError('%s count=%d expected 1 token=%r' % (label, count, old))
    return text.replace(old, new, 1)


def line_start(text, pos):
    return text.rfind('\n', 0, pos) + 1


def line_end(text, pos):
    end = text.find('\n', pos)
    return len(text) if end < 0 else end + 1


def indent_at(text, pos):
    start = line_start(text, pos)
    end = line_end(text, pos)
    line = text[start:end]
    return line[:len(line) - len(line.lstrip(' \t'))]


def patch_scene(sc):
    for token in (
        'TSP_ROOM_RENDER_SAFETY_051_V30_R9',
        'tspRoomLightNearXY = 2800.f',
        'tspRoomLightNearZ = 384.f',
        'tspNearWakeXY = 1100.f',
        'tspNearWakeZ = 320.f',
        'tspNearHoldXY = 1450.f',
        'tspNearHoldZ = 384.f',
    ):
        if token not in sc:
            raise RuntimeError('R9 scene precondition missing: ' + token)
    if MARK in sc:
        raise RuntimeError('R10 scene marker already present')

    old = 'constexpr float tspRoomLightNearXY = 2800.f;'
    pos = sc.index(old)
    indent = indent_at(sc, pos)
    new = (
        indent + '// ' + MARK + ' THREE_RANGE_SCENE\n'
        + indent + 'const int tspAdaptiveRangeMode = MWRender::getInteriorAdaptiveRangeMode();\n'
        + indent + 'const float tspRoomLightNearXY = tspAdaptiveRangeMode >= 2 ? 850.f\n'
        + indent + '    : (tspAdaptiveRangeMode == 1 ? 1700.f : 2600.f);'
    )
    sc = replace_one(sc, old, new, 'R9 light XY declaration')
    sc = replace_one(sc,
        'constexpr float tspRoomLightNearZ = 384.f;',
        'const float tspRoomLightNearZ = tspAdaptiveRangeMode >= 2 ? 192.f\n'
        + indent + '    : (tspAdaptiveRangeMode == 1 ? 256.f : 320.f);',
        'R9 light Z declaration')

    dynamic = (
        ('constexpr float tspNearWakeXY = 1100.f;',
         'const float tspNearWakeXY = tspAdaptiveRangeMode >= 2 ? 450.f\n'
         + indent + '    : (tspAdaptiveRangeMode == 1 ? 800.f : 1100.f);',
         'ordinary wake XY'),
        ('constexpr float tspNearWakeZ = 320.f;',
         'const float tspNearWakeZ = tspAdaptiveRangeMode >= 2 ? 160.f\n'
         + indent + '    : (tspAdaptiveRangeMode == 1 ? 256.f : 320.f);',
         'ordinary wake Z'),
        ('constexpr float tspNearHoldXY = 1450.f;',
         'const float tspNearHoldXY = tspAdaptiveRangeMode >= 2 ? 650.f\n'
         + indent + '    : (tspAdaptiveRangeMode == 1 ? 1050.f : 1450.f);',
         'ordinary hold XY'),
        ('constexpr float tspNearHoldZ = 384.f;',
         'const float tspNearHoldZ = tspAdaptiveRangeMode >= 2 ? 192.f\n'
         + indent + '    : (tspAdaptiveRangeMode == 1 ? 320.f : 384.f);',
         'ordinary hold Z'),
    )
    for old_token, new_token, label in dynamic:
        sc = replace_one(sc, old_token, new_token, label)

    # Match the exact verified prefix inside the string literal, not an
    # invented complete literal. The live R9 log continues with more fields
    # after lightNearZ=384, so requiring a quote at that point is wrong.
    old_log = '[TSP_ROOMOBJ_V30] lightNearXY=2800 lightNearZ=384'
    if sc.count(old_log) != 1:
        raise RuntimeError('R9 aggregate range log prefix count=%d expected 1'
                           % sc.count(old_log))
    # This diagnostic is outside the per-object block where the dynamic range
    # locals are declared. Never reference those inner-scope locals here.
    # The bridge getter is namespace-visible at the log site and the R10 Lua
    # authority line already reports the selected distance envelope.
    new_log = ('[TSP_ROOMOBJ_V30] adaptiveRangeMode="'
               ' << MWRender::getInteriorAdaptiveRangeMode() << "')
    sc = sc.replace(old_log, new_log, 1)

    for token in (
        MARK,
        'tspAdaptiveRangeMode >= 2 ? 850.f',
        'tspAdaptiveRangeMode == 1 ? 1700.f : 2600.f',
        'tspAdaptiveRangeMode >= 2 ? 450.f',
        'tspAdaptiveRangeMode == 1 ? 800.f : 1100.f',
        'tspAdaptiveRangeMode >= 2 ? 650.f',
        'tspAdaptiveRangeMode == 1 ? 1050.f : 1450.f',
        '[TSP_ROOMOBJ_V30] adaptiveRangeMode=',
    ):
        if token not in sc:
            raise RuntimeError('R10 scene postcondition missing: ' + token)
    return sc


def patch_header(vh):
    if MARK in vh or 'setInteriorAdaptiveRangeMode' in vh:
        raise RuntimeError('R10 header patch already present')
    anchor = 'bool isInteriorTopologyPvsEnabled();'
    if vh.count(anchor) != 1:
        candidates = [line for line in vh.splitlines() if 'isInteriorTopologyPvsEnabled' in line]
        raise RuntimeError('header topology API anchor count=%d candidates=%r'
                           % (vh.count(anchor), candidates[-10:]))
    pos = vh.index(anchor)
    end = line_end(vh, pos)
    indent = indent_at(vh, pos)
    insert = (
        '\n' + indent + '// ' + MARK + ' LUA_CPP_BRIDGE\n'
        + indent + '// 0=open, 1=tight, 2=very-tight. Setter clamps invalid input.\n'
        + indent + 'void setInteriorAdaptiveRangeMode(int mode);\n'
        + indent + 'int getInteriorAdaptiveRangeMode();\n'
    )
    vh = vh[:end] + insert + vh[end:]
    return vh


def patch_visibility(vi):
    for token in (
        'TSP_ROOM_RENDER_SAFETY_051_V30_R9',
        'tspGameplayCullBypass = 1600.0',
        'tspGameplayNearSurface = std::max(0.0, center.length() - radius)',
    ):
        if token not in vi:
            raise RuntimeError('R9 visibility precondition missing: ' + token)
    if MARK in vi or 'tspAdaptiveRangeModeStorage' in vi:
        raise RuntimeError('R10 visibility patch already present')

    ns = 'namespace MWRender\n{'
    if vi.count(ns) < 1:
        raise RuntimeError('MWRender namespace opening not found')
    bridge = '''namespace MWRender
{
    // TSP_ROOM_ADAPTIVE_RANGE_051_V30_R10 LUA_CPP_BRIDGE
    namespace
    {
        std::atomic<int>& tspAdaptiveRangeModeStorage()
        {
            static std::atomic<int> mode{ 0 };
            return mode;
        }
    }

    void setInteriorAdaptiveRangeMode(int mode)
    {
        if (mode < 0)
            mode = 0;
        else if (mode > 2)
            mode = 2;
        tspAdaptiveRangeModeStorage().store(mode, std::memory_order_relaxed);
    }

    int getInteriorAdaptiveRangeMode()
    {
        return tspAdaptiveRangeModeStorage().load(std::memory_order_relaxed);
    }
'''
    vi = vi.replace(ns, bridge, 1)

    old = 'constexpr double tspGameplayCullBypass = 1600.0;'
    pos = vi.index(old)
    indent = indent_at(vi, pos)
    new = (
        '// ' + MARK + ' THREE_RANGE_RENDER\n'
        + indent + 'const int tspAdaptiveRangeMode = getInteriorAdaptiveRangeMode();\n'
        + indent + 'const double tspGameplayCullBypass = tspAdaptiveRangeMode >= 2 ? 500.0\n'
        + indent + '    : (tspAdaptiveRangeMode == 1 ? 1000.0 : 1450.0);'
    )
    vi = replace_one(vi, old, new, 'R9 gameplay bypass')

    for token in (
        MARK,
        'setInteriorAdaptiveRangeMode(int mode)',
        'getInteriorAdaptiveRangeMode()',
        'tspAdaptiveRangeMode >= 2 ? 500.0',
        'tspAdaptiveRangeMode == 1 ? 1000.0 : 1450.0',
        'const double nearestSurface=',
    ):
        if token not in vi:
            raise RuntimeError('R10 visibility postcondition missing: ' + token)
    return vi


def patch_camera_binding(cb):
    for token in ('setInteriorTopologyPvs', 'clearInteriorTopologyPvs'):
        if token not in cb:
            raise RuntimeError('camera binding precondition missing: ' + token)
    if MARK in cb or 'setInteriorAdaptiveRangeMode' in cb:
        raise RuntimeError('R10 camera binding already present')

    anchor = 'api["clearInteriorTopologyPvs"]'
    if cb.count(anchor) != 1:
        candidates = [line for line in cb.splitlines() if 'clearInteriorTopologyPvs' in line]
        raise RuntimeError('camera clear-PVS anchor count=%d candidates=%r'
                           % (cb.count(anchor), candidates[-10:]))
    pos = cb.index(anchor)
    start = line_start(cb, pos)
    indent = indent_at(cb, pos)
    insert = (
        indent + '// ' + MARK + ' LUA_CPP_BRIDGE\n'
        + indent + 'api["setInteriorAdaptiveRangeMode"] = [](int mode) {\n'
        + indent + '    MWRender::setInteriorAdaptiveRangeMode(mode);\n'
        + indent + '};\n'
        + indent + 'api["getInteriorAdaptiveRangeMode"] = []() {\n'
        + indent + '    return MWRender::getInteriorAdaptiveRangeMode();\n'
        + indent + '};\n'
    )
    cb = cb[:start] + insert + cb[start:]
    return cb


def patch_all(sc, vi, vh, cb):
    return patch_scene(sc), patch_visibility(vi), patch_header(vh), patch_camera_binding(cb)


def sample_scene():
    return '''namespace MWRender { int getInteriorAdaptiveRangeMode(); }
struct DummyLog
{
    template <class T> DummyLog& operator<<(const T&) { return *this; }
};
DummyLog Log();
// TSP_ROOM_RENDER_SAFETY_051_V30_R9
void f()
{
    {
        constexpr float tspRoomLightNearXY = 2800.f;
        constexpr float tspRoomLightNearZ = 384.f;
        constexpr float tspNearWakeXY = 1100.f;
        constexpr float tspNearWakeZ = 320.f;
        constexpr float tspNearHoldXY = 1450.f;
        constexpr float tspNearHoldZ = 384.f;
    }
    // The real R9 literal continues after lightNearZ; this exact regression
    // shape prevents preflight/mutator matcher drift from returning.
    Log() << "[TSP_ROOMOBJ_V30] lightNearXY=2800 lightNearZ=384 ordinaryWakeXY=1100 ordinaryHoldXY=1450";
    // The live source legitimately has another diagnostic with the same broad
    // marker. Keep it in the fixture so validators cannot assume global
    // uniqueness when they only own the aggregate range diagnostic above.
    Log() << "[TSP_ROOMOBJ_V30] unload-purge parked=0";
}
'''


def sample_visibility():
    return '''#include <atomic>
namespace MWRender
{
// TSP_ROOM_RENDER_SAFETY_051_V30_R9
void f()
{
    constexpr double tspGameplayCullBypass = 1600.0;
    const double tspGameplayNearSurface = std::max(0.0, center.length() - radius);
    const double nearestSurface=5.0;
}
}
'''


def sample_header():
    return '''namespace MWRender
{
    bool isInteriorTopologyPvsEnabled();
}
'''


def sample_binding():
    return '''void init()
{
    api["setInteriorTopologyPvs"] = []() {};
    api["clearInteriorTopologyPvs"] = []() {};
}
'''


def selftest():
    sc, vi, vh, cb = patch_all(sample_scene(), sample_visibility(), sample_header(), sample_binding())
    assert '850.f' in sc and '1700.f : 2600.f' in sc
    assert '450.f' in sc and '650.f' in sc
    assert '500.0' in vi and '1000.0 : 1450.0' in vi
    assert 'void setInteriorAdaptiveRangeMode(int mode);' in vh
    assert 'api["setInteriorAdaptiveRangeMode"]' in cb
    assert all(text.count(MARK) >= 1 for text in (sc, vi, vh, cb))
    assert '[TSP_ROOMOBJ_V30] lightNearXY=2800 lightNearZ=384' not in sc
    assert '[TSP_ROOMOBJ_V30] adaptiveRangeMode=" << MWRender::getInteriorAdaptiveRangeMode()' in sc
    assert 'ordinaryWakeXY=1100 ordinaryHoldXY=1450' in sc
    aggregate_lines = [
        line for line in sc.splitlines()
        if '[TSP_ROOMOBJ_V30] adaptiveRangeMode=' in line
    ]
    assert len(aggregate_lines) == 1
    assert sum('[TSP_ROOMOBJ_V30]' in line for line in sc.splitlines()) == 2
    log_line = aggregate_lines[0]
    assert '<< tspAdaptiveRangeMode' not in log_line
    assert '<< tspRoomLightNearXY' not in log_line
    assert '<< tspRoomLightNearZ' not in log_line
    print('PASS R10 C++ patcher selftest: scope-safe log + three ranges + Lua bridge')


if len(sys.argv) == 2 and sys.argv[1] == '--selftest':
    selftest()
    raise SystemExit(0)
if len(sys.argv) == 3 and sys.argv[1] == '--emit-scene-selftest':
    write(sys.argv[2], patch_scene(sample_scene()))
    print('PASS emitted scope-accurate transformed scene fixture: ' + sys.argv[2])
    raise SystemExit(0)
if len(sys.argv) != 5:
    raise SystemExit('usage: patch_r10.py SCENE_CPP INTERIORVIS_CPP INTERIORVIS_HPP CAMERABIND_CPP | --selftest | --emit-scene-selftest PATH')

scene_path, vis_path, vish_path, cambind_path = sys.argv[1:5]
sc, vi, vh, cb = patch_all(read(scene_path), read(vis_path), read(vish_path), read(cambind_path))
write(scene_path, sc)
write(vis_path, vi)
write(vish_path, vh)
write(cambind_path, cb)
print('PASS R10 four-file C++ source patch applied')
PY_PATCH

if ! python3 -m py_compile "$TMP/patch_r10.py"; then
    fail 44 "embedded R10 C++ Python patcher does not compile"
fi
if ! python3 "$TMP/patch_r10.py" --selftest; then
    fail 45 "R10 C++ patcher selftest failed"
fi
if ! python3 "$TMP/patch_r10.py" --emit-scene-selftest "$TMP/r10-scene-scope-selftest.cpp"; then
    fail 73 "could not emit scope-accurate R10 C++ fixture"
fi
if ! docker cp "$TMP/r10-scene-scope-selftest.cpp" "$CTR:/tmp/r10-scene-scope-selftest.cpp" >/dev/null; then
    fail 74 "could not stage scope-accurate R10 C++ fixture"
fi
if ! docker exec "$CTR" bash -lc '
    CXX=""
    for candidate in g++-13 g++ c++; do
        if command -v "$candidate" >/dev/null 2>&1; then CXX="$candidate"; break; fi
    done
    if [ -z "$CXX" ]; then echo "FAIL no C++ compiler for R10 fixture" >&2; exit 1; fi
    "$CXX" -std=c++20 -fsyntax-only /tmp/r10-scene-scope-selftest.cpp
'; then
    fail 75 "scope-accurate transformed R10 scene fixture does not compile"
fi
echo "PASS R10 C++ patcher validated structurally and with scope-accurate compiler test"

echo
cat > "$TMP/patch_r10_lua.py" <<'PY_LUA'
#!/usr/bin/env python3
import re
import sys

MARK = 'TSP_ROOMRAY_LUA_V30_R10_THREE_RANGE'


def read(path):
    with open(path, 'r', encoding='utf-8', newline='') as f:
        return f.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def patch_lua(src):
    for token in (
        'TSP_VISGRID_LUA_V30_R4_SAME_FLOOR_PROXIMITY',
        'camera.viewportToWorldVector',
        'nearby.castRay',
        'RAY_MASK',
        'mapState.updateTopologyPvs',
        'engineHandlers',
    ):
        if token not in src:
            raise RuntimeError('R4 Lua precondition missing: ' + token)
    if MARK in src or 'setInteriorAdaptiveRangeMode' in src:
        raise RuntimeError('R10 Lua already present')

    handler_pattern = re.compile(
        r"(?m)^(?P<indent>[ \t]*)onFrame[ \t]*=[ \t]*function[ \t]*"
        r"\([ \t]*dt[ \t]*\)[ \t]*guarded[ \t]*\([ \t]*"
        r"[\"']onFrame[\"'][ \t]*,[ \t]*"
        r"(?P<base>mapState\.[A-Za-z_][A-Za-z0-9_]*)[ \t]*,[ \t]*dt[ \t]*"
        r"\)[ \t]*end[ \t]*,?[ \t]*$"
    )
    matches = list(handler_pattern.finditer(src))
    if len(matches) != 1:
        candidates = [line for line in src.splitlines()
                      if 'onFrame' in line and 'guarded' in line]
        raise RuntimeError('R4 onFrame handler matches=%d expected 1 candidates=%r'
                           % (len(matches), candidates[-20:]))
    handler = matches[0]
    base = handler.group('base')
    indent = handler.group('indent')

    # R4 returns engineHandlers as a field of its final module table:
    #     return {
    #         engineHandlers = {
    # R10-R1 originally assumed a nonexistent `local engineHandlers = {` and
    # failed on the exact live R4 shape. Anchor the insertion before the unique
    # top-level return table instead; inserting immediately before the field
    # itself would place statements inside a Lua table constructor.
    engine_field_pattern = re.compile(
        r'(?m)^[ \t]*engineHandlers[ \t]*=[ \t]*\{[ \t]*$')
    engine_fields = list(engine_field_pattern.finditer(src))
    if len(engine_fields) != 1:
        candidates = [line for line in src.splitlines() if 'engineHandlers' in line]
        raise RuntimeError('R4 engineHandlers field matches=%d expected 1 candidates=%r'
                           % (len(engine_fields), candidates[-20:]))

    return_pattern = re.compile(r'(?m)^return[ \t]*\{[ \t]*$')
    returns = [m for m in return_pattern.finditer(src)
               if m.start() < engine_fields[0].start()]
    if len(returns) != 1:
        candidates = [line for line in src.splitlines()
                      if line.lstrip().startswith('return {')]
        raise RuntimeError('R4 top-level return anchor matches=%d expected 1 candidates=%r'
                           % (len(returns), candidates[-20:]))

    block = r'''-- TSP_ROOMRAY_LUA_V30_R10_THREE_RANGE
-- Four casts per 0.20-second sample. Center is fixed; left/right/up sweep an
-- eight-phase ring. R4 navmesh kind/AABB supplies a live prior. Forward ray
-- depths are averaged with the longest ray carrying 65% of the weight.
-- Expansion evidence is applied about ten times faster than shrink evidence;
-- the delta-to-target update naturally tapers repeated reports. Old evidence
-- becomes negligible as new samples arrive, and every cell/topology change
-- resets the complete evidence slate.
mapState.r10BaseOnFrame = BASE_CALLBACK
mapState.r10RayElapsed = 0.0
mapState.r10ReportElapsed = 0.0
mapState.r10RayPhase = 1
mapState.r10RangeMode = 0
mapState.r10SpaceScore = 1.5
mapState.r10TightSupport = 0
mapState.r10SmallSupport = 0
mapState.r10LongBurst = 0
mapState.r10SampleCount = 0
mapState.r10WeightedDepth = 2400.0
mapState.r10TopoPrior = 1.5
mapState.r10TopoKind = 'unknown'
mapState.r10TopoSpan = 0.0
mapState.r10LastCell = nil
mapState.r10LastTopoCell = nil
mapState.r10BridgeErrorPrinted = false
mapState.r10RayPeriod = 0.20
mapState.r10ReportPeriod = 5.0
mapState.r10RayLength = 2400.0
mapState.r10TightEnter = 1200.0
mapState.r10TightExit = 1350.0
mapState.r10VeryEnter = 700.0
mapState.r10VeryExit = 900.0
mapState.r10UpVeto = 1500.0
mapState.r10VerySamples = 40
mapState.r10TightSamples = 8
mapState.r10SweepRadius = 0.065
mapState.r10Phases = {
    { 1.0000,  0.0000 }, { 0.7071,  0.7071 },
    { 0.0000,  1.0000 }, {-0.7071,  0.7071 },
    {-1.0000,  0.0000 }, {-0.7071, -0.7071 },
    { 0.0000, -1.0000 }, { 0.7071, -0.7071 },
}

mapState.r10Clamp = function(value, low, high)
    return math.max(low, math.min(high, tonumber(value or low) or low))
end

mapState.r10ModeName = function(mode)
    mode = tonumber(mode or 0) or 0
    return mode == 2 and 'very-tight' or (mode == 1 and 'tight' or 'open')
end

mapState.r10SetRangeMode = function(mode, reason, distances)
    mode = mapState.r10Clamp(mode, 0, 2)
    if camera.setInteriorAdaptiveRangeMode == nil then
        if not mapState.r10BridgeErrorPrinted then
            mapState.r10BridgeErrorPrinted = true
            print('[TSP_ROOMRAY_R10] BRIDGE ERROR setInteriorAdaptiveRangeMode unavailable')
        end
        return
    end
    if mode == mapState.r10RangeMode then return end
    local ok, err = pcall(camera.setInteriorAdaptiveRangeMode, mode)
    if not ok then
        if not mapState.r10BridgeErrorPrinted then
            mapState.r10BridgeErrorPrinted = true
            print('[TSP_ROOMRAY_R10] BRIDGE ERROR ' .. tostring(err))
        end
        return
    end
    mapState.r10RangeMode = mode
    local detail = distances and string.format(' L=%.0f C=%.0f R=%.0f U=%.0f',
        distances[1] or -1, distances[2] or -1,
        distances[3] or -1, distances[4] or -1) or ''
    print(string.format(
        '[TSP_ROOMRAY_R10] mode=%s reason=%s score=%.2f topo=%s/%.2f small=%d tight=%d long=%d%s',
        mapState.r10ModeName(mode), tostring(reason or '?'),
        tonumber(mapState.r10SpaceScore or 0) or 0,
        tostring(mapState.r10TopoKind or '?'),
        tonumber(mapState.r10TopoPrior or 0) or 0,
        tonumber(mapState.r10SmallSupport or 0) or 0,
        tonumber(mapState.r10TightSupport or 0) or 0,
        tonumber(mapState.r10LongBurst or 0) or 0, detail))
end

mapState.r10TopologyPrior = function()
    local tc = mapState.topoCell
    local sectors = tc and tc.sectors or nil
    local current = tonumber(mapState.topoSectorId or 0) or 0
    local sec = sectors and current > 0 and sectors[current] or nil
    if sec == nil then return 1.45, 'unmapped', 0.0 end

    local kind = tostring(sec.kind or 'room')
    local b = sec.bbox
    local span = 0.0
    if b ~= nil and #b >= 6 then
        local sx = math.max(0.0, (tonumber(b[4] or 0) or 0) - (tonumber(b[1] or 0) or 0))
        local sy = math.max(0.0, (tonumber(b[5] or 0) or 0) - (tonumber(b[2] or 0) or 0))
        span = math.max(sx, sy)
    end

    local prior = 0.55
    if kind == 'large_open' then
        prior = 2.0
    elseif kind == 'corridor' then
        prior = 1.10
    elseif kind == 'small_room' then
        prior = 0.30
    elseif kind == 'vertical_connector' then
        prior = 1.15
    elseif span >= 2200.0 then
        prior = 1.85
    elseif span >= 1200.0 then
        prior = 1.20
    end

    local active = tonumber(mapState.pvsActiveCount or 0) or 0
    if active >= 4 then prior = math.min(2.0, prior + 0.15) end
    return prior, kind, span
end

mapState.r10ResetAuthority = function(reason)
    local prior, kind, span = mapState.r10TopologyPrior()
    mapState.r10TopoPrior = prior
    mapState.r10TopoKind = kind
    mapState.r10TopoSpan = span
    mapState.r10SpaceScore = prior
    mapState.r10TightSupport = 0
    mapState.r10SmallSupport = 0
    mapState.r10LongBurst = 0
    mapState.r10SampleCount = 0
    mapState.r10ReportElapsed = 0.0
    local initialMode = prior >= 1.45 and 0 or 1
    mapState.r10SetRangeMode(initialMode, 'authority-reset-' .. tostring(reason or '?'), nil)
    print(string.format(
        '[TSP_ROOMRAY_R10] authority-reset reason=%s mode=%s topo=%s prior=%.2f span=%.0f active=%d',
        tostring(reason or '?'), mapState.r10ModeName(initialMode), kind, prior, span,
        tonumber(mapState.pvsActiveCount or 0) or 0))
end

mapState.r10CastDirection = function(eye, u, v)
    local okDir, dir = pcall(camera.viewportToWorldVector, util.vector2(u, v))
    if not okDir or dir == nil then return nil end
    local okLen, len = pcall(function() return dir:length() end)
    if not okLen or len == nil or len <= 0.0001 then return nil end
    local dest = eye + (dir / len) * mapState.r10RayLength
    local okRay, result = pcall(nearby.castRay, eye, dest, { collisionType = RAY_MASK })
    if not okRay or result == nil then return nil end
    if result.hit and result.hitPos ~= nil then
        local okDist, distance = pcall(function() return (result.hitPos - eye):length() end)
        if okDist and distance ~= nil then return distance end
        return nil
    end
    -- A clean miss is an OPEN witness, not an API failure.
    return mapState.r10RayLength
end

mapState.r10SampleFour = function()
    local eye = camera.getPosition()
    if eye == nil then return nil end
    eye = eye + util.vector3(0, 0, 16.0)
    local phase = mapState.r10Phases[mapState.r10RayPhase] or {1.0, 0.0}
    mapState.r10RayPhase = mapState.r10RayPhase % #mapState.r10Phases + 1
    local dx = phase[1] * mapState.r10SweepRadius
    local dy = phase[2] * mapState.r10SweepRadius
    -- Exactly four calls. The true center sample never rotates away from a door.
    local distances = {
        mapState.r10CastDirection(eye, 0.28 + dx, 0.50 + dy),
        mapState.r10CastDirection(eye, 0.50,      0.50),
        mapState.r10CastDirection(eye, 0.72 - dx, 0.50 - dy),
        mapState.r10CastDirection(eye, 0.50 + dy, 0.24 + dx),
    }
    for i = 1, 4 do
        if distances[i] == nil then return nil end
    end
    return distances
end

mapState.r10DepthTarget = function(depth)
    depth = mapState.r10Clamp(depth, 0.0, mapState.r10RayLength)
    if depth <= 700.0 then return 0.15 end
    if depth <= 1200.0 then return 0.15 + (depth - 700.0) * (0.85 / 500.0) end
    return math.min(2.0, 1.0 + (depth - 1200.0) / 1000.0)
end

mapState.r10AuthorityReport = function(distances)
    local detail = distances and string.format(' L=%.0f C=%.0f R=%.0f U=%.0f',
        distances[1] or -1, distances[2] or -1,
        distances[3] or -1, distances[4] or -1) or ''
    print(string.format(
        '[TSP_ROOMRAY_R10] authority mode=%s score=%.2f weighted=%.0f topo=%s/%.2f span=%.0f active=%d small=%d/40 tight=%d/8 long=%d samples=%d%s',
        mapState.r10ModeName(mapState.r10RangeMode),
        tonumber(mapState.r10SpaceScore or 0) or 0,
        tonumber(mapState.r10WeightedDepth or 0) or 0,
        tostring(mapState.r10TopoKind or '?'),
        tonumber(mapState.r10TopoPrior or 0) or 0,
        tonumber(mapState.r10TopoSpan or 0) or 0,
        tonumber(mapState.pvsActiveCount or 0) or 0,
        tonumber(mapState.r10SmallSupport or 0) or 0,
        tonumber(mapState.r10TightSupport or 0) or 0,
        tonumber(mapState.r10LongBurst or 0) or 0,
        tonumber(mapState.r10SampleCount or 0) or 0, detail))
end

mapState.r10Classify = function(distances)
    if distances == nil then
        -- An API/direction failure is not geometric evidence. Fail fully open.
        mapState.r10TightSupport = 0
        mapState.r10SmallSupport = 0
        mapState.r10LongBurst = 2
        mapState.r10SpaceScore = 2.0
        mapState.r10SetRangeMode(0, 'ray-api-failure', nil)
        return
    end

    local ordered = { distances[1], distances[2], distances[3] }
    table.sort(ordered)
    local forwardMax = ordered[3]
    local weighted = ordered[1] * 0.10 + ordered[2] * 0.25 + ordered[3] * 0.65
    local up = distances[4]
    local allSmall = forwardMax <= mapState.r10VeryEnter
    local allTight = forwardMax <= mapState.r10TightEnter
    mapState.r10WeightedDepth = weighted
    mapState.r10SampleCount = mapState.r10SampleCount + 1

    if allSmall and up <= mapState.r10UpVeto then
        mapState.r10SmallSupport = math.min(mapState.r10VerySamples,
            mapState.r10SmallSupport + 1)
        mapState.r10TightSupport = math.min(mapState.r10VerySamples,
            mapState.r10TightSupport + 1)
    elseif allTight then
        mapState.r10SmallSupport = math.max(0, mapState.r10SmallSupport - 2)
        mapState.r10TightSupport = math.min(mapState.r10VerySamples,
            mapState.r10TightSupport + 1)
    else
        mapState.r10SmallSupport = math.max(0, mapState.r10SmallSupport - 10)
        mapState.r10TightSupport = math.max(0, mapState.r10TightSupport - 3)
    end

    if forwardMax > mapState.r10TightExit then
        mapState.r10LongBurst = math.min(3, mapState.r10LongBurst + 1)
    else
        mapState.r10LongBurst = math.max(0, mapState.r10LongBurst - 1)
    end

    local prior, kind, span = mapState.r10TopologyPrior()
    mapState.r10TopoPrior = prior
    mapState.r10TopoKind = kind
    mapState.r10TopoSpan = span

    local target = mapState.r10DepthTarget(weighted)
    if up > mapState.r10UpVeto then
        local upTarget = 1.25 + math.min(0.75,
            (up - mapState.r10UpVeto) / 900.0 * 0.75)
        target = math.max(target, upTarget)
    end

    -- Asymmetric decaying evidence: upward/open reports move roughly 10x as
    -- fast as sustained shrink reports. Both updates are delta-to-target, so
    -- the influence of repeated identical reports tapers instead of growing
    -- without bound. A 1% live topology pull remains overridable by long-term
    -- ray agreement.
    local alpha = 0.055
    if target > mapState.r10SpaceScore then
        alpha = forwardMax >= 1800.0 and 0.58 or 0.38
    end
    mapState.r10SpaceScore = mapState.r10SpaceScore
        + (target - mapState.r10SpaceScore) * alpha
    mapState.r10SpaceScore = mapState.r10SpaceScore
        + (prior - mapState.r10SpaceScore) * 0.01
    mapState.r10SpaceScore = mapState.r10Clamp(mapState.r10SpaceScore, 0.0, 2.0)

    local current = mapState.r10RangeMode
    local desired = current
    local reason = 'hold'

    -- One contradictory opening immediately removes VERY_TIGHT. A second
    -- continuing long report advances TIGHT to OPEN. This preserves the
    -- requested medium step while making doorway/open-room recovery fast.
    if current == 2 and (forwardMax > mapState.r10VeryExit or up > mapState.r10UpVeto) then
        desired = 1
        reason = 'first-opening-witness'
    elseif forwardMax > mapState.r10TightExit and mapState.r10LongBurst >= 2 then
        desired = 0
        reason = 'two-long-witnesses'
    elseif current == 1 and mapState.r10SpaceScore >= 1.50
        and forwardMax <= mapState.r10TightExit then
        desired = 0
        reason = 'authority-open'
    elseif allSmall and up <= mapState.r10UpVeto
        and mapState.r10SmallSupport >= mapState.r10VerySamples
        and mapState.r10SpaceScore <= 0.68 then
        desired = 2
        reason = 'sustained-all-three-small'
    elseif current == 0 and allTight
        and mapState.r10TightSupport >= mapState.r10TightSamples
        and mapState.r10SpaceScore <= 1.20 then
        desired = 1
        reason = 'weighted-tight-authority'
    end

    mapState.r10SetRangeMode(desired, reason, distances)
end

mapState.r10RayUpdate = function(dt)
    local cell = self.cell
    if cell == nil or cell.isExterior then
        mapState.r10LastCell = cell
        mapState.r10LastTopoCell = nil
        mapState.r10TightSupport = 0
        mapState.r10SmallSupport = 0
        mapState.r10LongBurst = 0
        mapState.r10SpaceScore = 2.0
        mapState.r10SetRangeMode(0, 'not-interior', nil)
        return
    end

    if mapState.r10LastCell ~= cell or mapState.r10LastTopoCell ~= mapState.topoCell then
        local reason = mapState.r10LastCell ~= cell and 'cell-change' or 'topology-change'
        mapState.r10LastCell = cell
        mapState.r10LastTopoCell = mapState.topoCell
        mapState.r10ResetAuthority(reason)
    end

    mapState.r10RayElapsed = mapState.r10RayElapsed + math.max(0.0, tonumber(dt or 0) or 0)
    if mapState.r10RayElapsed < mapState.r10RayPeriod then return end
    mapState.r10RayElapsed = 0.0
    local distances = mapState.r10SampleFour()
    mapState.r10Classify(distances)
    mapState.r10ReportElapsed = mapState.r10ReportElapsed + mapState.r10RayPeriod
    if mapState.r10ReportElapsed >= mapState.r10ReportPeriod then
        mapState.r10ReportElapsed = 0.0
        mapState.r10AuthorityReport(distances)
    end
end

mapState.r10OnFrame = function(dt)
    mapState.r10BaseOnFrame(dt)
    mapState.r10RayUpdate(dt)
end

print('[TSP_ROOMRAY_R10] enabled rays=4 period=0.20 phases=8 authority=decay+topology long-weight=0.65 very-support=40 open=2600/1450 tight=1700/1000 very=850/500')

'''.replace('BASE_CALLBACK', base)

    insert_pos = returns[0].start()
    src = src[:insert_pos] + block + src[insert_pos:]

    handler_matches = list(handler_pattern.finditer(src))
    if len(handler_matches) != 1:
        raise RuntimeError('onFrame handler changed unexpectedly after R10 insertion')
    handler = handler_matches[0]
    replacement = indent + "onFrame = function(dt) guarded('onFrame', mapState.r10OnFrame, dt) end,"
    src = src[:handler.start()] + replacement + src[handler.end():]

    required = (
        MARK,
        'mapState.r10RayPeriod = 0.20',
        'mapState.r10VeryEnter = 700.0',
        'mapState.r10VeryExit = 900.0',
        'mapState.r10VerySamples = 40',
        'mapState.r10TopologyPrior = function()',
        'ordered[3] * 0.65',
        "reason = 'first-opening-witness'",
        "reason = 'two-long-witnesses'",
        "reason = 'sustained-all-three-small'",
        "'cell-change' or 'topology-change'",
        'mapState.r10CastDirection(eye, 0.50,      0.50)',
        "guarded('onFrame', mapState.r10OnFrame, dt)",
        'rays=4 period=0.20 phases=8 authority=decay+topology',
    )
    for token in required:
        if token not in src:
            raise RuntimeError('R10 Lua postcondition missing: ' + token)
    if src.count('mapState.r10CastDirection(eye,') != 4:
        raise RuntimeError('R10 sample does not contain exactly four cast call sites')
    return src


def sample():
    return '''local camera = require('openmw.camera')
local nearby = require('openmw.nearby')
local self = require('openmw.self')
local util = require('openmw.util')
local RAY_MASK = 1
local mapState = {}
-- TSP_VISGRID_LUA_V30_R4_SAME_FLOOR_PROXIMITY
camera.viewportToWorldVector(util.vector2(0.5,0.5))
nearby.castRay(a,b,{ collisionType = RAY_MASK })
mapState.updateTopologyPvs = function() end
mapState.base = function(dt) end
local function guarded(name, fn, dt) fn(dt) end
return {
    engineHandlers = {
        onFrame = function(dt) guarded('onFrame', mapState.base, dt) end,
    },
}
'''


def selftest():
    out = patch_lua(sample())
    assert out.count('mapState.r10CastDirection(eye,') == 4
    assert 'r10VeryEnter = 700.0' in out
    assert 'r10VerySamples = 40' in out
    assert 'r10TopologyPrior = function()' in out
    assert 'ordered[3] * 0.65' in out
    assert out.index('TSP_ROOMRAY_LUA_V30_R10_THREE_RANGE') < out.index('return {')
    assert "guarded('onFrame', mapState.r10OnFrame, dt)" in out
    print('PASS R10 Lua structural selftest: actual R4 return-table shape + four casts + decaying topology authority')


if len(sys.argv) == 2 and sys.argv[1] == '--selftest':
    selftest()
    raise SystemExit(0)
if len(sys.argv) != 3:
    raise SystemExit('usage: patch_r10_lua.py INPUT_R4_LUA OUTPUT_R10_LUA | --selftest')

write(sys.argv[2], patch_lua(read(sys.argv[1])))
print('PASS R10 four-ray three-range Lua generated')
PY_LUA

if ! python3 -m py_compile "$TMP/patch_r10_lua.py"; then
    fail 46 "embedded R10 Lua patcher does not compile"
fi
if ! python3 "$TMP/patch_r10_lua.py" --selftest; then
    fail 47 "R10 Lua patcher selftest failed"
fi
if ! python3 "$TMP/patch_r10_lua.py" "$TMP/visgrid-r4.lua" "$TMP/visgrid-r10.lua"; then
    fail 48 "R10 Lua generation failed"
fi

if ! docker cp "$TMP/visgrid-r10.lua" "$CTR:/tmp/visgrid-r10.lua" >/dev/null; then
    fail 49 "could not stage R10 Lua for syntax validation"
fi
LUA_PARSER="$(docker exec "$CTR" bash -lc 'for x in luajit lua texlua; do command -v "$x" >/dev/null 2>&1 && { echo "$x"; exit 0; }; done; exit 1' 2>/dev/null || true)"
if [ -n "$LUA_PARSER" ]; then
    if [ "$LUA_PARSER" = "texlua" ]; then
        # texlua is a LuaTeX launcher, not the standard lua CLI: it does not
        # accept lua/luajit's -e switch. --luaconly parses/compiles without
        # executing the OpenMW-only requires in the generated profile.
        if ! docker exec "$CTR" texlua --luaconly /tmp/visgrid-r10.lua; then
            fail 50 "generated R10 Lua syntax validation failed with texlua --luaconly"
        fi
        echo "LUA_PARSE_PASS /tmp/visgrid-r10.lua (texlua --luaconly)"
    else
        if ! docker exec -e R10_LUA_FILE=/tmp/visgrid-r10.lua "$CTR" "$LUA_PARSER" -e \
            'local p=os.getenv("R10_LUA_FILE"); local f,e=loadfile(p); assert(f,e); print("LUA_PARSE_PASS " .. p)'
        then
            fail 50 "generated R10 Lua syntax validation failed"
        fi
    fi
else
    echo "INFO: no Lua CLI in Docker; compiling a LuaJIT syntax checker."
    if ! docker exec -i "$CTR" bash -s <<'REMOTE_LUA_CHECK'
set -u
HEADER="$(find /usr/include /usr/local/include -type f -name lua.h -path '*luajit*' -print 2>/dev/null | head -1)"
if [ -z "$HEADER" ]; then echo "FAIL LuaJIT lua.h not found" >&2; exit 1; fi
INC="$(dirname "$HEADER")"
LIB="$(find /usr/lib /usr/local/lib \( -type f -o -type l \) -name 'libluajit-5.1.so*' -print 2>/dev/null | head -1)"
if [ -z "$LIB" ]; then echo "FAIL libluajit-5.1.so not found" >&2; exit 2; fi
CC=""
for c in gcc-13 gcc cc; do command -v "$c" >/dev/null 2>&1 && { CC="$c"; break; }; done
if [ -z "$CC" ]; then echo "FAIL no C compiler for LuaJIT checker" >&2; exit 3; fi
cat > /tmp/r10_lua_check.c <<'C_CHECK'
#include <stdio.h>
#include <lua.h>
#include <lauxlib.h>
int main(int argc, char **argv) {
    lua_State *L;
    int rc;
    if (argc != 2) return 2;
    L = luaL_newstate();
    if (!L) return 3;
    rc = luaL_loadfile(L, argv[1]);
    if (rc != 0) {
        const char *msg = lua_tostring(L, -1);
        fprintf(stderr, "LUA_PARSE_FAIL: %s\n", msg ? msg : "unknown");
        lua_close(L);
        return 4;
    }
    lua_close(L);
    printf("LUA_PARSE_PASS %s\n", argv[1]);
    return 0;
}
C_CHECK
"$CC" -O2 -I"$INC" /tmp/r10_lua_check.c "$LIB" -lm -ldl -pthread -o /tmp/r10_lua_check || exit 4
/tmp/r10_lua_check /tmp/visgrid-r10.lua || exit 5
REMOTE_LUA_CHECK
    then
        fail 51 "generated R10 Lua could not be syntax-validated"
    fi
fi
R10_LUA_SHA="$(sha256sum "$TMP/visgrid-r10.lua" | awk '{print $1}')"
echo "PASS R10 Lua SHA: $R10_LUA_SHA"

echo
echo "===== 5/9 APPLY R10 C++ PATCH + VERIFY SEMANTICS ====="

if ! docker cp "$TMP/patch_r10.py" "$CTR:/tmp/patch_r10.py" >/dev/null; then
    fail 52 "failed to copy R10 patcher into Docker"
fi
SOURCE_MUTATED=1
if ! docker exec "$CTR" python3 /tmp/patch_r10.py "$SCENE" "$VIS" "$VISH" "$CAMBIND"; then
    fail 53 "R10 source patch failed"
fi

if ! docker exec -i "$CTR" python3 - "$SCENE" "$ANIM" "$VIS" "$VISH" "$CAMBIND" <<'PY_VERIFY'
import sys
paths=sys.argv[1:6]
texts=[]
for p in paths:
    with open(p,'r',encoding='utf-8') as f:
        texts.append(f.read())
sc,an,vi,vh,cb=texts

checks = [
    (sc, 'TSP_ROOM_RENDER_SAFETY_051_V30_R9', 'scene R9 marker'),
    (sc, 'TSP_ROOM_ADAPTIVE_RANGE_051_V30_R10', 'scene R10 marker'),
    (sc, 'tspAdaptiveRangeMode >= 2 ? 850.f', 'very-tight light XY'),
    (sc, 'tspAdaptiveRangeMode == 1 ? 1700.f : 2600.f', 'tight/open light XY'),
    (sc, 'tspAdaptiveRangeMode >= 2 ? 450.f', 'very-tight ordinary wake'),
    (sc, 'tspAdaptiveRangeMode >= 2 ? 650.f', 'very-tight ordinary hold'),
    (sc, '[TSP_ROOMOBJ_V30] adaptiveRangeMode=" << MWRender::getInteriorAdaptiveRangeMode()',
     'scope-safe aggregate range log'),
    (an, 'TSP_ROOM_RENDER_SAFETY_051_V30_R9', 'animation R9 marker'),
    (an, 'const bool tspIsLight = mPtr.getType() == ESM::Light::sRecordId;', 'light classification'),
    (an, 'const bool tspPvsEligible = false;', 'gameplay callback topology PVS disabled'),
    (vi, 'TSP_ROOM_ADAPTIVE_RANGE_051_V30_R10', 'visibility R10 marker'),
    (vi, 'tspAdaptiveRangeMode >= 2 ? 500.0', 'very-tight gameplay safety'),
    (vi, 'tspAdaptiveRangeMode == 1 ? 1000.0 : 1450.0', 'tight/open gameplay safety'),
    (vi, 'const double nearestSurface=', 'far screen-depth path retained'),
    (vh, 'void setInteriorAdaptiveRangeMode(int mode);', 'range bridge header setter'),
    (vh, 'int getInteriorAdaptiveRangeMode();', 'range bridge header getter'),
    (cb, 'api["setInteriorAdaptiveRangeMode"]', 'range bridge Lua setter'),
    (cb, 'api["getInteriorAdaptiveRangeMode"]', 'range bridge Lua getter'),
]
for text, token, label in checks:
    if token not in text:
        raise SystemExit('FAIL semantic verify missing %s: %s' % (label, token))

for text, token, label in (
    (sc, 'tspRoomLightNearXY = 2800.f', 'obsolete R9 light XY'),
    (vi, 'tspGameplayCullBypass = 1600.0', 'obsolete R9 gameplay bypass'),
    (an, 'const bool tspPvsEligible = std::isfinite(tspPvsRadius)', 'obsolete callback topology PVS eligibility'),
    (an, 'mPtr.get<ESM::Static>()', 'unsafe Static cast'),
):
    if token in text:
        raise SystemExit('FAIL forbidden token survived %s: %s' % (label, token))

roomobj_lines = [
    line for line in sc.splitlines()
    if '[TSP_ROOMOBJ_V30] adaptiveRangeMode=' in line
]
if len(roomobj_lines) != 1:
    raise SystemExit('FAIL R10 aggregate room-object log line count=%d expected 1'
                     % len(roomobj_lines))
for token in ('<< tspAdaptiveRangeMode', '<< tspRoomLightNearXY', '<< tspRoomLightNearZ'):
    if token in roomobj_lines[0]:
        raise SystemExit('FAIL out-of-scope local survived in R10 room-object log: ' + token)

print('PASS R10 semantics: 2600/1450 open + 1700/1000 tight + 850/500 very-tight')
PY_VERIFY
then
    fail 54 "R10 post-patch semantic verification failed"
fi

echo
echo "===== 6/9 INVALIDATE EXACTLY THREE CHANGED TRANSLATION UNITS ====="

if ! docker exec -i "$CTR" bash -s -- "$BUILD" "$SCENE" "$VIS" "$VISH" "$CAMBIND" <<'REMOTE_INVALIDATE'
set -u
BUILD="$1"
SCENE="$2"
VIS="$3"
VISH="$4"
CAMBIND="$5"

SCENE_OBJ="$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwworld/scene.cpp.o"
VIS_OBJ="$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwrender/interiorvisibility.cpp.o"
CAMBIND_OBJ="$BUILD/apps/openmw/CMakeFiles/openmw-lib.dir/mwlua/camerabindings.cpp.o"

rm -f "$SCENE_OBJ" "$SCENE_OBJ.d" "$VIS_OBJ" "$VIS_OBJ.d" "$CAMBIND_OBJ" "$CAMBIND_OBJ.d"
touch "$SCENE" "$VIS" "$VISH" "$CAMBIND"

for obj in "$SCENE_OBJ" "$VIS_OBJ" "$CAMBIND_OBJ"; do
    if [ -e "$obj" ]; then
        echo "FAIL object survived invalidation: $obj" >&2
        exit 1
    fi
done

echo "PASS invalidated scene.cpp.o + interiorvisibility.cpp.o + camerabindings.cpp.o"
REMOTE_INVALIDATE
then
    fail 55 "R10 object invalidation failed"
fi

echo
echo "===== 7/9 BUILD + PROVE ALL THREE TRANSLATION UNITS RECOMPILED ====="

: > "$BUILDLOG"
if ! docker exec "$CTR" cmake --build "$BUILD" --target openmw --parallel 1 2>&1 | tee "$BUILDLOG"; then
    echo
    echo "===== R10 BUILD FAILURE TAIL ====="
    tail -320 "$BUILDLOG" || true
    fail 56 "R10 build failed; full log: $BUILDLOG"
fi

for needle in 'mwworld/scene.cpp.o' 'mwrender/interiorvisibility.cpp.o' 'mwlua/camerabindings.cpp.o'; do
    if ! grep -Fq "$needle" "$BUILDLOG"; then
        fail 57 "build log does not prove recompile: $needle"
    fi
    echo "PASS build log proves recompile: $needle"
done

echo
echo "===== 8/9 PACKAGE + ARM64/SHA VERIFY + INSTALL BINARY + LUA ====="

if ! docker exec -i "$CTR" bash -s -- "$BUILT" "$PACKAGED" <<'REMOTE_PACKAGE'
set -u
BUILT="$1"
PACKAGED="$2"
if [ ! -s "$BUILT" ]; then echo "FAIL rebuilt binary missing" >&2; exit 1; fi
if ! mkdir -p "$(dirname "$PACKAGED")"; then exit 2; fi
if ! install -m 755 "$BUILT" "$PACKAGED"; then exit 3; fi
file "$PACKAGED"
sha256sum "$PACKAGED"
REMOTE_PACKAGE
then
    fail 60 "R10 package failed"
fi

if ! docker cp "$CTR:$PACKAGED" "$HOSTBIN" >/dev/null; then
    fail 61 "Docker -> Ubuntu copy failed"
fi
if [ ! -s "$HOSTBIN" ]; then
    fail 62 "host R10 binary missing/empty"
fi
DESC="$(file "$HOSTBIN" 2>/dev/null || true)"
echo "$DESC"
if ! printf '%s\n' "$DESC" | grep -Eq 'ARM aarch64|ARM64|AArch64'; then
    fail 63 "host R10 binary is not ARM64/AArch64: $DESC"
fi
NEW_SHA="$(sha256sum "$HOSTBIN" | awk '{print $1}')"
if [ -z "$NEW_SHA" ]; then
    fail 64 "could not hash R10 host binary"
fi
if [ "$NEW_SHA" = "$EXPECTED_R9_SHA" ]; then
    fail 65 "R10 binary SHA unexpectedly equals R9 after verified semantic changes"
fi
echo "PASS R10 ARM64 host SHA: $NEW_SHA"

if ! scp -q "$HOSTBIN" "$DEV:$TMPBIN"; then
    fail 66 "R10 binary upload failed"
fi
if ! scp -q "$TMP/visgrid-r10.lua" "$DEV:$TMPLUA"; then
    fail 67 "R10 Lua upload failed"
fi
DEVICE_DEPLOYED=1
LUA_DEPLOYED=1
if ! ssh "$DEV" 'bash -s' -- "$TMPBIN" "$BIN" "$NEW_SHA" "$TMPLUA" "$LUA" "$PROFILE" "$R10_LUA_SHA" <<'REMOTE_INSTALL'
set -u
TMPBIN="$1"
BIN="$2"
EXPECTED_BIN="$3"
TMPLUA="$4"
LIVE_LUA="$5"
PROFILE="$6"
EXPECTED_LUA="$7"
if [ ! -s "$TMPBIN" ] || [ ! -s "$TMPLUA" ]; then echo "FAIL staged R10 input missing" >&2; exit 1; fi
INCOMING="$(sha256sum "$TMPBIN" | awk '{print $1}')"
if [ "$INCOMING" != "$EXPECTED_BIN" ]; then
    echo "FAIL binary upload SHA expected=$EXPECTED_BIN actual=$INCOMING" >&2
    exit 2
fi
INCOMING_LUA="$(sha256sum "$TMPLUA" | awk '{print $1}')"
if [ "$INCOMING_LUA" != "$EXPECTED_LUA" ]; then
    echo "FAIL Lua upload SHA expected=$EXPECTED_LUA actual=$INCOMING_LUA" >&2
    exit 3
fi
if ! install -m 755 "$TMPBIN" "$BIN"; then exit 4; fi
if ! install -m 644 "$TMPLUA" "$PROFILE"; then exit 5; fi
if ! install -m 644 "$TMPLUA" "$LIVE_LUA"; then exit 6; fi
rm -f "$TMPBIN" "$TMPLUA"
sync
FINAL="$(sha256sum "$BIN" | awk '{print $1}')"
if [ "$FINAL" != "$EXPECTED_BIN" ]; then
    echo "FAIL final binary SHA expected=$EXPECTED_BIN actual=$FINAL" >&2
    exit 7
fi
for f in "$PROFILE" "$LIVE_LUA"; do
    GOT="$(sha256sum "$f" | awk '{print $1}')"
    if [ "$GOT" != "$EXPECTED_LUA" ]; then
        echo "FAIL final Lua SHA expected=$EXPECTED_LUA actual=$GOT file=$f" >&2
        exit 8
    fi
    grep -Fq 'TSP_ROOMRAY_LUA_V30_R10_THREE_RANGE' "$f" || exit 9
done
echo "PASS installed exact R10 binary SHA: $FINAL"
echo "PASS installed exact R10 profile/live Lua SHA: $EXPECTED_LUA"
REMOTE_INSTALL
then
    fail 68 "R10 device install failed"
fi

FINAL_SHA="$(ssh "$DEV" "sha256sum '$BIN' | awk '{print \$1}'" 2>/dev/null || true)"
if [ "$FINAL_SHA" != "$NEW_SHA" ]; then
    fail 69 "final R10 device SHA verification failed"
fi
LUA_SHA_AFTER="$(ssh "$DEV" "sha256sum '$LUA' | awk '{print \$1}'" 2>/dev/null || true)"
if [ "$LUA_SHA_AFTER" != "$R10_LUA_SHA" ]; then
    echo "EXPECTED R10 LUA: $R10_LUA_SHA" >&2
    echo "ACTUAL R10 LUA:   $LUA_SHA_AFTER" >&2
    fail 70 "final R10 Lua SHA verification failed"
fi

echo
echo "===== 9/9 ARM CLEAN CAPTURE + SAVE EXACT R9/R4 ROLLBACK STATE ====="

if ! ssh "$DEV" 'bash -s' -- "$GAMELOG" "$ARM" <<'REMOTE_ARM'
set -u
LOG="$1"
ARM="$2"
if [ ! -f "$LOG" ]; then echo "FAIL log missing: $LOG" >&2; exit 1; fi
LINES="$(wc -l < "$LOG" | tr -d '[:space:]')"
case "$LINES" in ''|*[!0-9]*) echo "FAIL invalid log line count: $LINES" >&2; exit 2;; esac
if ! printf '%s\n' "$LINES" > "$ARM"; then exit 3; fi
echo "PASS R10 capture armed after log line: $LINES"
REMOTE_ARM
then
    fail 71 "R10 capture arm failed"
fi

cat > "$STATE" <<EOF_STATE
R10_SOURCE_BACKUP='$SOURCE_BACKUP'
R10_DEVICE_BACKUP='$DEVICE_BACKUP'
R10_OLD_SHA='$EXPECTED_R9_SHA'
R10_NEW_SHA='$NEW_SHA'
R10_OLD_LUA_SHA='$EXPECTED_R4_LUA_SHA'
R10_NEW_LUA_SHA='$R10_LUA_SHA'
R10_HOST_BIN='$HOSTBIN'
EOF_STATE
if [ ! -s "$STATE" ]; then
    fail 72 "R10 state file was not written: $STATE"
fi

SOURCE_MUTATED=0
DEVICE_DEPLOYED=0
LUA_DEPLOYED=0

echo
echo "============================================================"
echo "V30 R10-R1 FOUR-RAY THREE-RANGE CONTROLLER INSTALLED"
echo "============================================================"
echo "R9 SHA:     $EXPECTED_R9_SHA"
echo "R10 SHA:    $FINAL_SHA"
echo "R4 Lua:     $EXPECTED_R4_LUA_SHA"
echo "R10 Lua:    $LUA_SHA_AFTER"
echo "Host bin:  $HOSTBIN"
echo "State:     $STATE"
echo
echo "Test once:"
echo "  1. Tight corridor: after ~8 seconds confirm mode=very-tight and improved FPS"
echo "  2. Walk toward an open doorway: confirm first opening witness -> tight, then open"
echo "  3. Ald-ruhn hall + Arobar doors: confirm the R9 visual fix remains"
echo "  4. Validation should show 5-second authority score/topology/depth lines"
echo
echo "Then collect:"
echo "  cd ~/Downloads"
echo "  ./apply_openmw51_tsp_roomwake_v30_R10_R1_four_ray_three_range.sh collect"
echo
echo "Rollback to exact R9 binary + R4 Lua:"
echo "  ./apply_openmw51_tsp_roomwake_v30_R10_R1_four_ray_three_range.sh rollback"
echo "============================================================"
