#!/usr/bin/env bash
set -Eeuo pipefail

cd "$HOME/Downloads"

ROOT="/mnt/SDCARD/data/ports/openmw51"
BASE="$ROOT/mods/TSPInteriorVisGrid/scripts/TSPInteriorVisGrid"
LUA="$BASE/visgrid.lua"
TOPO="$BASE/topology.lua"
TOPO_CELLS="$BASE/topology_cells"
DOOR="$BASE/doorgraph.lua"
DB="/mnt/UDISK/openmw51-nav/navmesh.db"
BIN="$ROOT/bin/openmw-0.51"

if [ -f "$HOME/Downloads/visgrid-tools/device.env" ]; then
    . "$HOME/Downloads/visgrid-tools/device.env" || true
fi
if [ -n "${TSP_DEV:-}" ]; then DEV="$TSP_DEV"
elif [ -n "${TSP_IP:-}" ]; then DEV="root@$TSP_IP"
else DEV="root@192.168.1.25"; fi
SSH=(-o BatchMode=yes -o ConnectTimeout=8)

EXPECTED_BASE_SHA="6dabab5641894968b51c2a8399ac206926662d4182d8445bb710ef7a0e2a7c45"
EXPECTED_NEW_SHA="4556f20dc78620843f624c91ca91be74254d75d423a007fac0ba1d0bc12e1c25"
EXPECTED_PATCH_SHA="071dabe718829239023e64108ef3cb641252d67c241a2bfb62b351ee161ea73a"

STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$HOME/Downloads/openmw51-visgrid-v22-2-intercell-$STAMP"
LOG="$OUT/controller.log"
mkdir -p "$OUT"
exec > >(tee "$LOG") 2>&1

fail() {
    rc=$?
    line="${1:-?}"
    cmd="${2:-?}"
    trap - ERR
    echo
    echo "=================================================================="
    echo "V22.2 INTERCELL HANDOFF INSTALLER STOPPED"
    echo "=================================================================="
    echo "exit=$rc line=$line"
    echo "command: $cmd"
    echo "No automatic rerun was attempted."
    echo "Log: $LOG"
    exit "$rc"
}
trap 'fail "$LINENO" "$BASH_COMMAND"' ERR

cat <<'BANNER'
==================================================================
OPENMW 0.51 — VISGRID V22.2 INTERIOR→INTERIOR HANDOFF
==================================================================
This fixes the destination-side cold-start hole seen on some load doors.

On every real interior->interior cell change it now:
  - notices the transition even if the 6s load-safe gate is still active
  - discards source-cell sector/latch ids before entering the new topology
  - finds the reverse ESM/ESP load door back to the source cell when possible
  - pins current + reverse-door + nearby two-hop destination sectors for 5s
  - caps that temporary handoff bubble at 12 topology sectors
  - fully opens the VISGRID curtain for the first 1.35s INSIDE that PVS bubble
  - then keeps a 4200 depth floor until the 5s handoff expires
  - falls back to a 4200 depth floor if destination topology is unavailable

After the handoff expires, normal V22/V22.1 resident/ray/upward logic resumes.
This modifies visgrid.lua only.
Game binary, topology, doorgraph and canonical navmesh DB are snapshot-protected.
No OpenMW-running process gate is used.
==================================================================
BANNER

echo
echo "===== 1/7 FETCH EXACT LIVE V22.1 + SNAPSHOT PROTECTED STATE ====="
ssh "${SSH[@]}" "$DEV" "test -s '$LUA'; test -s '$BIN'; test -s '$TOPO'; test -s '$DOOR'; test -s '$DB'; test -d '$TOPO_CELLS'"
scp -q "${SSH[@]}" "$DEV:$LUA" "$OUT/visgrid-live.lua"

LIVE_SHA="$(sha256sum "$OUT/visgrid-live.lua" | awk '{print $1}')"
GAME_BEFORE="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$BIN'" | awk '{print $1}')"
TOPO_BEFORE="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$TOPO'" | awk '{print $1}')"
DOOR_BEFORE="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$DOOR'" | awk '{print $1}')"
DB_BEFORE="$(ssh "${SSH[@]}" "$DEV" "stat -c '%s %Y' '$DB'")"
SHARDS_BEFORE="$(ssh "${SSH[@]}" "$DEV" "find '$TOPO_CELLS' -type f -name '*.lua' | wc -l")"

printf 'sensor SHA:    %s\n' "$LIVE_SHA"
printf 'game SHA:      %s\n' "$GAME_BEFORE"
printf 'topology SHA:  %s\n' "$TOPO_BEFORE"
printf 'doorgraph SHA: %s\n' "$DOOR_BEFORE"
printf 'DB size/mtime: %s\n' "$DB_BEFORE"
printf 'topology files:%s\n' "$SHARDS_BEFORE"

if [ "$LIVE_SHA" = "$EXPECTED_NEW_SHA" ]; then
    echo "PASS: exact V22.2 is already installed."
else
    [ "$LIVE_SHA" = "$EXPECTED_BASE_SHA" ] || {
        echo "ERROR: this patch targets the exact V22.1 sensor from your latest trace."
        echo "Expected V22.1: $EXPECTED_BASE_SHA"
        echo "Live:           $LIVE_SHA"
        echo "Nothing changed."
        exit 20
    }
fi

grep -Fq 'TSP_VISGRID_LUA_V22_1_UPWARD_ANTICIPATION' "$OUT/visgrid-live.lua"
grep -Fq 'TSP_VISGRID_REAL_DOOR_GRAPH_V1' <(ssh "${SSH[@]}" "$DEV" "cat '$DOOR'")
grep -Fq 'TSP_VISGRID_GLOBAL_TOPOLOGY_V1' <(ssh "${SSH[@]}" "$DEV" "head -40 '$TOPO'")
echo "PASS: exact latest sensor lineage + real-door + global-topology sidecars present."

if [ "$LIVE_SHA" != "$EXPECTED_NEW_SHA" ]; then
    echo
    echo "===== 2/7 RECREATE SELF-TESTED V22.1 -> V22.2 PATCHER ====="
    cat > "$OUT/patch.py.b64" <<'PATCH_B64'
ZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmltcG9ydCBoYXNobGliCgppbXBvcnQgc3lzCmlmIGxl
bihzeXMuYXJndikgIT0gMzoKICAgIHJhaXNlIFN5c3RlbUV4aXQoJ3VzYWdlOiBwYXRjaF92MjJf
Mi5weSBJTlBVVF9WMjJfMSBPVVRQVVRfVjIyXzInKQpzcmMgPSBQYXRoKHN5cy5hcmd2WzFdKQpk
c3QgPSBQYXRoKHN5cy5hcmd2WzJdKQpzID0gc3JjLnJlYWRfdGV4dChlbmNvZGluZz0ndXRmLTgn
KQpFWFBFQ1RFRCA9ICc2ZGFiYWI1NjQxODk0OTY4YjUxYzJhODM5OWFjMjA2OTI2NjYyZDQxODJk
ODQ0NWJiNzEwZWY3YTBlMmE3YzQ1JwpFWFBFQ1RFRF9PVVQgPSAnNDU1NmYyMGRjNzg2MjA4NDNm
NjI0YzkxY2E5MWJlNzQyNTRkNzVkNDIzYTAwN2ZhYzBiYTFkMGJjMTJlMWMyNScKc2hhID0gaGFz
aGxpYi5zaGEyNTYoc3JjLnJlYWRfYnl0ZXMoKSkuaGV4ZGlnZXN0KCkKaWYgc2hhICE9IEVYUEVD
VEVEOgogICAgcmFpc2UgU3lzdGVtRXhpdChmJ0VSUk9SOiBleGFjdCBWMjIuMSBTSEEgcmVxdWly
ZWQ7IGdvdCB7c2hhfScpCgpkZWYgcmVwKG9sZCxuZXcsbmFtZSk6CiAgICBnbG9iYWwgcwogICAg
Yz1zLmNvdW50KG9sZCkKICAgIGlmIGMgIT0gMToKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3Io
Zid7bmFtZX06IGV4cGVjdGVkIDEgYW5jaG9yLCBnb3Qge2N9JykKICAgIHM9cy5yZXBsYWNlKG9s
ZCxuZXcsMSkKCiMgTWFya2VyCnJlcCgKIi0tIFRTUF9WSVNHUklEX0xVQV9WMjJfMV9VUFdBUkRf
QU5USUNJUEFUSU9OICAoY2FtZXJhLVogbW9tZW50dW0gKyB2ZXJ0aWNhbCBwcmVkaWN0aXZlIHJh
eXMpXG4iLAoiLS0gVFNQX1ZJU0dSSURfTFVBX1YyMl8xX1VQV0FSRF9BTlRJQ0lQQVRJT04gIChj
YW1lcmEtWiBtb21lbnR1bSArIHZlcnRpY2FsIHByZWRpY3RpdmUgcmF5cylcbiIKIi0tIFRTUF9W
SVNHUklEX0xVQV9WMjJfMl9JTlRFUkNFTExfSEFORE9GRiAgKGRlc3RpbmF0aW9uIGFycml2YWwg
YnViYmxlICsgcmV2ZXJzZS1kb29yIGhhbmRvZmYpXG4iLAonbWFya2VyJykKCiMgU3RhdGUgZmll
bGRzCm9sZD0iIiIgICAgdXBCb29zdEV2ZW50cyA9IDAsIHVwUHJlZGljdENhc3RzID0gMCwgdXBE
ZWVwUmVwb3J0cyA9IDAsCiAgICB1cFB1bGxiYWNrcyA9IDAsIHVwRmxvb3JBcHBsaWNhdGlvbnMg
PSAwLAoKICAgIHB2c0JyaWRnZSA9IHR5cGUoY2FtZXJhLnNldEludGVyaW9yVG9wb2xvZ3lQdnMp
ID09ICdmdW5jdGlvbicKIiIiCm5ldz0iIiIgICAgdXBCb29zdEV2ZW50cyA9IDAsIHVwUHJlZGlj
dENhc3RzID0gMCwgdXBEZWVwUmVwb3J0cyA9IDAsCiAgICB1cFB1bGxiYWNrcyA9IDAsIHVwRmxv
b3JBcHBsaWNhdGlvbnMgPSAwLAoKICAgIC0tIFYyMi4yIGludGVyaW9yLT5pbnRlcmlvciBoYW5k
b2ZmLiBTZWN0b3IgaWRzIGFyZSBjZWxsLWxvY2FsLCBzbyBzb3VyY2UtY2VsbAogICAgLS0gbGF0
Y2hlcyBtdXN0IG5ldmVyIGJsZWVkIGludG8gdGhlIGRlc3RpbmF0aW9uLiBUaGUgZGVzdGluYXRp
b24gZ2V0cyBhIHNob3J0CiAgICAtLSBhcnJpdmFsIHdvcmtpbmcgc2V0IGNlbnRlcmVkIG9uIHRo
ZSBwbGF5ZXIgKyByZXZlcnNlIGxvYWQgZG9vciBpbnN0ZWFkLgogICAgY2VsbEhhbmRvZmZTZWN0
b3JzID0ge30sIGNlbGxIYW5kb2ZmQ291bnQgPSAwLAogICAgY2VsbEhhbmRvZmZVbnRpbCA9IDAu
MCwgY2VsbEhhbmRvZmZGdWxsVW50aWwgPSAwLjAsCiAgICBjZWxsSGFuZG9mZkRvb3JTZWN0b3Ig
PSAwLCBjZWxsSGFuZG9mZkV2ZW50cyA9IDAsCiAgICBjZWxsSGFuZG9mZkRvb3JNYXRjaGVzID0g
MCwgY2VsbEhhbmRvZmZGYWxsYmFja3MgPSAwLAogICAgY2VsbEhhbmRvZmZHcmlkRmxvb3JzID0g
MCwKICAgIGxvYWRTYWZlTGFzdENlbGwgPSBuaWwsIGxvYWRTYWZlVHJhbnNpdGlvbkZyb20gPSBu
aWwsCgogICAgcHZzQnJpZGdlID0gdHlwZShjYW1lcmEuc2V0SW50ZXJpb3JUb3BvbG9neVB2cykg
PT0gJ2Z1bmN0aW9uJwoiIiIKcmVwKG9sZCxuZXcsJ3N0YXRlIGZpZWxkcycpCgojIHBvbGljeQpv
bGQ9IiIiICAgIHYyMjFVcFByZWRpY3RCaW5zID0gMiwgICAgICAgICAgLS0gcGl0Y2ggYmlucyBh
aGVhZCBvZiBjZW50ZXIKICAgIHYyMjFVcEV4dHJhUmF5cyA9IDIsICAgICAgICAgICAgLS0gb25s
eSBkdXJpbmcgYnJpZWYgdXB3YXJkIGFudGljaXBhdGlvbgoKICAgIC0tIENvbnNlcnZhdGl2ZSBz
dGF0aWMtb2JqZWN0L3NlY3RvciBvdmVybGFwIG1hcmdpbnMgaW4gdGhlIEMrKyBQVlMuCiIiIgpu
ZXc9IiIiICAgIHYyMjFVcFByZWRpY3RCaW5zID0gMiwgICAgICAgICAgLS0gcGl0Y2ggYmlucyBh
aGVhZCBvZiBjZW50ZXIKICAgIHYyMjFVcEV4dHJhUmF5cyA9IDIsICAgICAgICAgICAgLS0gb25s
eSBkdXJpbmcgYnJpZWYgdXB3YXJkIGFudGljaXBhdGlvbgoKICAgIC0tIFYyMi4yIGNyb3NzLWNl
bGwgYXJyaXZhbCBwb2xpY3kuIEZvciBmaXZlIHNlY29uZHMgYWZ0ZXIgYW4gaW50ZXJpb3ItPmlu
dGVyaW9yCiAgICAtLSBsb2FkLCBwaW4gYSBib3VuZGVkIHR3by1ob3AgZGVzdGluYXRpb24gYnVi
YmxlLiBEdXJpbmcgdGhlIGZpcnN0IDEuMzVzIHRoZQogICAgLS0gVklTR1JJRCBjdXJ0YWluIGlz
IGZ1bGx5IG9wZW4gaW5zaWRlIHRoYXQgc3RydWN0dXJhbCBidWJibGUsIHRoZW4ga2VlcHMgYQog
ICAgLS0gNDIwMC11bml0IGZsb29yIGZvciB0aGUgcmVzdCBvZiB0aGUgaGFuZG9mZi4gVW5tYXBw
ZWQgY2VsbHMgbmV2ZXIgZ2V0IHRoZQogICAgLS0gZnVsbC1vcGVuIHBoYXNlOyB0aGV5IHJlY2Vp
dmUgb25seSB0aGUgYm91bmRlZCBkZXB0aCBmbG9vci4KICAgIHYyMjJDZWxsSGFuZG9mZlNlY29u
ZHMgPSA1LjAwLAogICAgdjIyMkNlbGxIYW5kb2ZmRnVsbFNlY29uZHMgPSAxLjM1LAogICAgdjIy
MkNlbGxIYW5kb2ZmRmxvb3IgPSA0MjAwLjAsCiAgICB2MjIyQ2VsbEhhbmRvZmZIb3BzID0gMiwK
ICAgIHYyMjJDZWxsSGFuZG9mZk1heFNlY3RvcnMgPSAxMiwKICAgIHYyMjJDZWxsSGFuZG9mZlJh
ZGl1cyA9IDE3MDAuMCwKCiAgICAtLSBDb25zZXJ2YXRpdmUgc3RhdGljLW9iamVjdC9zZWN0b3Ig
b3ZlcmxhcCBtYXJnaW5zIGluIHRoZSBDKysgUFZTLgoiIiIKcmVwKG9sZCxuZXcsJ3BvbGljeScp
CgojIHJlc2V0UnVudGltZSBmaWVsZHMKb2xkPSIiIiAgICBtYXBTdGF0ZS51cFB1bGxiYWNrcyA9
IDAKICAgIG1hcFN0YXRlLnVwRmxvb3JBcHBsaWNhdGlvbnMgPSAwCiAgICBncmlkTWF5YmVBcm1l
ZCA9IHRydWUgICAtLSBlbmdpbmUgZ3JpZCBzdGF0ZSB1bmtub3duIGFmdGVyIGFueSAocmUpbG9h
ZDoKIiIiCm5ldz0iIiIgICAgbWFwU3RhdGUudXBQdWxsYmFja3MgPSAwCiAgICBtYXBTdGF0ZS51
cEZsb29yQXBwbGljYXRpb25zID0gMAogICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZTZWN0b3JzID0g
e30KICAgIG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQgPSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFu
ZG9mZlVudGlsID0gMC4wCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkZ1bGxVbnRpbCA9IDAuMAog
ICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZEb29yU2VjdG9yID0gMAogICAgbWFwU3RhdGUuY2VsbEhh
bmRvZmZFdmVudHMgPSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkRvb3JNYXRjaGVzID0gMAog
ICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZGYWxsYmFja3MgPSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFu
ZG9mZkdyaWRGbG9vcnMgPSAwCiAgICBtYXBTdGF0ZS5sb2FkU2FmZUxhc3RDZWxsID0gbmlsCiAg
ICBtYXBTdGF0ZS5sb2FkU2FmZVRyYW5zaXRpb25Gcm9tID0gbmlsCiAgICBncmlkTWF5YmVBcm1l
ZCA9IHRydWUgICAtLSBlbmdpbmUgZ3JpZCBzdGF0ZSB1bmtub3duIGFmdGVyIGFueSAocmUpbG9h
ZDoKIiIiCnJlcChvbGQsbmV3LCdydW50aW1lIHJlc2V0JykKCiMgSW5zZXJ0IGNlbGwgaGFuZG9m
ZiBoZWxwZXJzIGFmdGVyIG9wZW5QdnNEZXN0aW5hdGlvbgphbmNob3I9IiIibWFwU3RhdGUub3Bl
blB2c0Rlc3RpbmF0aW9uID0gZnVuY3Rpb24ob3RoZXIsIGlkeCwgbGFyZ2VUYXJnZXQsIGRpc3Qs
IGdyYWNlLCBzb3VyY2UpCiAgICBpZiBvdGhlciA9PSBuaWwgb3Igb3RoZXIgPD0gMCBvciBvdGhl
ciA9PSBtYXBTdGF0ZS50b3BvU2VjdG9ySWQgdGhlbiByZXR1cm4gZmFsc2UgZW5kCiAgICBsb2Nh
bCBleHBpcnkgPSBpbnRlcmlvckVsYXBzZWQgKyBncmFjZQogICAgbG9jYWwgcmVzaWRlbnREZXB0
aCA9IG1pbihPUEVOX0RFUFRILCAoZGlzdCBvciAwLjApICsgbWFwU3RhdGUudjIyUG9ydGFsRGVw
dGhQYWQpCiAgICBtYXBTdGF0ZS5yZXNpZGVudFByb21vdGUoCiAgICAgICAgb3RoZXIsIHNvdXJj
ZSA9PSAncmF5JyBhbmQgJ3JheScgb3IgKHNvdXJjZSBvciAncHJlZGljdCcpLAogICAgICAgIGlk
eCwgcmVzaWRlbnREZXB0aCwgbWFwU3RhdGUudjIyUmVzaWRlbnRNaW5Ib2xkKQogICAgbWFwU3Rh
dGUucHZzUmVtZW1iZXJTZWN0b3Iob3RoZXIsIGdyYWNlKQogICAgbWFwU3RhdGUucHZzUG9ydGFs
U2VjdG9yID0gb3RoZXIKICAgIG1hcFN0YXRlLnB2c1BvcnRhbFVudGlsID0gbWF4KG1hcFN0YXRl
LnB2c1BvcnRhbFVudGlsIG9yIDAuMCwgZXhwaXJ5KQogICAgbWFwU3RhdGUub3BlblBvcnRhbFdl
ZGdlKGlkeCwgbGFyZ2VUYXJnZXQsIGRpc3QsIGV4cGlyeSwKICAgICAgICBzb3VyY2UgPT0gJ3Jh
eScgYW5kIDE1IG9yIDEzKQogICAgZW50ZXJCdXJzdCA9IG1heChlbnRlckJ1cnN0LCBtYXBTdGF0
ZS52MThQb3J0YWxCdXJzdCkKICAgIHR1cm5MaW5nZXIgPSBtYXgodHVybkxpbmdlciwgbGFyZ2VU
YXJnZXQgYW5kIDEuMDUgb3IgMC44MCkKICAgIG1hcFN0YXRlLnVwZGF0ZVRvcG9sb2d5UHZzKGZh
bHNlKQogICAgcmV0dXJuIHRydWUKZW5kCgoiIiIKaGVscGVyPXInJyctLSA9PT09PT09PSBWMjIu
MjogaW50ZXJpb3ItPmludGVyaW9yIGRlc3RpbmF0aW9uIGhhbmRvZmYgPT09PT09PT0KLS0gU2Vj
dG9yIGlkcyBhcmUgb25seSBtZWFuaW5nZnVsIGluc2lkZSBvbmUgY2VsbC4gT24gYSBsb2FkIGRv
b3IgdHJhbnNpdGlvbiwKLS0gdGhyb3cgYXdheSBhbGwgc291cmNlLWNlbGwgUFZTL2xhdGNoIHN0
YXRlIGFuZCBidWlsZCBhIGZyZXNoIGRlc3RpbmF0aW9uLXNpZGUKLS0gYXJyaXZhbCBidWJibGUu
IFRoZSByZXZlcnNlIEVTTSBkb29yIGJhY2sgdG8gdGhlIHNvdXJjZSBpcyB0aGUgcHJlZmVycmVk
IHNlZWQ7Ci0tIGN1cnJlbnQtc2VjdG9yICsgbG9jYWwtcmFkaXVzIHRvcG9sb2d5IGFyZSBjb25z
ZXJ2YXRpdmUgZmFsbGJhY2tzLgptYXBTdGF0ZS5jbGVhckNyb3NzQ2VsbFZpc2liaWxpdHlTdGF0
ZSA9IGZ1bmN0aW9uKCkKICAgIG1hcFN0YXRlLnB2c1JlY2VudCA9IHt9CiAgICBtYXBTdGF0ZS5w
dnNSZWNlbnRBY3RpdmUgPSAwCiAgICBtYXBTdGF0ZS5wdnNQb3J0YWxTZWN0b3IgPSAwCiAgICBt
YXBTdGF0ZS5wdnNQb3J0YWxVbnRpbCA9IDAuMAogICAgbWFwU3RhdGUucG9ydGFsTGF0Y2hlcyA9
IHt9CiAgICBtYXBTdGF0ZS5wb3J0YWxMYXRjaENvdW50ID0gMAogICAgbWFwU3RhdGUucG9ydGFs
TGF0Y2hUb3VjaGVzID0gMAogICAgbWFwU3RhdGUudHJhbnNpdGlvbk9wZW5VbnRpbCA9IDAuMAog
ICAgbWFwU3RhdGUudHJhbnNpdGlvbk9sZCA9IDAKICAgIG1hcFN0YXRlLnRyYW5zaXRpb25OZXcg
PSAwCiAgICBtYXBTdGF0ZS5kb29yUHJvdGVjdERlcHRoID0ge30KICAgIG1hcFN0YXRlLmRvb3JQ
cm90ZWN0VW50aWwgPSB7fQogICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZTZWN0b3JzID0ge30KICAg
IG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQgPSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZlVu
dGlsID0gMC4wCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkZ1bGxVbnRpbCA9IDAuMAogICAgbWFw
U3RhdGUuY2VsbEhhbmRvZmZEb29yU2VjdG9yID0gMAplbmQKCm1hcFN0YXRlLmJlZ2luQ2VsbEhh
bmRvZmYgPSBmdW5jdGlvbihmcm9tQ2VsbCwgdG9DZWxsLCBleCwgZXksIGV6KQogICAgbWFwU3Rh
dGUuY2VsbEhhbmRvZmZTZWN0b3JzID0ge30KICAgIG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQg
PSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZlVudGlsID0gMC4wCiAgICBtYXBTdGF0ZS5jZWxs
SGFuZG9mZkZ1bGxVbnRpbCA9IDAuMAogICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZEb29yU2VjdG9y
ID0gMAoKICAgIGlmIHR5cGUoZnJvbUNlbGwpIH49ICdzdHJpbmcnIG9yIGZyb21DZWxsID09ICcn
CiAgICAgICAgb3IgdHlwZSh0b0NlbGwpIH49ICdzdHJpbmcnIG9yIHRvQ2VsbCA9PSAnJwogICAg
ICAgIG9yIHN0cmluZy5sb3dlcihmcm9tQ2VsbCkgPT0gc3RyaW5nLmxvd2VyKHRvQ2VsbCkgdGhl
bgogICAgICAgIHJldHVybiBmYWxzZQogICAgZW5kCgogICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZF
dmVudHMgPSAobWFwU3RhdGUuY2VsbEhhbmRvZmZFdmVudHMgb3IgMCkgKyAxCiAgICBtYXBTdGF0
ZS5jZWxsSGFuZG9mZlVudGlsID0gaW50ZXJpb3JFbGFwc2VkICsgbWFwU3RhdGUudjIyMkNlbGxI
YW5kb2ZmU2Vjb25kcwogICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZGdWxsVW50aWwKICAgICAgICA9
IGludGVyaW9yRWxhcHNlZCArIG1hcFN0YXRlLnYyMjJDZWxsSGFuZG9mZkZ1bGxTZWNvbmRzCiAg
ICBlbnRlckJ1cnN0ID0gbWF4KGVudGVyQnVyc3QsIG1hcFN0YXRlLnYxOFBvcnRhbEJ1cnN0KQog
ICAgdHVybkxpbmdlciA9IG1heCh0dXJuTGluZ2VyLCAxLjAwKQoKICAgIGxvY2FsIHRjID0gbWFw
U3RhdGUudG9wb0NlbGwKICAgIGlmIHRjID09IG5pbCBvciB0Yy5zZWN0b3JzID09IG5pbCB0aGVu
CiAgICAgICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZGYWxsYmFja3MgPSAobWFwU3RhdGUuY2VsbEhh
bmRvZmZGYWxsYmFja3Mgb3IgMCkgKyAxCiAgICAgICAgcHJpbnQoc3RyaW5nLmZvcm1hdCgKICAg
ICAgICAgICAgJ1tUU1BfVklTR1JJRF9WMjIuMl0gaW50ZXJjZWxsIGhhbmRvZmYgJXMgLT4gJXMg
dG9wbz11bm1hcHBlZCBncmlkLWZsb29yLW9ubHkgdHRsPSUuMWYnLAogICAgICAgICAgICB0b3N0
cmluZyhmcm9tQ2VsbCksIHRvc3RyaW5nKHRvQ2VsbCksIG1hcFN0YXRlLnYyMjJDZWxsSGFuZG9m
ZlNlY29uZHMpKQogICAgICAgIHJldHVybiB0cnVlCiAgICBlbmQKCiAgICBsb2NhbCBzZWxlY3Rl
ZCA9IHt9CiAgICBsb2NhbCBxdWV1ZSA9IHt9CiAgICBsb2NhbCBxZGVwdGggPSB7fQogICAgbG9j
YWwgZnVuY3Rpb24gcHVzaChzaWQsIGRlcHRoKQogICAgICAgIGlmIHR5cGUoc2lkKSB+PSAnbnVt
YmVyJyBvciBzaWQgPD0gMCBvciB0Yy5zZWN0b3JzW3NpZF0gPT0gbmlsCiAgICAgICAgICAgIG9y
IHNlbGVjdGVkW3NpZF0gdGhlbiByZXR1cm4gZmFsc2UgZW5kCiAgICAgICAgaWYgbWFwU3RhdGUu
Y2VsbEhhbmRvZmZDb3VudCA+PSBtYXBTdGF0ZS52MjIyQ2VsbEhhbmRvZmZNYXhTZWN0b3JzIHRo
ZW4KICAgICAgICAgICAgcmV0dXJuIGZhbHNlCiAgICAgICAgZW5kCiAgICAgICAgc2VsZWN0ZWRb
c2lkXSA9IHRydWUKICAgICAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZlNlY3RvcnNbc2lkXSA9IHRy
dWUKICAgICAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkNvdW50ID0gbWFwU3RhdGUuY2VsbEhhbmRv
ZmZDb3VudCArIDEKICAgICAgICBxdWV1ZVsjcXVldWUgKyAxXSA9IHNpZAogICAgICAgIHFkZXB0
aFsjcWRlcHRoICsgMV0gPSBkZXB0aCBvciAwCiAgICAgICAgcmV0dXJuIHRydWUKICAgIGVuZAoK
ICAgIHB1c2gobWFwU3RhdGUudG9wb1NlY3RvcklkIG9yIDAsIDApCgogICAgLS0gUHJlZmVyIHRo
ZSB0ZWxlcG9ydCBkb29yIGluIHRoZSBkZXN0aW5hdGlvbiB0aGF0IHBvaW50cyBiYWNrIHRvIHRo
ZSBjZWxsCiAgICAtLSB3ZSBqdXN0IGxlZnQuIElmIHRoZXJlIGFyZSBzZXZlcmFsLCBjaG9vc2Ug
dGhlIG9uZSBuZWFyZXN0IHRoZSBhcnJpdmFsIGV5ZS4KICAgIGxvY2FsIGJlc3REb29yLCBiZXN0
RDIgPSBuaWwsIG5pbAogICAgaWYgdHlwZShtYXBTdGF0ZS5yZWFsRG9vcnMpID09ICd0YWJsZScg
dGhlbgogICAgICAgIGZvciBpID0gMSwgI21hcFN0YXRlLnJlYWxEb29ycyBkbwogICAgICAgICAg
ICBsb2NhbCBkID0gbWFwU3RhdGUucmVhbERvb3JzW2ldCiAgICAgICAgICAgIGlmIGQgfj0gbmls
IGFuZCBkLnRlbGVwb3J0ID09IHRydWUgYW5kIGQuZGVzdEtpbmQgPT0gJ2ludGVyaW9yJwogICAg
ICAgICAgICAgICAgYW5kIHR5cGUoZC5kZXN0Q2VsbCkgPT0gJ3N0cmluZycKICAgICAgICAgICAg
ICAgIGFuZCBzdHJpbmcubG93ZXIoZC5kZXN0Q2VsbCkgPT0gc3RyaW5nLmxvd2VyKGZyb21DZWxs
KQogICAgICAgICAgICAgICAgYW5kIHR5cGUoZC5zb3VyY2VTZWN0b3IpID09ICdudW1iZXInIGFu
ZCBkLnNvdXJjZVNlY3RvciA+IDAKICAgICAgICAgICAgICAgIGFuZCB0eXBlKGQueCkgPT0gJ251
bWJlcicgYW5kIHR5cGUoZC55KSA9PSAnbnVtYmVyJwogICAgICAgICAgICAgICAgYW5kIHR5cGUo
ZC56KSA9PSAnbnVtYmVyJyB0aGVuCiAgICAgICAgICAgICAgICBsb2NhbCBkeCwgZHksIGR6ID0g
ZC54IC0gZXgsIGQueSAtIGV5LCBkLnogLSBlegogICAgICAgICAgICAgICAgbG9jYWwgZDIgPSBk
eCpkeCArIGR5KmR5ICsgZHoqZHoKICAgICAgICAgICAgICAgIGlmIGJlc3REMiA9PSBuaWwgb3Ig
ZDIgPCBiZXN0RDIgdGhlbgogICAgICAgICAgICAgICAgICAgIGJlc3REb29yLCBiZXN0RDIgPSBk
LCBkMgogICAgICAgICAgICAgICAgZW5kCiAgICAgICAgICAgIGVuZAogICAgICAgIGVuZAogICAg
ZW5kCgogICAgaWYgYmVzdERvb3Igfj0gbmlsIHRoZW4KICAgICAgICBtYXBTdGF0ZS5jZWxsSGFu
ZG9mZkRvb3JNYXRjaGVzCiAgICAgICAgICAgID0gKG1hcFN0YXRlLmNlbGxIYW5kb2ZmRG9vck1h
dGNoZXMgb3IgMCkgKyAxCiAgICAgICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZEb29yU2VjdG9yID0g
YmVzdERvb3Iuc291cmNlU2VjdG9yIG9yIDAKICAgICAgICBwdXNoKG1hcFN0YXRlLmNlbGxIYW5k
b2ZmRG9vclNlY3RvciwgMCkKCiAgICAgICAgbG9jYWwgZHgsIGR5LCBkeiA9IGJlc3REb29yLngg
LSBleCwgYmVzdERvb3IueSAtIGV5LCBiZXN0RG9vci56IC0gZXoKICAgICAgICBsb2NhbCBkaXN0
ID0gc3FydChkeCpkeCArIGR5KmR5ICsgZHoqZHopCiAgICAgICAgaWYgZGlzdCA+IDEuMCB0aGVu
CiAgICAgICAgICAgIGxvY2FsIGlkeCA9IGJpbk9mRGlyKGR4LCBkeSwgZHosIGRpc3QpCiAgICAg
ICAgICAgIG1hcFN0YXRlLm9wZW5Qb3J0YWxXZWRnZSgKICAgICAgICAgICAgICAgIGlkeCwgZmFs
c2UsIGRpc3QsIG1hcFN0YXRlLmNlbGxIYW5kb2ZmVW50aWwsIDE1KQogICAgICAgIGVuZAogICAg
ZWxzZQogICAgICAgIG1hcFN0YXRlLmNlbGxIYW5kb2ZmRmFsbGJhY2tzID0gKG1hcFN0YXRlLmNl
bGxIYW5kb2ZmRmFsbGJhY2tzIG9yIDApICsgMQogICAgZW5kCgogICAgLS0gVHdvLWhvcCBncmFw
aCBidWJibGUuIFVubGlrZSBvcmRpbmFyeSBwdnNBZGRFbnZlbG9wZSwgbG9hZCBoYW5kb2ZmIGNy
b3NzZXMKICAgIC0tIGRvb3ItY2xhc3NpZmllZCBib3VuZGFyaWVzIGRlbGliZXJhdGVseTogdGhl
IHdob2xlIHBvaW50IGlzIHRvIG1ha2UgdGhlCiAgICAtLSBpbW1lZGlhdGUgZGVzdGluYXRpb24g
YXJvdW5kIGEgbG9hZCBkb29yIGRyYXdhYmxlIGJlZm9yZSBmcmVzaCByYXlzIHNldHRsZS4KICAg
IGxvY2FsIHFpID0gMQogICAgd2hpbGUgcWkgPD0gI3F1ZXVlIGFuZCBtYXBTdGF0ZS5jZWxsSGFu
ZG9mZkNvdW50IDwgbWFwU3RhdGUudjIyMkNlbGxIYW5kb2ZmTWF4U2VjdG9ycyBkbwogICAgICAg
IGxvY2FsIHNpZCA9IHF1ZXVlW3FpXQogICAgICAgIGxvY2FsIGRlcHRoID0gcWRlcHRoW3FpXSBv
ciAwCiAgICAgICAgcWkgPSBxaSArIDEKICAgICAgICBpZiBkZXB0aCA8IG1hcFN0YXRlLnYyMjJD
ZWxsSGFuZG9mZkhvcHMgdGhlbgogICAgICAgICAgICBsb2NhbCBzZWMgPSB0Yy5zZWN0b3JzW3Np
ZF0KICAgICAgICAgICAgaWYgc2VjIH49IG5pbCBhbmQgc2VjLm5laWdoYm9ycyB+PSBuaWwgdGhl
bgogICAgICAgICAgICAgICAgZm9yIGkgPSAxLCAjc2VjLm5laWdoYm9ycyBkbwogICAgICAgICAg
ICAgICAgICAgIHB1c2goc2VjLm5laWdoYm9yc1tpXSwgZGVwdGggKyAxKQogICAgICAgICAgICAg
ICAgICAgIGlmIG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQgPj0gbWFwU3RhdGUudjIyMkNlbGxI
YW5kb2ZmTWF4U2VjdG9ycyB0aGVuCiAgICAgICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAg
ICAgICAgICAgICAgICAgZW5kCiAgICAgICAgICAgICAgICBlbmQKICAgICAgICAgICAgZW5kCiAg
ICAgICAgZW5kCiAgICBlbmQKCiAgICAtLSBTcGF0aWFsIGZhbGxiYWNrIGNhdGNoZXMgZGlzY29u
bmVjdGVkIG5hdm1lc2ggaXNsYW5kcyAvIGltcGVyZmVjdCBwb3J0YWwKICAgIC0tIHJlY29uc3Ry
dWN0aW9uIGFyb3VuZCB0aGUgYWN0dWFsIGFycml2YWwgcG9pbnQsIHN0aWxsIGJvdW5kZWQgdG8g
MTIgc2VjdG9ycy4KICAgIGlmIG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQgPCBtYXBTdGF0ZS52
MjIyQ2VsbEhhbmRvZmZNYXhTZWN0b3JzIHRoZW4KICAgICAgICBsb2NhbCBweCwgcHksIHB6ID0g
bWFwU3RhdGUudG9wb1ggb3IgZXgsIG1hcFN0YXRlLnRvcG9ZIG9yIGV5LCBtYXBTdGF0ZS50b3Bv
WiBvciBlegogICAgICAgIGxvY2FsIHIyID0gbWFwU3RhdGUudjIyMkNlbGxIYW5kb2ZmUmFkaXVz
ICogbWFwU3RhdGUudjIyMkNlbGxIYW5kb2ZmUmFkaXVzCiAgICAgICAgZm9yIHNpZCwgc2VjIGlu
IHBhaXJzKHRjLnNlY3RvcnMpIGRvCiAgICAgICAgICAgIGlmIG5vdCBzZWxlY3RlZFtzaWRdIGFu
ZCBzZWMgfj0gbmlsIGFuZCBzZWMuYmJveCB+PSBuaWwKICAgICAgICAgICAgICAgIGFuZCAjc2Vj
LmJib3ggPj0gNiB0aGVuCiAgICAgICAgICAgICAgICBsb2NhbCBiID0gc2VjLmJib3gKICAgICAg
ICAgICAgICAgIGxvY2FsIHF4ID0gbWF4KGJbMV0sIG1pbihweCwgYls0XSkpCiAgICAgICAgICAg
ICAgICBsb2NhbCBxeSA9IG1heChiWzJdLCBtaW4ocHksIGJbNV0pKQogICAgICAgICAgICAgICAg
bG9jYWwgcXogPSBtYXgoYlszXSwgbWluKHB6LCBiWzZdKSkKICAgICAgICAgICAgICAgIGxvY2Fs
IGR4LCBkeSwgZHogPSBweCAtIHF4LCBweSAtIHF5LCBweiAtIHF6CiAgICAgICAgICAgICAgICBp
ZiBkeCpkeCArIGR5KmR5ICsgZHoqZHogPD0gcjIgdGhlbgogICAgICAgICAgICAgICAgICAgIHB1
c2goc2lkLCBtYXBTdGF0ZS52MjIyQ2VsbEhhbmRvZmZIb3BzKQogICAgICAgICAgICAgICAgICAg
IGlmIG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQgPj0gbWFwU3RhdGUudjIyMkNlbGxIYW5kb2Zm
TWF4U2VjdG9ycyB0aGVuCiAgICAgICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgICAg
ICAgICAgICAgZW5kCiAgICAgICAgICAgICAgICBlbmQKICAgICAgICAgICAgZW5kCiAgICAgICAg
ZW5kCiAgICBlbmQKCiAgICBwcmludChzdHJpbmcuZm9ybWF0KAogICAgICAgICdbVFNQX1ZJU0dS
SURfVjIyLjJdIGludGVyY2VsbCBoYW5kb2ZmICVzIC0+ICVzIGN1cnJlbnQ9JWQgcmV2ZXJzZURv
b3JTZWN0b3I9JWQgc2VjdG9ycz0lZCB0dGw9JS4xZicsCiAgICAgICAgdG9zdHJpbmcoZnJvbUNl
bGwpLCB0b3N0cmluZyh0b0NlbGwpLCBtYXBTdGF0ZS50b3BvU2VjdG9ySWQgb3IgMCwKICAgICAg
ICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkRvb3JTZWN0b3Igb3IgMCwgbWFwU3RhdGUuY2VsbEhhbmRv
ZmZDb3VudCBvciAwLAogICAgICAgIG1hcFN0YXRlLnYyMjJDZWxsSGFuZG9mZlNlY29uZHMpKQog
ICAgcmV0dXJuIHRydWUKZW5kCgptYXBTdGF0ZS5jZWxsSGFuZG9mZkRlcHRoRmxvb3IgPSBmdW5j
dGlvbigpCiAgICBpZiAobWFwU3RhdGUuY2VsbEhhbmRvZmZVbnRpbCBvciAwLjApIDw9IGludGVy
aW9yRWxhcHNlZCB0aGVuIHJldHVybiBuaWwgZW5kCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkdy
aWRGbG9vcnMgPSAobWFwU3RhdGUuY2VsbEhhbmRvZmZHcmlkRmxvb3JzIG9yIDApICsgMQogICAg
aWYgbWFwU3RhdGUudG9wb0NlbGwgfj0gbmlsCiAgICAgICAgYW5kIChtYXBTdGF0ZS5jZWxsSGFu
ZG9mZkZ1bGxVbnRpbCBvciAwLjApID4gaW50ZXJpb3JFbGFwc2VkIHRoZW4KICAgICAgICByZXR1
cm4gT1BFTl9ERVBUSAogICAgZW5kCiAgICByZXR1cm4gbWFwU3RhdGUudjIyMkNlbGxIYW5kb2Zm
Rmxvb3IKZW5kCgonJycKcmVwKGFuY2hvciwgYW5jaG9yK2hlbHBlciwgJ2hhbmRvZmYgaGVscGVy
cycpCgojIHVwZGF0ZVRvcG9sb2d5UHZzOiBpbmplY3QgaGFuZG9mZiBhY3RpdmUgc2V0IGFmdGVy
IHJlc2lkZW50IHNlZWRzCm9sZD0iIiIgICAgZm9yIHNpZCwgciBpbiBwYWlycyhtYXBTdGF0ZS5y
ZXNpZGVudFNlY3RvcnMpIGRvCiAgICAgICAgaWYgciB+PSBuaWwgdGhlbiBtYXBTdGF0ZS5wdnNB
ZGRMYXRjaGVkU2VjdG9yKGFjdGl2ZSwgc2lkKSBlbmQKICAgIGVuZAoKICAgIGxvY2FsIHJlY2Vu
dE4gPSAwCiIiIgpuZXc9IiIiICAgIGZvciBzaWQsIHIgaW4gcGFpcnMobWFwU3RhdGUucmVzaWRl
bnRTZWN0b3JzKSBkbwogICAgICAgIGlmIHIgfj0gbmlsIHRoZW4gbWFwU3RhdGUucHZzQWRkTGF0
Y2hlZFNlY3RvcihhY3RpdmUsIHNpZCkgZW5kCiAgICBlbmQKCiAgICAtLSBWMjIuMiBsb2FkLWRv
b3IgaGFuZG9mZiBpcyBpbmRlcGVuZGVudCBvZiB0aGUgbm9ybWFsIDMtcm9vbSByZXNpZGVudAog
ICAgLS0gYnVkZ2V0LiBJdCBpcyBhIHNob3J0IGRlc3RpbmF0aW9uLW9ubHkgc2FmZXR5IGJ1YmJs
ZSBhbmQgZXhwaXJlcyBhcyBhIHVuaXQuCiAgICBpZiAobWFwU3RhdGUuY2VsbEhhbmRvZmZVbnRp
bCBvciAwLjApID4gaW50ZXJpb3JFbGFwc2VkIHRoZW4KICAgICAgICBmb3Igc2lkLCBrZWVwIGlu
IHBhaXJzKG1hcFN0YXRlLmNlbGxIYW5kb2ZmU2VjdG9ycykgZG8KICAgICAgICAgICAgaWYga2Vl
cCB0aGVuIG1hcFN0YXRlLnB2c0FkZExhdGNoZWRTZWN0b3IoYWN0aXZlLCBzaWQpIGVuZAogICAg
ICAgIGVuZAogICAgZWxzZWlmIG1hcFN0YXRlLmNlbGxIYW5kb2ZmQ291bnQgPiAwIHRoZW4KICAg
ICAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZlNlY3RvcnMgPSB7fQogICAgICAgIG1hcFN0YXRlLmNl
bGxIYW5kb2ZmQ291bnQgPSAwCiAgICAgICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZEb29yU2VjdG9y
ID0gMAogICAgZW5kCgogICAgbG9jYWwgcmVjZW50TiA9IDAKIiIiCnJlcChvbGQsbmV3LCdQVlMg
aGFuZG9mZiBzZXQnKQoKIyBQdWJsaXNoIGZsb29yIGFmdGVyIHJlc2lkZW50IGF1dGhvcml0eSwg
YmVmb3JlIHRvcG9sb2d5IGZpbmFsIGJyYW5jaApvbGQ9IiIiICAgICAgICAgICAgICAgICAgICBs
b2NhbCByZXNpZGVudERlcHRoID0gbWFwU3RhdGUucmVzaWRlbnREZXB0aEZvckJpbihpZHgpCiAg
ICAgICAgICAgICAgICAgICAgaWYgcmVzaWRlbnREZXB0aCB+PSBuaWwgYW5kIHJlc2lkZW50RGVw
dGggPiBkZXB0aCB0aGVuCiAgICAgICAgICAgICAgICAgICAgICAgIGRlcHRoID0gcmVzaWRlbnRE
ZXB0aAogICAgICAgICAgICAgICAgICAgIGVuZAogICAgICAgICAgICAgICAgZW5kCiAgICAgICAg
ICAgIGVuZAogICAgICAgICAgICAtLSBWMTUgY29udHJhY3Q6IHRvcG9sb2d5LW1hcHBlZCBjZWxs
cyBuZXZlciBoYXJkLWNsYW1wIGxpdmUgcmF5IGRlcHRoLgoiIiIKbmV3PSIiIiAgICAgICAgICAg
ICAgICAgICAgbG9jYWwgcmVzaWRlbnREZXB0aCA9IG1hcFN0YXRlLnJlc2lkZW50RGVwdGhGb3JC
aW4oaWR4KQogICAgICAgICAgICAgICAgICAgIGlmIHJlc2lkZW50RGVwdGggfj0gbmlsIGFuZCBy
ZXNpZGVudERlcHRoID4gZGVwdGggdGhlbgogICAgICAgICAgICAgICAgICAgICAgICBkZXB0aCA9
IHJlc2lkZW50RGVwdGgKICAgICAgICAgICAgICAgICAgICBlbmQKCiAgICAgICAgICAgICAgICAg
ICAgLS0gVjIyLjIgY3Jvc3MtY2VsbCBhcnJpdmFsIGZsb29yIGlzIGRlbGliZXJhdGVseSBsYXN0
IGFtb25nCiAgICAgICAgICAgICAgICAgICAgLS0gc2Vuc29yIGhldXJpc3RpY3MuIEZyZXNoIGNs
b3NlIHJheXMgbWF5IGxlYXJuIGltbWVkaWF0ZWx5LAogICAgICAgICAgICAgICAgICAgIC0tIGJ1
dCBjYW5ub3QgcGFpbnQgYSByZWQgaG9sZSBkdXJpbmcgdGhlIGZpdmUtc2Vjb25kIGhhbmRvZmYu
CiAgICAgICAgICAgICAgICAgICAgbG9jYWwgaGFuZG9mZkRlcHRoID0gbWFwU3RhdGUuY2VsbEhh
bmRvZmZEZXB0aEZsb29yKCkKICAgICAgICAgICAgICAgICAgICBpZiBoYW5kb2ZmRGVwdGggfj0g
bmlsIGFuZCBoYW5kb2ZmRGVwdGggPiBkZXB0aCB0aGVuCiAgICAgICAgICAgICAgICAgICAgICAg
IGRlcHRoID0gaGFuZG9mZkRlcHRoCiAgICAgICAgICAgICAgICAgICAgZW5kCiAgICAgICAgICAg
ICAgICBlbmQKICAgICAgICAgICAgZW5kCiAgICAgICAgICAgIC0tIFYxNSBjb250cmFjdDogdG9w
b2xvZ3ktbWFwcGVkIGNlbGxzIG5ldmVyIGhhcmQtY2xhbXAgbGl2ZSByYXkgZGVwdGguCiIiIgpy
ZXAob2xkLG5ldywncHVibGlzaCBoYW5kb2ZmIGZsb29yJykKCiMgZW50ZXJJbnRlcmlvciBzaWdu
YXR1cmUgYW5kIGNsZWFyL3ByZXNlcnZlIGhhbmRvZmYKcmVwKAoibG9jYWwgZnVuY3Rpb24gZW50
ZXJJbnRlcmlvcihjZWxsTmFtZSwgZXgsIGV5LCBleilcbiIsCiJsb2NhbCBmdW5jdGlvbiBlbnRl
ckludGVyaW9yKGNlbGxOYW1lLCBleCwgZXksIGV6LCBoYW5kb2ZmRnJvbUNlbGwpXG4iLAonZW50
ZXIgc2lnbmF0dXJlJykKCiMgY2xlYXIgc291cmNlIGxvY2FsIHN0YXRlIGFmdGVyIGNhY2hlIHNh
dmUgYW5kIGJlZm9yZSB0b3BvQ2VsbCBuZXcgYXNzaWdubWVudApvbGQ9IiIiICAgIGlmIGluSW50
ZXJpb3IgYW5kIGxhc3RDZWxsTmFtZSB+PSBuaWwgYW5kIGxhc3RFeCB+PSBuaWwgdGhlbgogICAg
ICAgIGNhY2hlU2F2ZShsYXN0Q2VsbE5hbWUsIGxhc3RFeCwgbGFzdEV5LCBsYXN0RXopCiAgICBl
bmQKICAgIC0tIFYxNTogZGV0ZXJtaW5lIHdoZXRoZXIgdGhpcyBjZWxsIGhhcyBhIHJlYWwgbmF2
bWVzaCB0b3BvbG9neSBlbnRyeS4KIiIiCm5ldz0iIiIgICAgaWYgaW5JbnRlcmlvciBhbmQgbGFz
dENlbGxOYW1lIH49IG5pbCBhbmQgbGFzdEV4IH49IG5pbCB0aGVuCiAgICAgICAgY2FjaGVTYXZl
KGxhc3RDZWxsTmFtZSwgbGFzdEV4LCBsYXN0RXksIGxhc3RFeikKICAgIGVuZAogICAgaWYgdHlw
ZShoYW5kb2ZmRnJvbUNlbGwpID09ICdzdHJpbmcnIGFuZCBoYW5kb2ZmRnJvbUNlbGwgfj0gJycK
ICAgICAgICBhbmQgc3RyaW5nLmxvd2VyKGhhbmRvZmZGcm9tQ2VsbCkgfj0gc3RyaW5nLmxvd2Vy
KGNlbGxOYW1lKSB0aGVuCiAgICAgICAgbWFwU3RhdGUuY2xlYXJDcm9zc0NlbGxWaXNpYmlsaXR5
U3RhdGUoKQogICAgZW5kCiAgICAtLSBWMTU6IGRldGVybWluZSB3aGV0aGVyIHRoaXMgY2VsbCBo
YXMgYSByZWFsIG5hdm1lc2ggdG9wb2xvZ3kgZW50cnkuCiIiIgpyZXAob2xkLG5ldywnZW50ZXIg
Y3Jvc3MgY2xlYXInKQoKIyBEb24ndCB3aXBlIGhhbmRvZmYgYWN0aXZlIGZpZWxkcyBpbiBnZW5l
cmljIGVudGVyIHJlc2V0OyBzZXQgYWN0aXZlIGZpZWxkcyBleHBsaWNpdGx5IGJlZm9yZSByZXNl
dCBwYW5vcmFtYQpvbGQ9IiIiICAgIG1hcFN0YXRlLnVwQmxvY2tlZFVudGlsID0gMC4wCiAgICBt
YXBTdGF0ZS51cENsb3NlUnVuID0gMAogICAgbWFwU3RhdGUudXBPcGVuUnVuID0gMAogICAgcmVz
ZXRQYW5vcmFtYSgpCiIiIgpuZXc9IiIiICAgIG1hcFN0YXRlLnVwQmxvY2tlZFVudGlsID0gMC4w
CiAgICBtYXBTdGF0ZS51cENsb3NlUnVuID0gMAogICAgbWFwU3RhdGUudXBPcGVuUnVuID0gMAog
ICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZTZWN0b3JzID0ge30KICAgIG1hcFN0YXRlLmNlbGxIYW5k
b2ZmQ291bnQgPSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZlVudGlsID0gMC4wCiAgICBtYXBT
dGF0ZS5jZWxsSGFuZG9mZkZ1bGxVbnRpbCA9IDAuMAogICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZE
b29yU2VjdG9yID0gMAogICAgcmVzZXRQYW5vcmFtYSgpCiIiIgpyZXAob2xkLG5ldywnZW50ZXIg
YWN0aXZlIHJlc2V0JykKCiMgU3RhcnQgaGFuZG9mZiBhZnRlciByZWFsIGRvb3JzIGxvYWRlZCBh
bmQgYm94ZXMgYnVpbHQsIGJlZm9yZSBQVlMgdXBkYXRlCm9sZD0iIiIgICAgbWFwU3RhdGUubG9h
ZFJlYWxEb29ycyhjZWxsTmFtZSkKICAgIG1hcFN0YXRlLmJ1aWxkUHZzQm94ZXMoKQogICAgbWFw
U3RhdGUudXBkYXRlVG9wb2xvZ3lQdnModHJ1ZSkKICAgIGNhY2hlUmVzdG9yZShjZWxsTmFtZSwg
ZXgsIGV5LCBleikKIiIiCm5ldz0iIiIgICAgbWFwU3RhdGUubG9hZFJlYWxEb29ycyhjZWxsTmFt
ZSkKICAgIG1hcFN0YXRlLmJ1aWxkUHZzQm94ZXMoKQogICAgbWFwU3RhdGUuYmVnaW5DZWxsSGFu
ZG9mZihoYW5kb2ZmRnJvbUNlbGwsIGNlbGxOYW1lLCBleCwgZXksIGV6KQogICAgbWFwU3RhdGUu
dXBkYXRlVG9wb2xvZ3lQdnModHJ1ZSkKICAgIGNhY2hlUmVzdG9yZShjZWxsTmFtZSwgZXgsIGV5
LCBleikKIiIiCnJlcChvbGQsbmV3LCdiZWdpbiBoYW5kb2ZmIGluIGVudGVyJykKCiMgZXhpdCBj
bGVhciBoYW5kb2ZmCm9sZD0iIiIgICAgbWFwU3RhdGUucmVzaWRlbnRTZWN0b3JzID0ge30KICAg
IG1hcFN0YXRlLnJlc2lkZW50Q291bnQgPSAwCiAgICByZXN0b3JlVmlld0Rpc3RhbmNlKCkKIiIi
Cm5ldz0iIiIgICAgbWFwU3RhdGUucmVzaWRlbnRTZWN0b3JzID0ge30KICAgIG1hcFN0YXRlLnJl
c2lkZW50Q291bnQgPSAwCiAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZlNlY3RvcnMgPSB7fQogICAg
bWFwU3RhdGUuY2VsbEhhbmRvZmZDb3VudCA9IDAKICAgIG1hcFN0YXRlLmNlbGxIYW5kb2ZmVW50
aWwgPSAwLjAKICAgIG1hcFN0YXRlLmNlbGxIYW5kb2ZmRnVsbFVudGlsID0gMC4wCiAgICBtYXBT
dGF0ZS5jZWxsSGFuZG9mZkRvb3JTZWN0b3IgPSAwCiAgICBtYXBTdGF0ZS5sb2FkU2FmZUxhc3RD
ZWxsID0gbmlsCiAgICBtYXBTdGF0ZS5sb2FkU2FmZVRyYW5zaXRpb25Gcm9tID0gbmlsCiAgICBy
ZXN0b3JlVmlld0Rpc3RhbmNlKCkKIiIiCnJlcChvbGQsbmV3LCdleGl0IGNsZWFyJykKCiMgRHVy
aW5nIGdsb2JhbCBwb3N0LWxvYWQgaG9sZCwgcmVtZW1iZXIgaW50ZXJpb3IgY2VsbC10by1jZWxs
IGNoYW5nZXMgZXZlbiB0aG91Z2ggc2Vuc29yIGlzbid0IGFybWVkIHlldC4Kb2xkPSIiIiAgICAt
LSBUU1BfVklTR1JJRF9WMjBfTE9BRFNBRkVfNlMKICAgIGlmIHBvc3RMb2FkQXJtUmVtYWluaW5n
ID4gMC4wIHRoZW4KICAgICAgICBwb3N0TG9hZEFybVJlbWFpbmluZyA9IG1heCgwLjAsIHBvc3RM
b2FkQXJtUmVtYWluaW5nIC0gZHQpCiIiIgpuZXc9IiIiICAgIC0tIFRTUF9WSVNHUklEX1YyMF9M
T0FEU0FGRV82UwogICAgaWYgcG9zdExvYWRBcm1SZW1haW5pbmcgPiAwLjAgdGhlbgogICAgICAg
IC0tIFYyMi4yOiB0aGUgbG9hZC1zYWZlIGdhdGUgdXNlZCB0byByZXR1cm4gYmVmb3JlIGV2ZW4g
bm90aWNpbmcgdGhhdCB0aGUKICAgICAgICAtLSBwbGF5ZXIgY3Jvc3NlZCBhbiBpbnRlcmlvciBs
b2FkIGRvb3IuIFJlbWVtYmVyIHRoYXQgdHJhbnNpdGlvbiBzbyB0aGUKICAgICAgICAtLSBkZXN0
aW5hdGlvbiBjYW4gc3RpbGwgcmVjZWl2ZSBhIHByb3BlciBoYW5kb2ZmIHdoZW4gVklTR1JJRCBm
aW5hbGx5IGFybXMuCiAgICAgICAgbG9jYWwgaG9sZENlbGxOYW1lID0gdG9zdHJpbmcoY2VsbC5u
YW1lIG9yIGNlbGwuaWQgb3IgJz8nKQogICAgICAgIGlmIG1hcFN0YXRlLmxvYWRTYWZlTGFzdENl
bGwgfj0gbmlsCiAgICAgICAgICAgIGFuZCBob2xkQ2VsbE5hbWUgfj0gbWFwU3RhdGUubG9hZFNh
ZmVMYXN0Q2VsbCB0aGVuCiAgICAgICAgICAgIG1hcFN0YXRlLmxvYWRTYWZlVHJhbnNpdGlvbkZy
b20gPSBtYXBTdGF0ZS5sb2FkU2FmZUxhc3RDZWxsCiAgICAgICAgZW5kCiAgICAgICAgbWFwU3Rh
dGUubG9hZFNhZmVMYXN0Q2VsbCA9IGhvbGRDZWxsTmFtZQogICAgICAgIHBvc3RMb2FkQXJtUmVt
YWluaW5nID0gbWF4KDAuMCwgcG9zdExvYWRBcm1SZW1haW5pbmcgLSBkdCkKIiIiCnJlcChvbGQs
bmV3LCdsb2FkLXNhZmUgb2JzZXJ2ZScpCgojIEVudGVyIGNhbGxzIHdpdGggZnJvbSBjZWxsOyBj
b25zdW1lIGxvYWQtc2FmZSByZW1lbWJlcmVkIHNvdXJjZSBvbiBmaXJzdCBhcm0uCm9sZD0iIiIg
ICAgbG9jYWwgbW92ZURpc3QgPSAwLjAKICAgIGlmIG5vdCBpbkludGVyaW9yIHRoZW4KICAgICAg
ICBlbnRlckludGVyaW9yKGNlbGxOYW1lLCBleCwgZXksIGV6KQogICAgZWxzZWlmIGNlbGxOYW1l
IH49IGxhc3RDZWxsTmFtZSB0aGVuCiAgICAgICAgZW50ZXJJbnRlcmlvcihjZWxsTmFtZSwgZXgs
IGV5LCBleikKICAgICAgICBwcmludCgnW1RTUF9WSVNHUklEX1YxMV0gcmVzZXQgcmVhc29uPWNl
bGwtY2hhbmdlJykKIiIiCm5ldz0iIiIgICAgbG9jYWwgbW92ZURpc3QgPSAwLjAKICAgIGlmIG5v
dCBpbkludGVyaW9yIHRoZW4KICAgICAgICBsb2NhbCBoYW5kb2ZmRnJvbSA9IG1hcFN0YXRlLmxv
YWRTYWZlVHJhbnNpdGlvbkZyb20KICAgICAgICBpZiBoYW5kb2ZmRnJvbSB+PSBuaWwgYW5kIGhh
bmRvZmZGcm9tID09IGNlbGxOYW1lIHRoZW4gaGFuZG9mZkZyb20gPSBuaWwgZW5kCiAgICAgICAg
ZW50ZXJJbnRlcmlvcihjZWxsTmFtZSwgZXgsIGV5LCBleiwgaGFuZG9mZkZyb20pCiAgICAgICAg
bWFwU3RhdGUubG9hZFNhZmVUcmFuc2l0aW9uRnJvbSA9IG5pbAogICAgICAgIG1hcFN0YXRlLmxv
YWRTYWZlTGFzdENlbGwgPSBjZWxsTmFtZQogICAgZWxzZWlmIGNlbGxOYW1lIH49IGxhc3RDZWxs
TmFtZSB0aGVuCiAgICAgICAgbG9jYWwgaGFuZG9mZkZyb20gPSBsYXN0Q2VsbE5hbWUKICAgICAg
ICBlbnRlckludGVyaW9yKGNlbGxOYW1lLCBleCwgZXksIGV6LCBoYW5kb2ZmRnJvbSkKICAgICAg
ICBtYXBTdGF0ZS5sb2FkU2FmZVRyYW5zaXRpb25Gcm9tID0gbmlsCiAgICAgICAgbWFwU3RhdGUu
bG9hZFNhZmVMYXN0Q2VsbCA9IGNlbGxOYW1lCiAgICAgICAgcHJpbnQoJ1tUU1BfVklTR1JJRF9W
MTFdIHJlc2V0IHJlYXNvbj1jZWxsLWNoYW5nZScpCiIiIgpyZXAob2xkLG5ldywnZW50ZXIgY2Fs
bHMnKQoKIyBLZWVwIHNhbWUtY2VsbCB0ZWxlcG9ydCBjYWxsIGV4cGxpY2l0IG5vIGhhbmRvZmYK
cmVwKAoiICAgICAgICAgICAgZW50ZXJJbnRlcmlvcihjZWxsTmFtZSwgZXgsIGV5LCBleilcbiAg
ICAgICAgICAgIHByaW50KCdbVFNQX1ZJU0dSSURfVjExXSByZXNldCByZWFzb249dGVsZXBvcnQn
KVxuIiwKIiAgICAgICAgICAgIGVudGVySW50ZXJpb3IoY2VsbE5hbWUsIGV4LCBleSwgZXosIG5p
bClcbiAgICAgICAgICAgIHByaW50KCdbVFNQX1ZJU0dSSURfVjExXSByZXNldCByZWFzb249dGVs
ZXBvcnQnKVxuIiwKJ3RlbGVwb3J0IGNhbGwnKQoKIyBkaWFnbm9zdGljcyBhZGQgdjIyMiBhZnRl
ciB2MjIxIGJsb2NrCm9sZD0iIiIgICAgICAgIC4uIHN0cmluZy5mb3JtYXQoCiAgICAgICAgICAg
ICcgdjIyMT0xIHV6cj0lLjJmIHViPSVkIHVwcj0lZCB1ZGVlcD0lZCB1Y2xvc2U9JWQgdXBiPSVk
IHVmPSVkJywKICAgICAgICAgICAgbWFwU3RhdGUudXBMb29rUmF0ZSBvciAwLjAsIG1hcFN0YXRl
LnVwQm9vc3RFdmVudHMgb3IgMCwKICAgICAgICAgICAgbWFwU3RhdGUudXBQcmVkaWN0Q2FzdHMg
b3IgMCwgbWFwU3RhdGUudXBEZWVwUmVwb3J0cyBvciAwLAogICAgICAgICAgICBtYXBTdGF0ZS51
cENsb3NlUnVuIG9yIDAsIG1hcFN0YXRlLnVwUHVsbGJhY2tzIG9yIDAsCiAgICAgICAgICAgIG1h
cFN0YXRlLnVwRmxvb3JBcHBsaWNhdGlvbnMgb3IgMCkpCiIiIgpuZXc9IiIiICAgICAgICAuLiBz
dHJpbmcuZm9ybWF0KAogICAgICAgICAgICAnIHYyMjE9MSB1enI9JS4yZiB1Yj0lZCB1cHI9JWQg
dWRlZXA9JWQgdWNsb3NlPSVkIHVwYj0lZCB1Zj0lZCcsCiAgICAgICAgICAgIG1hcFN0YXRlLnVw
TG9va1JhdGUgb3IgMC4wLCBtYXBTdGF0ZS51cEJvb3N0RXZlbnRzIG9yIDAsCiAgICAgICAgICAg
IG1hcFN0YXRlLnVwUHJlZGljdENhc3RzIG9yIDAsIG1hcFN0YXRlLnVwRGVlcFJlcG9ydHMgb3Ig
MCwKICAgICAgICAgICAgbWFwU3RhdGUudXBDbG9zZVJ1biBvciAwLCBtYXBTdGF0ZS51cFB1bGxi
YWNrcyBvciAwLAogICAgICAgICAgICBtYXBTdGF0ZS51cEZsb29yQXBwbGljYXRpb25zIG9yIDAp
CiAgICAgICAgLi4gc3RyaW5nLmZvcm1hdCgKICAgICAgICAgICAgJyB2MjIyPTEgY2g9JWQgY2hz
PSVkIGNoZD0lZCBjaGU9JWQgY2htPSVkIGNoZj0lZCBjaGc9JWQnLAogICAgICAgICAgICAoKG1h
cFN0YXRlLmNlbGxIYW5kb2ZmVW50aWwgb3IgMC4wKSA+IGludGVyaW9yRWxhcHNlZCkgYW5kIDEg
b3IgMCwKICAgICAgICAgICAgbWFwU3RhdGUuY2VsbEhhbmRvZmZDb3VudCBvciAwLCBtYXBTdGF0
ZS5jZWxsSGFuZG9mZkRvb3JTZWN0b3Igb3IgMCwKICAgICAgICAgICAgbWFwU3RhdGUuY2VsbEhh
bmRvZmZFdmVudHMgb3IgMCwgbWFwU3RhdGUuY2VsbEhhbmRvZmZEb29yTWF0Y2hlcyBvciAwLAog
ICAgICAgICAgICBtYXBTdGF0ZS5jZWxsSGFuZG9mZkZhbGxiYWNrcyBvciAwLCBtYXBTdGF0ZS5j
ZWxsSGFuZG9mZkdyaWRGbG9vcnMgb3IgMCkpCiIiIgpyZXAob2xkLG5ldywnZGlhZ25vc3RpY3Mn
KQoKIyBsb2FkIHByaW50IG1hcmtlcgpyZXAoCiJwcmludCgnW1RTUF9WSVNHUklEX1YyMi4xXSB1
cHdhcmQgYW50aWNpcGF0aW9uIGxvYWRlZCAoY2FtZXJhLVogbW9tZW50dW0gKyBwaXRjaC1sZWFk
aW5nIHJheXMgKyBjZWlsaW5nIHB1bGxiYWNrKScpXG4iLAoicHJpbnQoJ1tUU1BfVklTR1JJRF9W
MjIuMV0gdXB3YXJkIGFudGljaXBhdGlvbiBsb2FkZWQgKGNhbWVyYS1aIG1vbWVudHVtICsgcGl0
Y2gtbGVhZGluZyByYXlzICsgY2VpbGluZyBwdWxsYmFjayknKVxuIgoicHJpbnQoJ1tUU1BfVklT
R1JJRF9WMjIuMl0gaW50ZXJpb3ItY2VsbCBoYW5kb2ZmIGxvYWRlZCAocmV2ZXJzZS1kb29yIGFy
cml2YWwgYnViYmxlICsgY3Jvc3MtY2VsbCBQVlMgcmVzZXQpJylcbiIsCidsb2FkIHByaW50JykK
CmRzdC53cml0ZV90ZXh0KHMsIGVuY29kaW5nPSd1dGYtOCcsIG5ld2xpbmU9J1xuJykKb3V0X3No
YSA9IGhhc2hsaWIuc2hhMjU2KGRzdC5yZWFkX2J5dGVzKCkpLmhleGRpZ2VzdCgpCmlmIG91dF9z
aGEgIT0gRVhQRUNURURfT1VUOgogICAgcmFpc2UgU3lzdGVtRXhpdChmJ0VSUk9SOiB1bmV4cGVj
dGVkIFYyMi4yIG91dHB1dCBTSEEge291dF9zaGF9JykKZm9yIHRva2VuIGluICgKICAgICdUU1Bf
VklTR1JJRF9MVUFfVjIyXzJfSU5URVJDRUxMX0hBTkRPRkYnLAogICAgJ21hcFN0YXRlLmJlZ2lu
Q2VsbEhhbmRvZmYnLAogICAgJ21hcFN0YXRlLmNsZWFyQ3Jvc3NDZWxsVmlzaWJpbGl0eVN0YXRl
JywKICAgICdbVFNQX1ZJU0dSSURfVjIyLjJdIGludGVyaW9yLWNlbGwgaGFuZG9mZiBsb2FkZWQn
LAopOgogICAgaWYgdG9rZW4gbm90IGluIHM6CiAgICAgICAgcmFpc2UgU3lzdGVtRXhpdCgnRVJS
T1I6IG1pc3NpbmcgcG9zdGNvbmRpdGlvbiAnICsgdG9rZW4pCnByaW50KCdQQVNTOiBleGFjdCBW
MjIuMSAtPiBWMjIuMiBpbnRlcmNlbGwtaGFuZG9mZiBwYXRjaCBnZW5lcmF0ZWQnKQpwcmludCgn
VjIyLjIgU0hBOicsIG91dF9zaGEpCg==
PATCH_B64
    base64 -d "$OUT/patch.py.b64" > "$OUT/patch.py"
    rm -f "$OUT/patch.py.b64"
    chmod +x "$OUT/patch.py"

    ACTUAL_PATCH_SHA="$(sha256sum "$OUT/patch.py" | awk '{print $1}')"
    [ "$ACTUAL_PATCH_SHA" = "$EXPECTED_PATCH_SHA" ] || {
        echo "ERROR: embedded patcher bytes differ from the self-tested patcher."
        exit 21
    }
    python3 -m py_compile "$OUT/patch.py"
    echo "PASS: embedded patcher SHA + Python syntax."

    echo
    echo "===== 3/7 GENERATE EXACT PRE-VALIDATED V22.2 CANDIDATE ====="
    python3 "$OUT/patch.py" "$OUT/visgrid-live.lua" "$OUT/visgrid-v22.2.lua"
    NEW_SHA="$(sha256sum "$OUT/visgrid-v22.2.lua" | awk '{print $1}')"
    echo "candidate SHA: $NEW_SHA"
    [ "$NEW_SHA" = "$EXPECTED_NEW_SHA" ]
    grep -Fq 'TSP_VISGRID_LUA_V22_2_INTERCELL_HANDOFF' "$OUT/visgrid-v22.2.lua"
    grep -Fq 'mapState.beginCellHandoff' "$OUT/visgrid-v22.2.lua"
    grep -Fq '[TSP_VISGRID_V22.2] interior-cell handoff loaded' "$OUT/visgrid-v22.2.lua"
    echo "PASS: candidate bytes exactly match the independently Lua-parse-validated V22.2 build."

    echo
    echo "===== 4/7 INSTALL SENSOR ONLY ====="
    REMOTE_NEW="$ROOT/visgrid-v22.2-$STAMP.lua.new"
    BACK="$BASE/visgrid-backups/$STAMP-v22.2-intercell"
    scp -q "${SSH[@]}" "$OUT/visgrid-v22.2.lua" "$DEV:$REMOTE_NEW"

    ssh "${SSH[@]}" "$DEV" "
set -e
mkdir -p '$BACK'
cp -p '$LUA' '$BACK/visgrid.lua'
sha256sum '$LUA' > '$BACK/visgrid.before.sha256'
[ \"\$(sha256sum '$REMOTE_NEW' | awk '{print \$1}')\" = '$EXPECTED_NEW_SHA' ]
grep -Fq 'TSP_VISGRID_LUA_V22_2_INTERCELL_HANDOFF' '$REMOTE_NEW'
mv -f '$REMOTE_NEW' '$LUA'
sync
"
    echo "Backup: $BACK/visgrid.lua"
else
    BACK=""
    echo
    echo "===== 2-4/7 INSTALL SKIPPED — V22.2 ALREADY LIVE ====="
fi

echo
echo "===== 5/7 VERIFY LIVE SENSOR + PROTECTED STATE ====="
LIVE_AFTER="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$LUA'" | awk '{print $1}')"
GAME_AFTER="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$BIN'" | awk '{print $1}')"
TOPO_AFTER="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$TOPO'" | awk '{print $1}')"
DOOR_AFTER="$(ssh "${SSH[@]}" "$DEV" "sha256sum '$DOOR'" | awk '{print $1}')"
DB_AFTER="$(ssh "${SSH[@]}" "$DEV" "stat -c '%s %Y' '$DB'")"
SHARDS_AFTER="$(ssh "${SSH[@]}" "$DEV" "find '$TOPO_CELLS' -type f -name '*.lua' | wc -l")"

VERIFY_OK=1
[ "$LIVE_AFTER" = "$EXPECTED_NEW_SHA" ] || VERIFY_OK=0
[ "$GAME_AFTER" = "$GAME_BEFORE" ] || VERIFY_OK=0
[ "$TOPO_AFTER" = "$TOPO_BEFORE" ] || VERIFY_OK=0
[ "$DOOR_AFTER" = "$DOOR_BEFORE" ] || VERIFY_OK=0
[ "$DB_AFTER" = "$DB_BEFORE" ] || VERIFY_OK=0
[ "$SHARDS_AFTER" = "$SHARDS_BEFORE" ] || VERIFY_OK=0

if [ "$VERIFY_OK" -ne 1 ]; then
    echo "ERROR: post-install verification failed."
    echo "sensor:    $LIVE_AFTER"
    echo "game:      $GAME_BEFORE -> $GAME_AFTER"
    echo "topology:  $TOPO_BEFORE -> $TOPO_AFTER"
    echo "doorgraph: $DOOR_BEFORE -> $DOOR_AFTER"
    echo "DB:        $DB_BEFORE -> $DB_AFTER"
    echo "shards:    $SHARDS_BEFORE -> $SHARDS_AFTER"
    if [ -n "$BACK" ]; then
        echo "Rolling visgrid.lua back to the exact pre-install copy..."
        ssh "${SSH[@]}" "$DEV" "cp -pf '$BACK/visgrid.lua' '$LUA'; sync"
        echo "rollback SHA: $(ssh "${SSH[@]}" "$DEV" "sha256sum '$LUA'" | awk '{print $1}')"
    fi
    exit 30
fi

printf 'live sensor SHA: %s\n' "$LIVE_AFTER"
printf 'game SHA:        %s\n' "$GAME_AFTER"
printf 'topology SHA:    %s\n' "$TOPO_AFTER"
printf 'doorgraph SHA:   %s\n' "$DOOR_AFTER"
printf 'DB size/mtime:   %s\n' "$DB_AFTER"
printf 'topology files:  %s\n' "$SHARDS_AFTER"
echo "PASS: V22.2 live; all protected state is byte/state-identical."

echo
echo "===== 6/7 CREATE TRANSITION TRACE COLLECTOR ====="
COLLECT="$HOME/Downloads/pull-visgrid-v22-2-intercell.sh"
cat > "$COLLECT" <<'COLLECTOR'
#!/usr/bin/env bash
set -Eeuo pipefail
cd "$HOME/Downloads"
if [ -f "$HOME/Downloads/visgrid-tools/device.env" ]; then
    . "$HOME/Downloads/visgrid-tools/device.env" || true
fi
if [ -n "${TSP_DEV:-}" ]; then DEV="$TSP_DEV"
elif [ -n "${TSP_IP:-}" ]; then DEV="root@$TSP_IP"
else DEV="root@192.168.1.25"; fi
ROOT="/mnt/SDCARD/data/ports/openmw51"
LUA="$ROOT/mods/TSPInteriorVisGrid/scripts/TSPInteriorVisGrid/visgrid.lua"
STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$HOME/Downloads/visgrid-v22-2-intercell-$STAMP.txt"
{
    echo "===== V22.2 INSTALL ====="
    ssh -o BatchMode=yes -o ConnectTimeout=8 "$DEV" "sha256sum '$LUA'; grep -nF 'TSP_VISGRID_LUA_V22_2_INTERCELL_HANDOFF' '$LUA' | head -1"
    echo
    echo "===== INTERIOR TRANSITION SESSION ====="
    ssh -o BatchMode=yes -o ConnectTimeout=8 "$DEV" '
ROOT="/mnt/SDCARD/data/ports/openmw51"
for LOG in "$ROOT/openmw_051_log.txt" "$ROOT/config-0.51/openmw.log"; do
    [ -s "$LOG" ] || continue
    echo
    echo "--- $LOG ---"
    tail -n 14000 "$LOG" | grep -Ei \
"Changing to interior|Loading cell|Unloading cell|TSP_LOAD_FREEZE|load-safe|TSP_VISGRID_V22\\.2|TSP_VISGRID_V22\\.1|TSP_VISGRID_V22|TSP_VISGRID_V21|TSP_VISGRID_V20|TSP_VISGRID_V15|reset reason=cell-change|enter interior|doors cell=|PVS floor=|v222=1|Lua.*ERROR|Lua.*error|exception|failed" || true
done
'
} | tee "$OUT"
echo
echo "Saved: $OUT"
COLLECTOR
chmod +x "$COLLECT"
echo "Collector: $COLLECT"

echo
echo "===== 7/7 DONE ====="
echo "Restart OpenMW, then retest Pelagiad, Fort Pelagiad -> Pelagiad, South Wall -> Fort Pelagiad."
echo "The destination should immediately show a V22.2 handoff line and ch=1 for ~5 seconds."
echo "After the one test run:"
echo "  cd ~/Downloads"
echo "  ./pull-visgrid-v22-2-intercell.sh"
echo
echo "Controller log: $LOG"
