#!/usr/bin/env bash
set -Eeuo pipefail

DEVICE="${DEVICE:-root@192.168.1.12}"
ROOT="${ROOT:-/mnt/SDCARD/data/ports/openmw}"
LIVE_BIN="$ROOT/bin/openmw-0.51"
BACKUP_ROOT="$ROOT/tsp_patch_backups"
OUTDIR="${OUTDIR:-/home/bob-simpson/Downloads}"
OUTBIN="$OUTDIR/openmw-0.51-v73-controls-safe"
MANIFEST="$OUTDIR/openmw-0.51-v73-controls-safe.manifest"
REMOTE_UPLOAD="/tmp/openmw-0.51-v73-controls-safe.upload"

fail() { echo "ERROR: $*" >&2; exit 1; }
trap 'rc=$?; echo; echo "ERROR: CHUNK 2 stopped at host line $LINENO (status $rc)." >&2; echo "Your VM terminal remains open." >&2' ERR

echo "===== CHUNK 2: BACKUP / DEPLOY / VERIFY V73 ====="

test -s "$OUTBIN" || fail "missing built binary: $OUTBIN"
test -s "$MANIFEST" || fail "missing manifest: $MANIFEST"

# Manifest is generated by CHUNK 1 and contains simple KEY=VALUE lines.
BASELINE_LIVE_SHA256="$(awk -F= '$1=="BASELINE_LIVE_SHA256"{print $2}' "$MANIFEST")"
EXPECTED="$(awk -F= '$1=="OUTPUT_SHA256"{print $2}' "$MANIFEST")"
LOCAL="$(sha256sum "$OUTBIN" | awk '{print $1}')"

[ -n "$BASELINE_LIVE_SHA256" ] || fail "manifest baseline hash missing"
[ -n "$EXPECTED" ] || fail "manifest output hash missing"
[ "$LOCAL" = "$EXPECTED" ] || fail "local binary hash no longer matches CHUNK 1 manifest"
grep -a -q 'TSP_PRECISE_EDITBOX_CLICK_051_V73' "$OUTBIN" || fail "local binary lacks V73 runtime marker"

echo "Local SHA256: $LOCAL"

echo
echo "===== VERIFY LIVE BASELINE HAS NOT CHANGED ====="
CURRENT_LIVE="$(ssh -n -o BatchMode=yes "$DEVICE" "test -s '$LIVE_BIN' && sha256sum '$LIVE_BIN' | cut -d ' ' -f1")" \
    || fail "could not hash current live binary"

echo "CHUNK 1 baseline: $BASELINE_LIVE_SHA256"
echo "Current live:     $CURRENT_LIVE"

if [ "$CURRENT_LIVE" != "$BASELINE_LIVE_SHA256" ]; then
    fail "live OpenMW changed after CHUNK 1; refusing to overwrite a newer/different build"
fi

echo "Live baseline unchanged: PASS"

STAMP="$(date +%Y%m%d-%H%M%S)"
REMOTE_BACKUP="$BACKUP_ROOT/v73-controls-$STAMP/openmw-0.51.before-v73"

echo
echo "===== 1. BACK UP CURRENT LIVE BINARY FIRST ====="
ssh -n -o BatchMode=yes "$DEVICE" "
set -eu
mkdir -p '$BACKUP_ROOT/v73-controls-$STAMP'
cp -a '$LIVE_BIN' '$REMOTE_BACKUP'
B=\$(sha256sum '$REMOTE_BACKUP' | awk '{print \$1}')
L=\$(sha256sum '$LIVE_BIN' | awk '{print \$1}')
[ \"\$B\" = \"\$L\" ] || { echo 'ERROR: backup hash mismatch' >&2; exit 20; }
echo \"Backup: $REMOTE_BACKUP\"
echo \"Backup SHA256: \$B\"
" || fail "device backup failed"

echo
echo "===== 2. UPLOAD NEW BINARY ====="
scp -q -o BatchMode=yes "$OUTBIN" "$DEVICE:$REMOTE_UPLOAD" || fail "upload failed"

REMOTE_HASH="$(ssh -n -o BatchMode=yes "$DEVICE" "sha256sum '$REMOTE_UPLOAD' | cut -d ' ' -f1")" \
    || fail "could not hash remote upload"

echo "Local SHA256:  $LOCAL"
echo "Upload SHA256: $REMOTE_HASH"
[ "$REMOTE_HASH" = "$LOCAL" ] || fail "remote upload SHA256 mismatch"

echo
echo "===== 3. ATOMIC INSTALL ====="
ssh -n -o BatchMode=yes "$DEVICE" "EXPECTED='$EXPECTED' sh -s" <<'REMOTE'
set -eu
ROOT="/mnt/SDCARD/data/ports/openmw"
LIVE="$ROOT/bin/openmw-0.51"
UPLOAD="/tmp/openmw-0.51-v73-controls-safe.upload"
STAGE="$ROOT/bin/.openmw-0.51-v73-controls-safe-new-$$"

[ -s "$UPLOAD" ] || { echo "ERROR: upload missing" >&2; exit 30; }
UP="$(sha256sum "$UPLOAD" | awk '{print $1}')"
[ "$UP" = "$EXPECTED" ] || { echo "ERROR: upload hash changed" >&2; exit 31; }

rm -f "$STAGE"
cp "$UPLOAD" "$STAGE"
chmod 755 "$STAGE"
ST="$(sha256sum "$STAGE" | awk '{print $1}')"
[ "$ST" = "$EXPECTED" ] || { echo "ERROR: staged hash mismatch" >&2; rm -f "$STAGE"; exit 32; }

mv -f "$STAGE" "$LIVE"
rm -f "$UPLOAD"
sync

FINAL="$(sha256sum "$LIVE" | awk '{print $1}')"
[ "$FINAL" = "$EXPECTED" ] || { echo "ERROR: final live hash mismatch" >&2; exit 33; }
grep -a -q 'TSP_PRECISE_EDITBOX_CLICK_051_V73' "$LIVE" || {
    echo "ERROR: V73 runtime marker missing from live binary" >&2
    exit 34
}

echo "Final live SHA256: $FINAL"
echo "V73 runtime marker: PASS"
REMOTE

echo
echo "===== CHUNK 2 COMPLETE ====="
echo "Live binary: $LIVE_BIN"
echo "Backup:      $REMOTE_BACKUP"
echo "SHA256:      $EXPECTED"
echo "No launcher, helper, config, layout, map source, or libGL files were modified."
