#!/usr/bin/env bash
# TSP_SNDCACHE_V1 - the sound buffer cache is too small to keep what the warm
# decodes into it. Raise it. One setting, no rebuild.
#
#   bash ~/Downloads/tsp_sndcache.sh on     # then ONE load is enough to verify
#   bash ~/Downloads/tsp_sndcache.sh pull
#   bash ~/Downloads/tsp_sndcache.sh off
#
# ============================================================================
# THE EVIDENCE - Steve was right about sound, and I was wrong to dismiss it
# ============================================================================
# Across 33 dumps, 25,760 frames, sound is the most spike-shaped slot there is:
#
#   slot     mean_ms   p95   p99    MAX_ms  >=5ms >=10ms >=20ms >=30ms
#   sound       0.11  0.00  0.25     207.4     26     13     12     11
#
# mean-to-max ratio 1885x, the highest in the table. I dismissed this slot three
# times by pointing at the 0.11 mean. The mean, p95 AND p99 are all blind to it.
#
# The 09-08 doc predicted a ~33 ms synchronous playSound. Here are the frames:
#
#   frame  total_ms  sound_ms  share
#    224     237.8    201.86    85%     <- first seconds of the session
#    384      75.9     40.01    53%     <- first seconds
#    444     134.0     79.79    60%     <- first seconds
#   1056      68.7     36.02    52%
#   1258      77.1     37.17    48%
#   1332      84.0     36.51    43%
#   1414      79.0     40.82    52%
#   1518      82.8     40.10    48%
#   1988      64.5     29.75    46%
#   2608     240.0    207.38    86%
#   2634      96.0     38.01    40%
#
# Mean frame is 27.2 ms. These are 64-240 ms frames where sound is 40-86% of the
# cost. Every one is a visible stutter, and the lowest frame numbers are the first
# seconds of a run - exactly the reported symptom.
#
# ============================================================================
# THE MECHANISM IS ARITHMETIC
# ============================================================================
#   first SNDWARM each launch:  warmed=18 cached=1  failed=1   548-807 ms
#   every later call:           warmed=0  cached=13 failed=0   0.02 ms
#
# FIVE sounds evicted, every launch, without exception.
#
#   OpenMW [Sound] defaults: buffer cache min = 14 MB, buffer cache max = 16 MB
#   13 sounds fit in 16 MB  -> ~1.23 MB each
#   18 sounds need          -> ~22 MB
#
# The warm decodes 18 sounds into a cache that can only hold 13. Five are evicted
# immediately and each re-decodes SYNCHRONOUSLY on next play - a 36-41 ms
# main-thread stall. The warm is working; the cache it warms into is too small to
# keep the result. Raising the cache is the whole fix.
#
# COST: +16 MB of RAM on a device already at 660 MB RSS. That is real and it is
# 2.4% of the footprint, against removing discrete 64-240 ms stalls. If the memory
# cost shows up as worse reclaim, `off` reverts it.
#
# ============================================================================
# THE VERIFICATION IS A SINGLE NUMBER
# ============================================================================
# After this, the second SNDWARM line must read `cached=18`, not `cached=13`.
# That is unambiguous, needs one load and no play session, and if it still says
# 13 then the setting did not reach the engine and nothing else matters yet.
#
# `failed=1` is a SEPARATE defect this does not fix - one sound fails to warm on
# every launch. Worth chasing after, but eviction is the bigger share: 5 sounds
# against 1.
#
# Rule Zero: file, not paste; r() uses -n, rin() takes the heredoc (NEVER -n).
# No grep -r. No $(grep -c x f || echo 0). No apostrophe inside any awk program.
# ⚠ settings.cfg is REGENERATED by the launcher from tsp_cells_on.awk on every
# launch (09-07 doc). This finds the real writer instead of assuming, and refuses
# rather than making a change that gets overwritten at next boot.

set -u
MODE="${1:-}"
case "$MODE" in on|off|pull) : ;; *) echo "usage: bash $0 on|pull|off"; exit 2 ;; esac

TSP="${TSP:-root@192.168.1.12}"
SSH_OPTS="-o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=6"
DL="${DL:-$HOME/Downloads}"
STAMP="$(date +%Y%m%d-%H%M%S)"
CMIN="${CMIN:-24}"
CMAX="${CMAX:-32}"
REP="$DL/tsp-sndcache-$MODE-$STAMP.txt"

r()   { ssh -n $SSH_OPTS "$TSP" "$@"; }
rin() { ssh    $SSH_OPTS "$TSP" "$@"; }
die() { printf '\nFAIL: %s\n' "$*" >&2; exit 1; }
r 'echo ok' >/dev/null 2>&1 || die "cannot reach the TSP at $TSP"

if [ "$MODE" = "pull" ]; then
rin 'sh -s' <<'REMOTE' 2>&1 | tee "$REP"
S=/mnt/SDCARD
G=$S/data/ports/openmw
LG=$G/openmw_log.txt

echo "########## 1. THE ONE NUMBER THAT MATTERS ##########"
echo "  BEFORE: first call warmed=18 cached=1 failed=1, then every later call"
echo "          reported cached=13. Five evicted."
echo "  AFTER:  later calls must report cached=18."
echo
grep -a 'TSP_SNDWARM' "$LG" 2>/dev/null | awk '{
    ts = ""
    if (match($0, /[0-9][0-9]:[0-9][0-9]:[0-9][0-9]\.[0-9]+/)) ts = substr($0, RSTART, RLENGTH)
    w=""; c=""; f=""; ms=""
    for (i = 1; i <= NF; i++) {
        k = index($i, "="); if (!k) continue
        key = substr($i,1,k-1); v = substr($i,k+1)
        if (key == "warmed") w = v
        if (key == "cached") c = v
        if (key == "failed") f = v
        if (key == "ms")     ms = v
    }
    printf "  %s  warmed=%-3s cached=%-3s failed=%-3s %9.2f ms\n", ts, w, c, f, ms + 0
    n++
    if (w + 0 == 0) { lastc = c; later++ }
}
END {
    print ""
    if (!n) { print "  NO SNDWARM LINES. Did the save load? Is OPENMW_DEBUG_LEVEL=INFO?"; exit }
    if (!later) {
        print "  Only the first warm is present - no later call to read cached= from."
        print "  Cross a region boundary or play a little longer, then pull again."
        exit
    }
    printf "  later calls report cached=%s\n", lastc
    if (lastc + 0 >= 18)      print "  => FIXED. Nothing is being evicted any more."
    else if (lastc + 0 > 13)  printf "  => PARTIAL. %s of 18 now held, was 13. Raise the cache further.\n", lastc
    else                      print "  => NO CHANGE. The setting did not reach the engine - see section 2."
}'
echo

echo "########## 2. WHAT THE ENGINE ACTUALLY READ ##########"
for c in "$G/config/settings.cfg" "$G/config-0.51/settings.cfg"; do
    [ -f "$c" ] || continue
    echo "  -- $c --"
    sed -n '/^\[Sound\]/,/^\[/p' "$c" | grep -v '^\[' | sed 's/^/    /'
done
echo "  (if these do NOT show the raised values, the launcher regenerated"
echo "   settings.cfg over the top and the edit went to the wrong place)"
echo

echo "########## 3. DID THE SPIKES GO AWAY ##########"
if ls "$S"/tsp_ring.[0-9]* >/dev/null 2>&1; then
    # shellcheck disable=SC2086
    cat "$S"/tsp_ring.[0-9]* 2>/dev/null | awk '
    !lay {
        p1 = 0
        for (i = 1; i <= NF; i++) if ($i == "|") { p1 = i; break }
        if (p1 < 4) next
        if ($1 + 0 != $1 || $2 + 0 != $2) next
        S0 = 3; S1 = p1 - 1; lay = 1
    }
    lay {
        p1 = 0
        for (i = 1; i <= NF; i++) if ($i == "|") { p1 = i; break }
        if (p1 != S1 + 1) next
        if ($1 + 0 != $1 || $2 + 0 != $2) next
        rows++
        snd = $(S0 + 1) + 0
        if (snd > mx) mx = snd
        if (snd >= 30) o30++
        if (snd >= 20) o20++
        if (snd >= 5)  o5++
        if (snd >= 3) printf "  frame %-8s total %8.1f ms   sound %7.2f ms\n", $1, $2 + 0, snd
    }
    END {
        if (!rows) { print "  (no parseable rows in this run)"; exit }
        printf "\n  %d rows   sound MAX %.1f ms   >=5ms %d   >=20ms %d   >=30ms %d\n", \
            rows, mx, o5+0, o20+0, o30+0
        print  "  BEFORE, across 33 dumps: MAX 207.4 ms, >=5ms 26, >=20ms 12, >=30ms 11"
        if (o20 + 0 == 0) print "  => NO sound spike at or above 20 ms in this run."
        else              print "  => spikes remain; the evicted-sound path is not the only one."
    }'
else
    echo "  (no ring dumps this run - nothing crossed the trigger, which is itself good)"
fi
REMOTE
echo
echo "=================================================================="
echo "  Section 1 is the verdict: cached=18 means fixed, cached=13 means"
echo "  the setting never reached the engine."
echo "  Revert:  bash ~/Downloads/tsp_sndcache.sh off"
echo "=================================================================="
exit 0
fi

if [ "$MODE" = "on" ]; then WMIN=$CMIN; WMAX=$CMAX; LBL="on  buffer cache min=$CMIN max=$CMAX MB"
else                        WMIN=14;    WMAX=16;    LBL="off buffer cache min=14 max=16 MB (OpenMW defaults)"; fi
echo "MODE=$LBL"
echo

rin "WMIN=$WMIN WMAX=$WMAX STAMP=$STAMP MODE=$MODE sh -s" <<'REMOTE' 2>&1 | tee "$REP"
# ---- TSP_SNDCACHE_ARM_BEGIN ----
S=/mnt/SDCARD
G=$S/data/ports/openmw
L=$S/Roms/PORTS/Morrowind.sh

echo "########## 1. WHO WRITES settings.cfg - find it, do not assume ##########"
echo "  The 09-07 doc: settings.cfg is regenerated from tsp_cells_on.awk on every"
echo "  launch, so a direct edit is temporary. Locating every writer first."
echo
echo "  -- generator files present --"
GENS=""
for g in "$S"/tsp_cells_on.awk "$S"/tsp_*.awk; do
    [ -f "$g" ] || continue
    case " $GENS " in *" $g "*) continue ;; esac
    GENS="$GENS $g"
    printf '    %s  (%s lines)\n' "$g" "$(wc -l < "$g")"
done
[ -n "$GENS" ] || echo "    (no tsp_*.awk generators found)"
echo
echo "  -- does any generator mention Sound or buffer cache --"
HIT=""
for g in $GENS; do
    if grep -q -i 'buffer cache\|\[Sound\]' "$g" 2>/dev/null; then
        printf '    %s:\n' "$g"
        grep -n -i 'buffer cache\|\[Sound\]' "$g" | sed 's/^/      /'
        HIT="$HIT $g"
    fi
done
[ -n "$HIT" ] || echo "    none - no generator touches [Sound], so a settings.cfg edit SHOULD persist"
echo
echo "  -- does the launcher write settings.cfg or Sound settings --"
if [ -f "$L" ]; then
    grep -n -i 'settings\.cfg\|buffer cache\|\[Sound\]' "$L" 2>/dev/null | head -20 | sed 's/^/    /' \
        || echo "    (no mention)"
else
    echo "    launcher not found at $L"
fi
echo

echo "########## 2. EVERY settings.cfg, AND ITS [Sound] BLOCK NOW ##########"
CFGS=""
for c in "$G/config/settings.cfg" "$G/config-0.51/settings.cfg"; do
    [ -f "$c" ] && CFGS="$CFGS $c"
done
for c in $(find "$G" -maxdepth 3 -name 'settings.cfg' 2>/dev/null); do
    case " $CFGS " in *" $c "*) : ;; *) CFGS="$CFGS $c" ;; esac
done
[ -n "$CFGS" ] || { echo "  FAIL no settings.cfg found under $G"; exit 1; }
for c in $CFGS; do
    printf '  %s\n' "$c"
    if grep -q '^\[Sound\]' "$c" 2>/dev/null; then
        sed -n '/^\[Sound\]/,/^\[/p' "$c" | grep -v '^\[' | grep -v '^$' | sed 's/^/      /'
    else
        echo "      (no [Sound] section - it will be created)"
    fi
done
echo

echo "########## 3. SET buffer cache min=$WMIN max=$WMAX ##########"
for c in $CFGS; do
    cp -p "$c" "$c.bak-sndcache-$STAMP" || { echo "  FAIL backup $c"; continue; }
    # Ensure a [Sound] section exists, then set both keys inside the file. The keys
    # are unique across settings.cfg so a global substitution is safe; appending to
    # the section is only needed when the key is absent.
    if ! grep -q '^\[Sound\]' "$c" 2>/dev/null; then
        printf '\n[Sound]\n' >> "$c"
    fi
    for kv in "buffer cache min|$WMIN" "buffer cache max|$WMAX"; do
        key="${kv%|*}"; val="${kv#*|}"
        if grep -q "^$key[[:space:]]*=" "$c" 2>/dev/null; then
            awk -v k="$key" -v v="$val" '
                index($0, k "  = ") == 1 || index($0, k " = ") == 1 || index($0, k "=") == 1 {
                    print k " = " v; next
                }
                { print }' "$c" > "$c.n" && mv "$c.n" "$c"
        else
            # insert immediately after the [Sound] header so it lands in the section
            awk -v k="$key" -v v="$val" '
                { print }
                /^\[Sound\]$/ && !done { print k " = " v; done = 1 }' "$c" > "$c.n" && mv "$c.n" "$c"
        fi
    done
    GMIN="$(sed -n 's/^buffer cache min[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' "$c" | tail -1)"
    GMAX="$(sed -n 's/^buffer cache max[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' "$c" | tail -1)"
    if [ "${GMIN:-x}" = "$WMIN" ] && [ "${GMAX:-x}" = "$WMAX" ]; then
        printf '  OK   %s  min=%s max=%s\n' "$c" "$GMIN" "$GMAX"
    else
        printf '  FAIL %s  got min=[%s] max=[%s] - restoring\n' "$c" "${GMIN:-}" "${GMAX:-}"
        cp -p "$c.bak-sndcache-$STAMP" "$c"
    fi
done
echo
echo "  -- the [Sound] block as it now reads --"
for c in $CFGS; do
    printf '    %s\n' "$c"
    sed -n '/^\[Sound\]/,/^\[/p' "$c" | grep -v '^\[' | grep -v '^$' | sed 's/^/      /'
done
echo

echo "########## 4. BEHAVIOURAL CHECK - would a generator overwrite this ##########"
# The 09-07 pattern: run the generator against the real settings.cfg and see what
# it emits. If it does not emit buffer cache lines, the edit survives.
DONE=0
for g in $GENS; do
    FIRST="$(echo $CFGS | cut -d' ' -f1)"
    OUT="$(awk -f "$g" "$FIRST" 2>/dev/null | sed -n 's/^buffer cache m\(in\|ax\)[[:space:]]*=[[:space:]]*\(.*\)$/\1 \2/p' | tr '\n' ' ')"
    if [ -n "$OUT" ]; then
        printf '  %s EMITS buffer cache: %s\n' "$(basename "$g")" "$OUT"
        echo "    ** this generator will overwrite the edit at next launch."
        echo "       The value has to go INTO this awk, not into settings.cfg."
        DONE=1
    else
        printf '  %s does not emit buffer cache lines\n' "$(basename "$g")"
    fi
done
[ "$DONE" -eq 0 ] && echo "  => no generator emits these keys, so the settings.cfg edit should persist."
echo

echo "########## 5. CLEAN CAPTURE ##########"
[ -s "$G/openmw_log.txt" ] && mv "$G/openmw_log.txt" "$G/openmw_log.txt.sndcache-$MODE-$STAMP" \
    && echo "  log rotated"
A="$S/tsp_hitch_archive_$STAMP"; k=0
for d in "$S"/tsp_ring.[0-9]*; do
    [ -f "$d" ] || continue
    mkdir -p "$A"; cp -p "$d" "$A/" && rm -f "$d" && k=$((k + 1))
done
echo "  ring dumps archived: $k"
printf 'TSP_RING_TRIG=60\nTSP_RING_MAX=12\n' > "$S/tsp_ring.conf"
echo "  ring trigger set to 60 ms - low enough to catch a 36 ms sound spike"
echo "  inside a 64-96 ms frame, which a 1000 ms trigger would have missed"
[ -f "$S/tsp_ring_off" ] && mv "$S/tsp_ring_off" "$S/tsp_ring_off.parked-$STAMP"
sync
echo "  MemAvailable: $(awk '/^MemAvailable:/{print $2}' /proc/meminfo) kB"
echo "  (+16 MB of sound cache comes out of this)"
echo

echo "########## READY CHECK ##########"
F=0
for c in $CFGS; do
    GMIN="$(sed -n 's/^buffer cache min[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' "$c" | tail -1)"
    GMAX="$(sed -n 's/^buffer cache max[[:space:]]*=[[:space:]]*\(.*\)$/\1/p' "$c" | tail -1)"
    [ "${GMIN:-x}" = "$WMIN" ] && [ "${GMAX:-x}" = "$WMAX" ] \
        || { printf '  FAIL %s\n' "$c"; F=1; }
done
[ "$F" -eq 0 ] && echo "  OK   every settings.cfg has min=$WMIN max=$WMAX"
[ -s "$G/openmw_log.txt" ] && { echo "  FAIL log not empty"; F=1; } || echo "  OK   log clean"
ls "$S"/tsp_ring.[0-9]* >/dev/null 2>&1 && { echo "  FAIL dumps present"; F=1; } || echo "  OK   dump slots free"
echo
[ "$F" -eq 0 ] && echo "READY" || echo "NOT READY"
# ---- TSP_SNDCACHE_ARM_END ----
REMOTE

echo
if [ "$MODE" = "off" ]; then
    echo "=================================================================="
    echo "  Back to the OpenMW defaults, 14/16 MB."
    echo "=================================================================="
    exit 0
fi
echo "=================================================================="
echo "  ONE LOAD IS ENOUGH TO VERIFY. Launch, load your save, walk far"
echo "  enough to cross a region boundary so a second SNDWARM fires, then"
echo "  quit and run:"
echo "     bash ~/Downloads/tsp_sndcache.sh pull"
echo
echo "  The verdict is one number: later SNDWARM calls must say cached=18."
echo "  13 means the setting never reached the engine."
echo
echo "  If you keep playing, the ring trigger is now 60 ms so a 36 ms sound"
echo "  spike inside an 80 ms frame gets captured - the 1000 ms trigger we"
echo "  had been using could never see one."
echo
echo "  Revert:  bash ~/Downloads/tsp_sndcache.sh off"
echo "=================================================================="
