import sys
P = "/root/openmw-0.51-tsp-src/apps/openmw/mwrender/occlusionculling.cpp"
if len(sys.argv) > 1:
    P = sys.argv[1]
MARK = "TSP_INTOCC_V3"
src = open(P, encoding="utf-8").read()
if MARK in src:
    print("ALREADY APPLIED: " + MARK + " present. Nothing written.")
    sys.exit(0)
if "TSP_INTOCC_V1" in src or "TSP_INTOCC_V2" in src:
    print("REFUSING: file still carries an older TSP_INTOCC. Restore the pristine backup first.")
    sys.exit(1)
A1 = "#include <cmath>"
A2 = "        std::string_view getModelPathForNode(osg::Node* node)"
A3 = "        const unsigned int numChildren = node->getNumChildren();"
A4 = "            const OccluderMesh& mesh = getOccluderMesh(child);"
A5 = "                    if (!scaledBB.contains(cv->getEyePoint()))"
A6 = "            if (skipOcclusion || mCuller->testVisibleAABB(childBB))"
CTOR = "        , mStorage(storage)\n    {\n    }\n\n    const OccluderMesh& CellOcclusionCallback::getOccluderMesh"
fail = []
for nm, a in (("A1", A1), ("A2", A2), ("A3", A3), ("A4", A4), ("A5", A5), ("A6", A6), ("CTOR", CTOR)):
    n = src.count(a)
    if n != 1:
        fail.append(nm + " matched " + str(n) + " times: " + repr(a[:70]))
if fail:
    print("ANCHOR FAILURE - NOTHING WRITTEN")
    for f in fail:
        print("  " + f)
    print("--- survey ---")
    for i, l in enumerate(src.split("\n"), 1):
        if ("scaledBB" in l) or ("getModelPathForNode" in l) or ("cmath" in l) or ("numChildren" in l) or ("getOccluderMesh(child)" in l) or ("skipOcclusion" in l) or ("mStorage(storage)" in l):
            print("  %5d| %s" % (i, l))
    sys.exit(1)
H = ""
H += "        // TSP_INTOCC_V3 - make interior occlusion actually reject geometry.\n"
H += "        // Measured baseline (Caldera interior, terrain tris=0): 27 occluders / 4679 tris\n"
H += "        // rasterised, 212 objects tested, 0-23 occluded. Occlusion runs indoors, it just\n"
H += "        // rejects nothing. Three independent reasons, one switch each, all default-off:\n"
H += "        //   TSP_INTOCC=1  Pass 2 tests the object's REAL world AABB. Upstream builds the\n"
H += "        //                 test box from the bounding SPHERE - up to 73% larger per axis -\n"
H += "        //                 and MOC TestRect only rejects when the WHOLE rect is behind the\n"
H += "        //                 buffer, so an inflated rect poking past a wall never rejects.\n"
H += "        //   TSP_INTOCC=2  1, plus Pass 1 large objects get visibility-tested (upstream\n"
H += "        //                 always traverses them). Tested BEFORE the object rasterises\n"
H += "        //                 itself, so it can never occlude itself.\n"
H += "        //   TSP_INTOCC_SHRINK=<f>  override occluder shrink factor (1.0 = no shrink).\n"
H += "        //                 Shrunken occluders leave seams at every wall joint.\n"
H += "        //   TSP_INTOCC_INSIDE=<f>  override the eye-inside threshold (1.0 = true AABB).\n"
H += "        //                 Any occluder whose scaled AABB contains the eye is skipped -\n"
H += "        //                 indoors that can be most of the room shell.\n"
H += "        //   TSP_INTOCC_MINR=<f>    override occluder min radius. Lower = interior wall\n"
H += "        //                 pieces become occluders instead of occludees.\n"
H += "        //   TSP_INTOCC_EYEIN=1     rasterise eye-inside occluders anyway (budgeted).\n"
H += "        // V1 removed the eye-inside guard with no budget and hung the frame; every path\n"
H += "        // here is hard-capped and env-tunable without a rebuild.\n"
H += "        struct TspIntOccCfg\n"
H += "        {\n"
H += "            int mMode;\n"
H += "            int mEyeIn;\n"
H += "            int mMaxOcc;\n"
H += "            int mMaxTri;\n"
H += "            int mBudget;\n"
H += "            int mReportEvery;\n"
H += "            int mBoxBudget;\n"
H += "            float mShrink;\n"
H += "            float mInside;\n"
H += "            float mMinR;\n"
H += "        };\n"
H += "        int tspEnvInt(const char* name, int def)\n"
H += "        {\n"
H += "            const char* e = std::getenv(name);\n"
H += "            if (e == nullptr || e[0] == 0)\n"
H += "                return def;\n"
H += "            return std::atoi(e);\n"
H += "        }\n"
H += "        float tspEnvFloat(const char* name, float def)\n"
H += "        {\n"
H += "            const char* e = std::getenv(name);\n"
H += "            if (e == nullptr || e[0] == 0)\n"
H += "                return def;\n"
H += "            return static_cast<float>(std::atof(e));\n"
H += "        }\n"
H += "        const TspIntOccCfg& tspIntOccCfg()\n"
H += "        {\n"
H += "            static TspIntOccCfg sCfg;\n"
H += "            static bool sInit = false;\n"
H += "            if (!sInit)\n"
H += "            {\n"
H += "                sInit = true;\n"
H += "                sCfg.mMode = tspEnvInt(\"TSP_INTOCC\", 0);\n"
H += "                if (sCfg.mMode < 0)\n"
H += "                    sCfg.mMode = 0;\n"
H += "                sCfg.mEyeIn = tspEnvInt(\"TSP_INTOCC_EYEIN\", 0);\n"
H += "                sCfg.mMaxOcc = tspEnvInt(\"TSP_INTOCC_MAXOCC\", 12);\n"
H += "                sCfg.mMaxTri = tspEnvInt(\"TSP_INTOCC_MAXTRI\", 512);\n"
H += "                sCfg.mBudget = tspEnvInt(\"TSP_INTOCC_BUDGET\", 8000);\n"
H += "                sCfg.mReportEvery = tspEnvInt(\"TSP_INTOCC_REPORT\", 300);\n"
H += "                sCfg.mBoxBudget = tspEnvInt(\"TSP_INTOCC_BOXBUDGET\", 64);\n"
H += "                sCfg.mShrink = tspEnvFloat(\"TSP_INTOCC_SHRINK\", -1.0f);\n"
H += "                sCfg.mInside = tspEnvFloat(\"TSP_INTOCC_INSIDE\", -1.0f);\n"
H += "                sCfg.mMinR = tspEnvFloat(\"TSP_INTOCC_MINR\", -1.0f);\n"
H += "                Log(Debug::Warning) << \"TSP_INTOCC_V3 cfg mode=\" << sCfg.mMode << \" eyein=\" << sCfg.mEyeIn\n"
H += "                                    << \" maxocc=\" << sCfg.mMaxOcc << \" maxtri=\" << sCfg.mMaxTri\n"
H += "                                    << \" budget=\" << sCfg.mBudget << \" report=\" << sCfg.mReportEvery\n"
H += "                                    << \" boxbudget=\" << sCfg.mBoxBudget\n"
H += "                                    << \" shrink_ovr=\" << sCfg.mShrink << \" inside_ovr=\" << sCfg.mInside\n"
H += "                                    << \" minr_ovr=\" << sCfg.mMinR;\n"
H += "            }\n"
H += "            return sCfg;\n"
H += "        }\n"
H += "        unsigned int sTspFrame = 0xffffffffu;\n"
H += "        long sTspFrames = 0;\n"
H += "        long sTspBoxBuilt = 0;\n"
H += "        long sTspBoxDyn = 0;\n"
H += "        int sBoxThisFrame = 0;\n"
H += "        int sBoxDeferred = 0;\n"
H += "        int sP1Total = 0;\n"
H += "        int sP1Tested = 0;\n"
H += "        int sP1Culled = 0;\n"
H += "        int sP2Total = 0;\n"
H += "        int sP2Tested = 0;\n"
H += "        int sP2Culled = 0;\n"
H += "        int sP2Skip = 0;\n"
H += "        int sEyeSeen = 0;\n"
H += "        int sEyeRast = 0;\n"
H += "        int sEyeTris = 0;\n"
H += "        struct TspBoxEntry\n"
H += "        {\n"
H += "            osg::BoundingSphere::vec_type mCentre;\n"
H += "            osg::BoundingSphere::value_type mRadius;\n"
H += "            osg::BoundingBox mBox;\n"
H += "            bool mDynamic;\n"
H += "        };\n"
H += "        // Real world-space box for a cell child. ComputeBoundsVisitor is far too expensive\n"
H += "        // to run per frame, so results are cached and validated against the node's bounding\n"
H += "        // sphere. A node whose sphere ever changes (actors, anything animated) is marked\n"
H += "        // dynamic and permanently falls back to the cheap sphere box - that is the only\n"
H += "        // thing standing between this and a per-frame full-subtree traversal of the cell.\n"
H += "        const osg::BoundingBox& tspTightBox(osg::Node* child, const osg::BoundingSphere& bs)\n"
H += "        {\n"
H += "            static std::map<osg::Node*, TspBoxEntry> sCache;\n"
H += "            static osg::BoundingBox sFallback;\n"
H += "            if (sCache.size() > 32768)\n"
H += "                sCache.clear();\n"
H += "            std::map<osg::Node*, TspBoxEntry>::iterator it = sCache.find(child);\n"
H += "            if (it != sCache.end())\n"
H += "            {\n"
H += "                if (!it->second.mDynamic && it->second.mRadius == bs.radius()\n"
H += "                    && it->second.mCentre == bs.center())\n"
H += "                    return it->second.mBox;\n"
H += "                if (!it->second.mDynamic)\n"
H += "                {\n"
H += "                    it->second.mDynamic = true;\n"
H += "                    ++sTspBoxDyn;\n"
H += "                }\n"
H += "                sFallback = osg::BoundingBox();\n"
H += "                sFallback.expandBy(bs);\n"
H += "                return sFallback;\n"
H += "            }\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (c.mBoxBudget > 0 && sBoxThisFrame >= c.mBoxBudget)\n"
H += "            {\n"
H += "                ++sBoxDeferred;\n"
H += "                sFallback = osg::BoundingBox();\n"
H += "                sFallback.expandBy(bs);\n"
H += "                return sFallback;\n"
H += "            }\n"
H += "            ++sBoxThisFrame;\n"
H += "            osg::ComputeBoundsVisitor cbv;\n"
H += "            child->accept(cbv);\n"
H += "            TspBoxEntry e;\n"
H += "            e.mCentre = bs.center();\n"
H += "            e.mRadius = bs.radius();\n"
H += "            e.mBox = cbv.getBoundingBox();\n"
H += "            e.mDynamic = false;\n"
H += "            if (!e.mBox.valid())\n"
H += "                e.mBox.expandBy(bs);\n"
H += "            ++sTspBoxBuilt;\n"
H += "            sCache[child] = e;\n"
H += "            return sCache[child].mBox;\n"
H += "        }\n"
H += "        void tspIntOccBeginFrame(unsigned int frame)\n"
H += "        {\n"
H += "            if (frame == sTspFrame)\n"
H += "                return;\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (sTspFrame != 0xffffffffu && c.mMode >= 1)\n"
H += "            {\n"
H += "                ++sTspFrames;\n"
H += "                if (c.mReportEvery > 0 && (sTspFrames % c.mReportEvery) == 0)\n"
H += "                    Log(Debug::Warning) << \"TSP_INTOCC_V3 f=\" << sTspFrame\n"
H += "                                        << \" p1 tot=\" << sP1Total << \" tst=\" << sP1Tested\n"
H += "                                        << \" cul=\" << sP1Culled\n"
H += "                                        << \" | p2 tot=\" << sP2Total << \" tst=\" << sP2Tested\n"
H += "                                        << \" cul=\" << sP2Culled << \" skip=\" << sP2Skip\n"
H += "                                        << \" | eyein seen=\" << sEyeSeen << \" rast=\" << sEyeRast\n"
H += "                                        << \" tris=\" << sEyeTris\n"
H += "                                        << \" | box built=\" << sTspBoxBuilt << \" dyn=\" << sTspBoxDyn\n"
H += "                                        << \" deferred=\" << sBoxDeferred;\n"
H += "            }\n"
H += "            sTspFrame = frame;\n"
H += "            sBoxThisFrame = 0;\n"
H += "            sBoxDeferred = 0;\n"
H += "            sP1Total = 0;\n"
H += "            sP1Tested = 0;\n"
H += "            sP1Culled = 0;\n"
H += "            sP2Total = 0;\n"
H += "            sP2Tested = 0;\n"
H += "            sP2Culled = 0;\n"
H += "            sP2Skip = 0;\n"
H += "            sEyeSeen = 0;\n"
H += "            sEyeRast = 0;\n"
H += "            sEyeTris = 0;\n"
H += "        }\n"
H += "        bool tspIntOccAllowInside(int tris)\n"
H += "        {\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            ++sEyeSeen;\n"
H += "            if (c.mEyeIn == 0)\n"
H += "                return false;\n"
H += "            if (c.mMaxTri > 0 && tris > c.mMaxTri)\n"
H += "                return false;\n"
H += "            if (c.mMaxOcc > 0 && sEyeRast >= c.mMaxOcc)\n"
H += "                return false;\n"
H += "            if (c.mBudget > 0 && sEyeTris + tris > c.mBudget)\n"
H += "                return false;\n"
H += "            ++sEyeRast;\n"
H += "            sEyeTris += tris;\n"
H += "            return true;\n"
H += "        }\n"
N1 = A1 + "\n#include <cstdlib>\n#include <map>\n#include <osg/ComputeBoundsVisitor>"
N2 = H + A2
N3 = "        tspIntOccBeginFrame(cv->getTraversalNumber());\n" + A3
N4 = "            ++sP1Total;\n"
N4 += "            if (tspIntOccCfg().mMode >= 2)\n"
N4 += "            {\n"
N4 += "                ++sP1Tested;\n"
N4 += "                if (!mCuller->testVisibleAABB(tspTightBox(child, bs)))\n"
N4 += "                {\n"
N4 += "                    ++sP1Culled;\n"
N4 += "                    continue;\n"
N4 += "                }\n"
N4 += "            }\n"
N4 += A4
N5 = "                    const bool tspEyeInside = scaledBB.contains(cv->getEyePoint());\n"
N5 += "                    if (!tspEyeInside\n"
N5 += "                        || tspIntOccAllowInside(static_cast<int>(mesh.indices.size() / 3)))"
N6 = "            ++sP2Total;\n"
N6 += "            bool tspVisible = true;\n"
N6 += "            if (skipOcclusion)\n"
N6 += "                ++sP2Skip;\n"
N6 += "            else\n"
N6 += "            {\n"
N6 += "                ++sP2Tested;\n"
N6 += "                if (tspIntOccCfg().mMode >= 1)\n"
N6 += "                    childBB = tspTightBox(child, bs);\n"
N6 += "                tspVisible = mCuller->testVisibleAABB(childBB);\n"
N6 += "                if (!tspVisible)\n"
N6 += "                    ++sP2Culled;\n"
N6 += "            }\n"
N6 += "            if (tspVisible)"
CTORNEW = "        , mStorage(storage)\n    {\n"
CTORNEW += "        const TspIntOccCfg& tspCfg = tspIntOccCfg();\n"
CTORNEW += "        if (tspCfg.mShrink >= 0.0f)\n"
CTORNEW += "            mOccluderShrinkFactor = tspCfg.mShrink;\n"
CTORNEW += "        if (tspCfg.mInside >= 0.0f)\n"
CTORNEW += "            mOccluderInsideThreshold = tspCfg.mInside;\n"
CTORNEW += "        if (tspCfg.mMinR >= 0.0f)\n"
CTORNEW += "            mOccluderMinRadius = tspCfg.mMinR;\n"
CTORNEW += "        static bool sTspParamsLogged = false;\n"
CTORNEW += "        if (!sTspParamsLogged)\n"
CTORNEW += "        {\n"
CTORNEW += "            sTspParamsLogged = true;\n"
CTORNEW += "            Log(Debug::Warning) << \"TSP_INTOCC_V3 params minRadius=\" << mOccluderMinRadius\n"
CTORNEW += "                                << \" maxRadius=\" << mOccluderMaxRadius\n"
CTORNEW += "                                << \" shrink=\" << mOccluderShrinkFactor\n"
CTORNEW += "                                << \" meshRes=\" << mOccluderMeshResolution\n"
CTORNEW += "                                << \" maxMeshRes=\" << mOccluderMaxMeshResolution\n"
CTORNEW += "                                << \" insideThresh=\" << mOccluderInsideThreshold\n"
CTORNEW += "                                << \" maxDist=\" << std::sqrt(mOccluderMaxDistanceSq)\n"
CTORNEW += "                                << \" staticOcc=\" << (mEnableStaticOccluders ? 1 : 0)\n"
CTORNEW += "                                << \" maxTriangles=\" << mMaxTriangles;\n"
CTORNEW += "        }\n"
CTORNEW += "    }\n\n    const OccluderMesh& CellOcclusionCallback::getOccluderMesh"
out = src
for a, n in ((A1, N1), (A2, N2), (A3, N3), (A4, N4), (A5, N5), (A6, N6), (CTOR, CTORNEW)):
    out = out.replace(a, n, 1)
if out.count("{") != out.count("}"):
    print("BRACE IMBALANCE - NOTHING WRITTEN: " + str(out.count("{")) + " vs " + str(out.count("}")))
    sys.exit(1)
if out.count(MARK) < 4:
    print("MARKER CHECK FAILED (" + str(out.count(MARK)) + ") - NOTHING WRITTEN")
    sys.exit(1)
for frag in ("#include <osg/ComputeBoundsVisitor>", "tspTightBox(child, bs)", "sTspParamsLogged", "tspIntOccBeginFrame(cv->getTraversalNumber())", "mOccluderShrinkFactor = tspCfg.mShrink", "++sP2Culled"):
    if frag not in out:
        print("REQUIRED FRAGMENT MISSING (" + frag + ") - NOTHING WRITTEN")
        sys.exit(1)
open(P, "w", encoding="utf-8").write(out)
print("PATCH APPLIED: " + MARK)
print("  bytes   : " + str(len(src)) + " -> " + str(len(out)))
print("  braces  : " + str(out.count("{")) + " balanced")
print("  markers : " + str(out.count(MARK)))
