import sys
P = "/root/openmw-0.51-tsp-src/apps/openmw/mwrender/occlusionculling.cpp"
if len(sys.argv) > 1:
    P = sys.argv[1]
MARK = "TSP_INTOCC_V4"
src = open(P, encoding="utf-8").read()
if MARK in src:
    print("ALREADY APPLIED: " + MARK + " present. Nothing written.")
    sys.exit(0)
for old in ("TSP_INTOCC_V1", "TSP_INTOCC_V2", "TSP_INTOCC_V3"):
    if old in src:
        print("REFUSING: file still carries " + old + ". Restore the pristine backup first.")
        sys.exit(1)
A1 = "#include <cmath>"
A2 = "        std::string_view getModelPathForNode(osg::Node* node)"
A3 = "        const unsigned int numChildren = node->getNumChildren();"
A4 = "            const OccluderMesh& mesh = getOccluderMesh(child);"
A5 = "                    if (!scaledBB.contains(cv->getEyePoint()))"
A6 = "            // is reserved for culling small objects in Pass 2."
A7 = "        // Pass 2: Small objects"
A8 = "            if (skipOcclusion || mCuller->testVisibleAABB(childBB))"
CTOR = "        , mStorage(storage)\n    {\n    }\n\n    const OccluderMesh& CellOcclusionCallback::getOccluderMesh"
fail = []
for nm, a in (("A1", A1), ("A2", A2), ("A3", A3), ("A4", A4), ("A5", A5), ("A6", A6), ("A7", A7), ("A8", A8), ("CTOR", CTOR)):
    n = src.count(a)
    if n != 1:
        fail.append(nm + " matched " + str(n) + " times: " + repr(a[:70]))
if fail:
    print("ANCHOR FAILURE - NOTHING WRITTEN")
    for f in fail:
        print("  " + f)
    print("--- survey ---")
    for i, l in enumerate(src.split("\n"), 1):
        if ("scaledBB" in l) or ("getModelPathForNode" in l) or ("cmath" in l) or ("numChildren" in l) or ("getOccluderMesh(child)" in l) or ("skipOcclusion" in l) or ("mStorage(storage)" in l) or ("Pass 2" in l):
            print("  %5d| %s" % (i, l))
    sys.exit(1)
H = ""
H += "        // TSP_INTOCC_V4 - interior occlusion. Measured on device 2026-08-25, Caldera\n"
H += "        // interior, standing on a narrow stair facing a blank wall, 13-14 fps:\n"
H += "        //   params minRadius=400 maxRadius=5000 shrink=1 meshRes=7 insideThresh=1\n"
H += "        //          maxDist=6144 maxTriangles=30000 (4679 in use)\n"
H += "        //   V3 mode 1: p1 tot=29 tst=0 cul=0 | p2 tot=218 tst=212 cul=0-33 | eyein seen=1-2\n"
H += "        // shrink=1 means occluders are NOT shrunk and insideThresh=1 means the eye-inside\n"
H += "        // guard costs only 1-2 occluders a frame, so both of those theories are dead. The\n"
H += "        // tight-AABB fix works but only reaches Pass 2, which is ~28 of 212 small objects -\n"
H += "        // a few percent of the frame's drawables. The 29 Pass 1 architecture pieces carry a\n"
H += "        // large share of the drawables and upstream NEVER visibility-tests them.\n"
H += "        // V4 adds:\n"
H += "        //   TSP_INTOCC=2  two-phase Pass 1. Every large occluder is rasterised first, then\n"
H += "        //                 every large object is tested against the COMPLETE buffer and only\n"
H += "        //                 traversed if visible. V3 tested inside the same loop, so a wall\n"
H += "        //                 rasterised later in child order could not occlude a room tested\n"
H += "        //                 earlier - which is also the flicker upstream's comment warns of,\n"
H += "        //                 and it is fixed by ordering rather than by skipping the test.\n"
H += "        //   drawable accounting. Object counts do not predict frame time; drawables do\n"
H += "        //                 (frame_ms ~= 4 + 0.136 x visible drawables). Every cached box now\n"
H += "        //                 carries its subtree's drawable count, so the report says how many\n"
H += "        //                 of the ~490 drawables each pass is actually worth.\n"
H += "        //   TSP_INTOCC=1  unchanged: Pass 2 tests the real world AABB, not the sphere box.\n"
H += "        // Everything is env-gated, mode 0 is upstream, and every new path is budgeted.\n"
H += "        struct TspIntOccCfg\n"
H += "        {\n"
H += "            int mMode;\n"
H += "            int mEyeIn;\n"
H += "            int mMaxOcc;\n"
H += "            int mMaxTri;\n"
H += "            int mBudget;\n"
H += "            int mReportEvery;\n"
H += "            int mBoxBudget;\n"
H += "            float mShrink;\n"
H += "            float mInside;\n"
H += "            float mMinR;\n"
H += "        };\n"
H += "        int tspEnvInt(const char* name, int def)\n"
H += "        {\n"
H += "            const char* e = std::getenv(name);\n"
H += "            if (e == nullptr || e[0] == 0)\n"
H += "                return def;\n"
H += "            return std::atoi(e);\n"
H += "        }\n"
H += "        float tspEnvFloat(const char* name, float def)\n"
H += "        {\n"
H += "            const char* e = std::getenv(name);\n"
H += "            if (e == nullptr || e[0] == 0)\n"
H += "                return def;\n"
H += "            return static_cast<float>(std::atof(e));\n"
H += "        }\n"
H += "        const TspIntOccCfg& tspIntOccCfg()\n"
H += "        {\n"
H += "            static TspIntOccCfg sCfg;\n"
H += "            static bool sInit = false;\n"
H += "            if (!sInit)\n"
H += "            {\n"
H += "                sInit = true;\n"
H += "                sCfg.mMode = tspEnvInt(\"TSP_INTOCC\", 0);\n"
H += "                if (sCfg.mMode < 0)\n"
H += "                    sCfg.mMode = 0;\n"
H += "                sCfg.mEyeIn = tspEnvInt(\"TSP_INTOCC_EYEIN\", 0);\n"
H += "                sCfg.mMaxOcc = tspEnvInt(\"TSP_INTOCC_MAXOCC\", 12);\n"
H += "                sCfg.mMaxTri = tspEnvInt(\"TSP_INTOCC_MAXTRI\", 512);\n"
H += "                sCfg.mBudget = tspEnvInt(\"TSP_INTOCC_BUDGET\", 8000);\n"
H += "                sCfg.mReportEvery = tspEnvInt(\"TSP_INTOCC_REPORT\", 120);\n"
H += "                sCfg.mBoxBudget = tspEnvInt(\"TSP_INTOCC_BOXBUDGET\", 64);\n"
H += "                sCfg.mShrink = tspEnvFloat(\"TSP_INTOCC_SHRINK\", -1.0f);\n"
H += "                sCfg.mInside = tspEnvFloat(\"TSP_INTOCC_INSIDE\", -1.0f);\n"
H += "                sCfg.mMinR = tspEnvFloat(\"TSP_INTOCC_MINR\", -1.0f);\n"
H += "                Log(Debug::Warning) << \"TSP_INTOCC_V4 cfg mode=\" << sCfg.mMode << \" eyein=\" << sCfg.mEyeIn\n"
H += "                                    << \" maxocc=\" << sCfg.mMaxOcc << \" maxtri=\" << sCfg.mMaxTri\n"
H += "                                    << \" budget=\" << sCfg.mBudget << \" report=\" << sCfg.mReportEvery\n"
H += "                                    << \" boxbudget=\" << sCfg.mBoxBudget\n"
H += "                                    << \" shrink_ovr=\" << sCfg.mShrink << \" inside_ovr=\" << sCfg.mInside\n"
H += "                                    << \" minr_ovr=\" << sCfg.mMinR;\n"
H += "            }\n"
H += "            return sCfg;\n"
H += "        }\n"
H += "        unsigned int sTspFrame = 0xffffffffu;\n"
H += "        long sTspFrames = 0;\n"
H += "        long sTspBoxBuilt = 0;\n"
H += "        long sTspBoxDyn = 0;\n"
H += "        int sBoxThisFrame = 0;\n"
H += "        int sBoxDeferred = 0;\n"
H += "        int sP1Total = 0;\n"
H += "        int sP1Tested = 0;\n"
H += "        int sP1Culled = 0;\n"
H += "        int sP1TotDw = 0;\n"
H += "        int sP1CulDw = 0;\n"
H += "        int sP2Total = 0;\n"
H += "        int sP2Tested = 0;\n"
H += "        int sP2Culled = 0;\n"
H += "        int sP2Skip = 0;\n"
H += "        int sP2TotDw = 0;\n"
H += "        int sP2CulDw = 0;\n"
H += "        int sEyeSeen = 0;\n"
H += "        int sEyeRast = 0;\n"
H += "        int sEyeTris = 0;\n"
H += "        struct TspBoxEntry\n"
H += "        {\n"
H += "            osg::BoundingSphere::vec_type mCentre;\n"
H += "            osg::BoundingSphere::value_type mRadius = 0;\n"
H += "            osg::BoundingBox mBox;\n"
H += "            int mDrawables = 1;\n"
H += "            bool mDynamic = false;\n"
H += "        };\n"
H += "        struct TspCountVisitor : public osg::NodeVisitor\n"
H += "        {\n"
H += "            TspCountVisitor()\n"
H += "                : osg::NodeVisitor(osg::NodeVisitor::TRAVERSE_ALL_CHILDREN)\n"
H += "            {\n"
H += "            }\n"
H += "            void apply(osg::Drawable& drawable) override\n"
H += "            {\n"
H += "                (void)drawable;\n"
H += "                ++mCount;\n"
H += "            }\n"
H += "            int mCount = 0;\n"
H += "        };\n"
H += "        // Real world-space box AND subtree drawable count for a cell child. The visitors are\n"
H += "        // far too expensive to run per frame, so results are cached and validated against the\n"
H += "        // node's bounding sphere. A node whose sphere ever changes (actors, anything animated)\n"
H += "        // is marked dynamic and permanently falls back to the cheap sphere box - that is the\n"
H += "        // only thing between this and a per-frame full-subtree traversal of the cell.\n"
H += "        const TspBoxEntry& tspEntry(osg::Node* child, const osg::BoundingSphere& bs)\n"
H += "        {\n"
H += "            static std::map<osg::Node*, TspBoxEntry> sCache;\n"
H += "            static TspBoxEntry sFallback;\n"
H += "            if (sCache.size() > 32768)\n"
H += "                sCache.clear();\n"
H += "            std::map<osg::Node*, TspBoxEntry>::iterator it = sCache.find(child);\n"
H += "            if (it != sCache.end())\n"
H += "            {\n"
H += "                if (!it->second.mDynamic && it->second.mRadius == bs.radius()\n"
H += "                    && it->second.mCentre == bs.center())\n"
H += "                    return it->second;\n"
H += "                if (!it->second.mDynamic)\n"
H += "                {\n"
H += "                    it->second.mDynamic = true;\n"
H += "                    ++sTspBoxDyn;\n"
H += "                }\n"
H += "                sFallback = it->second;\n"
H += "                sFallback.mBox = osg::BoundingBox();\n"
H += "                sFallback.mBox.expandBy(bs);\n"
H += "                return sFallback;\n"
H += "            }\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (c.mBoxBudget > 0 && sBoxThisFrame >= c.mBoxBudget)\n"
H += "            {\n"
H += "                ++sBoxDeferred;\n"
H += "                sFallback = TspBoxEntry();\n"
H += "                sFallback.mDynamic = true;\n"
H += "                sFallback.mBox.expandBy(bs);\n"
H += "                return sFallback;\n"
H += "            }\n"
H += "            ++sBoxThisFrame;\n"
H += "            osg::ComputeBoundsVisitor cbv;\n"
H += "            child->accept(cbv);\n"
H += "            TspCountVisitor cnt;\n"
H += "            child->accept(cnt);\n"
H += "            TspBoxEntry e;\n"
H += "            e.mCentre = bs.center();\n"
H += "            e.mRadius = bs.radius();\n"
H += "            e.mBox = cbv.getBoundingBox();\n"
H += "            e.mDrawables = cnt.mCount > 0 ? cnt.mCount : 1;\n"
H += "            e.mDynamic = false;\n"
H += "            if (!e.mBox.valid())\n"
H += "                e.mBox.expandBy(bs);\n"
H += "            ++sTspBoxBuilt;\n"
H += "            sCache[child] = e;\n"
H += "            return sCache[child];\n"
H += "        }\n"
H += "        void tspIntOccBeginFrame(unsigned int frame)\n"
H += "        {\n"
H += "            if (frame == sTspFrame)\n"
H += "                return;\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (sTspFrame != 0xffffffffu && c.mMode >= 1)\n"
H += "            {\n"
H += "                ++sTspFrames;\n"
H += "                if (c.mReportEvery > 0 && (sTspFrames % c.mReportEvery) == 0)\n"
H += "                    Log(Debug::Warning) << \"TSP_INTOCC_V4 f=\" << sTspFrame\n"
H += "                                        << \" p1 tot=\" << sP1Total << \" tst=\" << sP1Tested\n"
H += "                                        << \" cul=\" << sP1Culled\n"
H += "                                        << \" | p2 tot=\" << sP2Total << \" tst=\" << sP2Tested\n"
H += "                                        << \" cul=\" << sP2Culled << \" skip=\" << sP2Skip\n"
H += "                                        << \" | DRAWABLES p1 tot=\" << sP1TotDw << \" cul=\" << sP1CulDw\n"
H += "                                        << \" p2 tot=\" << sP2TotDw << \" cul=\" << sP2CulDw\n"
H += "                                        << \" submitted=\" << (sP1TotDw + sP2TotDw - sP1CulDw - sP2CulDw)\n"
H += "                                        << \" | eyein seen=\" << sEyeSeen << \" rast=\" << sEyeRast\n"
H += "                                        << \" | box built=\" << sTspBoxBuilt << \" dyn=\" << sTspBoxDyn\n"
H += "                                        << \" deferred=\" << sBoxDeferred;\n"
H += "            }\n"
H += "            sTspFrame = frame;\n"
H += "            sBoxThisFrame = 0;\n"
H += "            sBoxDeferred = 0;\n"
H += "            sP1Total = 0;\n"
H += "            sP1Tested = 0;\n"
H += "            sP1Culled = 0;\n"
H += "            sP1TotDw = 0;\n"
H += "            sP1CulDw = 0;\n"
H += "            sP2Total = 0;\n"
H += "            sP2Tested = 0;\n"
H += "            sP2Culled = 0;\n"
H += "            sP2Skip = 0;\n"
H += "            sP2TotDw = 0;\n"
H += "            sP2CulDw = 0;\n"
H += "            sEyeSeen = 0;\n"
H += "            sEyeRast = 0;\n"
H += "            sEyeTris = 0;\n"
H += "        }\n"
H += "        bool tspIntOccAllowInside(int tris)\n"
H += "        {\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            ++sEyeSeen;\n"
H += "            if (c.mEyeIn == 0)\n"
H += "                return false;\n"
H += "            if (c.mMaxTri > 0 && tris > c.mMaxTri)\n"
H += "                return false;\n"
H += "            if (c.mMaxOcc > 0 && sEyeRast >= c.mMaxOcc)\n"
H += "                return false;\n"
H += "            if (c.mBudget > 0 && sEyeTris + tris > c.mBudget)\n"
H += "                return false;\n"
H += "            ++sEyeRast;\n"
H += "            sEyeTris += tris;\n"
H += "            return true;\n"
H += "        }\n"
N1 = A1 + "\n#include <cstdlib>\n#include <map>\n#include <vector>\n#include <osg/ComputeBoundsVisitor>\n#include <osg/NodeVisitor>"
N2 = H + A2
N3 = "        tspIntOccBeginFrame(cv->getTraversalNumber());\n"
N3 += "        std::vector<osg::Node*> tspP1Deferred;\n"
N3 += A3
N4 = "            ++sP1Total;\n"
N4 += "            if (tspIntOccCfg().mMode >= 1)\n"
N4 += "                sP1TotDw += tspEntry(child, bs).mDrawables;\n"
N4 += A4
N5 = "                    const bool tspEyeInside = scaledBB.contains(cv->getEyePoint());\n"
N5 += "                    if (!tspEyeInside\n"
N5 += "                        || tspIntOccAllowInside(static_cast<int>(mesh.indices.size() / 3)))"
N6 = A6 + "\n"
N6 += "            // TSP_INTOCC_V4: in mode 2 the traversal is deferred until every occluder in\n"
N6 += "            // this cell has been rasterised, so child order cannot decide what occludes what.\n"
N6 += "            if (tspIntOccCfg().mMode >= 2)\n"
N6 += "            {\n"
N6 += "                tspP1Deferred.push_back(child);\n"
N6 += "                continue;\n"
N6 += "            }"
N7 = "        // TSP_INTOCC_V4: deferred Pass 1 traversal, tested against the complete buffer.\n"
N7 += "        for (std::size_t tspI = 0; tspI < tspP1Deferred.size(); ++tspI)\n"
N7 += "        {\n"
N7 += "            osg::Node* deferredChild = tspP1Deferred[tspI];\n"
N7 += "            const osg::BoundingSphere& deferredBS = deferredChild->getBound();\n"
N7 += "            const TspBoxEntry& entry = tspEntry(deferredChild, deferredBS);\n"
N7 += "            ++sP1Tested;\n"
N7 += "            if (!mCuller->testVisibleAABB(entry.mBox))\n"
N7 += "            {\n"
N7 += "                ++sP1Culled;\n"
N7 += "                sP1CulDw += entry.mDrawables;\n"
N7 += "                continue;\n"
N7 += "            }\n"
N7 += "            deferredChild->accept(*cv);\n"
N7 += "        }\n"
N7 += A7
N8 = "            ++sP2Total;\n"
N8 += "            bool tspVisible = true;\n"
N8 += "            if (skipOcclusion)\n"
N8 += "                ++sP2Skip;\n"
N8 += "            else\n"
N8 += "            {\n"
N8 += "                ++sP2Tested;\n"
N8 += "                int tspDw = 1;\n"
N8 += "                if (tspIntOccCfg().mMode >= 1)\n"
N8 += "                {\n"
N8 += "                    const TspBoxEntry& entry = tspEntry(child, bs);\n"
N8 += "                    childBB = entry.mBox;\n"
N8 += "                    tspDw = entry.mDrawables;\n"
N8 += "                }\n"
N8 += "                sP2TotDw += tspDw;\n"
N8 += "                tspVisible = mCuller->testVisibleAABB(childBB);\n"
N8 += "                if (!tspVisible)\n"
N8 += "                {\n"
N8 += "                    ++sP2Culled;\n"
N8 += "                    sP2CulDw += tspDw;\n"
N8 += "                }\n"
N8 += "            }\n"
N8 += "            if (tspVisible)"
CTORNEW = "        , mStorage(storage)\n    {\n"
CTORNEW += "        const TspIntOccCfg& tspCfg = tspIntOccCfg();\n"
CTORNEW += "        if (tspCfg.mShrink >= 0.0f)\n"
CTORNEW += "            mOccluderShrinkFactor = tspCfg.mShrink;\n"
CTORNEW += "        if (tspCfg.mInside >= 0.0f)\n"
CTORNEW += "            mOccluderInsideThreshold = tspCfg.mInside;\n"
CTORNEW += "        if (tspCfg.mMinR >= 0.0f)\n"
CTORNEW += "            mOccluderMinRadius = tspCfg.mMinR;\n"
CTORNEW += "        static bool sTspParamsLogged = false;\n"
CTORNEW += "        if (!sTspParamsLogged)\n"
CTORNEW += "        {\n"
CTORNEW += "            sTspParamsLogged = true;\n"
CTORNEW += "            Log(Debug::Warning) << \"TSP_INTOCC_V4 params minRadius=\" << mOccluderMinRadius\n"
CTORNEW += "                                << \" maxRadius=\" << mOccluderMaxRadius\n"
CTORNEW += "                                << \" shrink=\" << mOccluderShrinkFactor\n"
CTORNEW += "                                << \" meshRes=\" << mOccluderMeshResolution\n"
CTORNEW += "                                << \" maxMeshRes=\" << mOccluderMaxMeshResolution\n"
CTORNEW += "                                << \" insideThresh=\" << mOccluderInsideThreshold\n"
CTORNEW += "                                << \" maxDist=\" << std::sqrt(mOccluderMaxDistanceSq)\n"
CTORNEW += "                                << \" staticOcc=\" << (mEnableStaticOccluders ? 1 : 0)\n"
CTORNEW += "                                << \" maxTriangles=\" << mMaxTriangles;\n"
CTORNEW += "        }\n"
CTORNEW += "    }\n\n    const OccluderMesh& CellOcclusionCallback::getOccluderMesh"
out = src
for a, n in ((A1, N1), (A2, N2), (A3, N3), (A4, N4), (A5, N5), (A6, N6), (A7, N7), (A8, N8), (CTOR, CTORNEW)):
    out = out.replace(a, n, 1)
if out.count("{") != out.count("}"):
    print("BRACE IMBALANCE - NOTHING WRITTEN: " + str(out.count("{")) + " vs " + str(out.count("}")))
    sys.exit(1)
if out.count(MARK) < 4:
    print("MARKER CHECK FAILED (" + str(out.count(MARK)) + ") - NOTHING WRITTEN")
    sys.exit(1)
for frag in ("#include <osg/ComputeBoundsVisitor>", "tspP1Deferred.push_back(child)", "sTspParamsLogged", "tspIntOccBeginFrame(cv->getTraversalNumber())", "mOccluderShrinkFactor = tspCfg.mShrink", "sP2CulDw += tspDw", "deferredChild->accept(*cv)"):
    if frag not in out:
        print("REQUIRED FRAGMENT MISSING (" + frag + ") - NOTHING WRITTEN")
        sys.exit(1)
if out.count("tspP1Deferred") != 4:
    print("DEFERRED-LIST WIRING WRONG (" + str(out.count("tspP1Deferred")) + " refs, want 4) - NOTHING WRITTEN")
    sys.exit(1)
open(P, "w", encoding="utf-8").write(out)
print("PATCH APPLIED: " + MARK)
print("  bytes   : " + str(len(src)) + " -> " + str(len(out)))
print("  braces  : " + str(out.count("{")) + " balanced")
print("  markers : " + str(out.count(MARK)))
