# TSP_INTMERGE_V1 patcher - all-or-nothing across 3 files, restore via .before-intmerge-<stamp>
P_ENGINE = []
P_ENGINE.append("    /* ====================== TSP_INTMERGE_V1 ======================")
P_ENGINE.append("       Interior static geometry merging. Interiors get none of the merging that")
P_ENGINE.append("       exterior active-grid ObjectPaging provides (renderingmanager gates paging on")
P_ENGINE.append("       isExterior), so a Caldera-class interior submits ~960 drawables a frame at a")
P_ENGINE.append("       measured ~100 us of CPU each (cull + State::apply + gl4es display-list replay")
P_ENGINE.append("       + light-list churn + driver copies). This builds ONE merged chunk per interior")
P_ENGINE.append("       cell at load, bucketed into room-sized groups so per-area point lighting")
P_ENGINE.append("       survives, and routes the merged refnums through the same mPagedRefs")
P_ENGINE.append("       suppression that exterior active-grid paging already uses in scene.cpp's")
P_ENGINE.append("       addObject. Merged geometry leaves the display-list path entirely (the")
P_ENGINE.append("       optimizer switches it to VBOs).")
P_ENGINE.append("       Correctness model, mirroring active-grid paging:")
P_ENGINE.append("       - only ESM::REC_STAT refs with a content-file refnum are merged; doors,")
P_ENGINE.append("         activators, containers, lights, actors all stay individual.")
P_ENGINE.append("       - templates needing update traversal (animated, NightDay, Herbalism, collada")
P_ENGINE.append("         anims) stay individual - same filter as paging's active grid.")
P_ENGINE.append("       - RefnumMarkers are attached like paging does, so refnum-based lookups on the")
P_ENGINE.append("         merged geometry keep working.")
P_ENGINE.append("       - a moved/deleted ref individuates through Scene::removeFromPagedRefs, which")
P_ENGINE.append("         calls tspIntMergeExcludeRef -> the chunk rebuilds without it.")
P_ENGINE.append("       - scripts that disable/delete a merged static are caught by")
P_ENGINE.append("         tspIntMergeRevalidate (called once per frame from Scene::update): the chunk")
P_ENGINE.append("         rebuilds without them and their refnums leave mPagedRefs, so a later enable")
P_ENGINE.append("         inserts them individually through the normal path.")
P_ENGINE.append("       - the chunk is attached under the cell's \"Cell Root\" on the first")
P_ENGINE.append("         Objects::insertBegin for that cell (every interior has at least a door, so")
P_ENGINE.append("         this always fires), and dies with the cell root on unload.")
P_ENGINE.append("       Env (read once): TSP_INTMERGE=1 arms it (default OFF - one launch A/B),")
P_ENGINE.append("       TSP_INTMERGE_BUCKET=units bucket edge (default 768),")
P_ENGINE.append("       TSP_INTMERGE_MIN=count minimum statics worth merging (default 10). */")
P_ENGINE.append("    namespace")
P_ENGINE.append("    {")
P_ENGINE.append("        struct TspIntMergeEntry")
P_ENGINE.append("        {")
P_ENGINE.append("            ESM::RefNum mRefNum;")
P_ENGINE.append("            const MWWorld::LiveCellRefBase* mLive;")
P_ENGINE.append("        };")
P_ENGINE.append("        struct TspIntMergeCellState")
P_ENGINE.append("        {")
P_ENGINE.append("            osg::ref_ptr<osg::Group> mChunk;")
P_ENGINE.append("            osg::Group* mAttachedTo = nullptr;")
P_ENGINE.append("            std::vector<TspIntMergeEntry> mEntries;")
P_ENGINE.append("            std::set<ESM::RefNum> mExcluded;")
P_ENGINE.append("        };")
P_ENGINE.append("        std::map<const MWWorld::CellStore*, TspIntMergeCellState> sTspIntMergeCells;")
P_ENGINE.append("        int sTspIntMergeMode = -1;")
P_ENGINE.append("        float sTspIntMergeBucket = 768.f;")
P_ENGINE.append("        std::size_t sTspIntMergeMin = 10;")
P_ENGINE.append("        int tspIntMergeMode()")
P_ENGINE.append("        {")
P_ENGINE.append("            if (sTspIntMergeMode < 0)")
P_ENGINE.append("            {")
P_ENGINE.append("                const char* e = std::getenv(\"TSP_INTMERGE\");")
P_ENGINE.append("                sTspIntMergeMode = (e != nullptr && e[0] != 0 && e[0] != '0') ? 1 : 0;")
P_ENGINE.append("                const char* b = std::getenv(\"TSP_INTMERGE_BUCKET\");")
P_ENGINE.append("                if (b != nullptr && std::atof(b) > 0.0)")
P_ENGINE.append("                    sTspIntMergeBucket = static_cast<float>(std::atof(b));")
P_ENGINE.append("                const char* m = std::getenv(\"TSP_INTMERGE_MIN\");")
P_ENGINE.append("                if (m != nullptr && std::atoi(m) > 0)")
P_ENGINE.append("                    sTspIntMergeMin = static_cast<std::size_t>(std::atoi(m));")
P_ENGINE.append("                Log(Debug::Warning) << \"TSP_INTMERGE_V1 mode=\" << sTspIntMergeMode << \" bucket=\" << sTspIntMergeBucket")
P_ENGINE.append("                                    << \" min=\" << sTspIntMergeMin << \" (TSP_INTMERGE=1 arms interior static merging)\";")
P_ENGINE.append("            }")
P_ENGINE.append("            return sTspIntMergeMode;")
P_ENGINE.append("        }")
P_ENGINE.append("        struct TspIntMergeCounter : public osg::NodeVisitor")
P_ENGINE.append("        {")
P_ENGINE.append("            TspIntMergeCounter()")
P_ENGINE.append("                : osg::NodeVisitor(TRAVERSE_ALL_CHILDREN)")
P_ENGINE.append("            {")
P_ENGINE.append("                setNodeMaskOverride(~0u);")
P_ENGINE.append("            }")
P_ENGINE.append("            unsigned int mDrawables = 0;")
P_ENGINE.append("            std::set<const osg::StateSet*> mStateSets;")
P_ENGINE.append("            void apply(osg::Drawable& drawable) override")
P_ENGINE.append("            {")
P_ENGINE.append("                ++mDrawables;")
P_ENGINE.append("                if (drawable.getStateSet() != nullptr)")
P_ENGINE.append("                    mStateSets.insert(drawable.getStateSet());")
P_ENGINE.append("            }")
P_ENGINE.append("        };")
P_ENGINE.append("        struct TspIntMergeCollector")
P_ENGINE.append("        {")
P_ENGINE.append("            std::vector<MWWorld::Ptr> mStatics;")
P_ENGINE.append("            bool operator()(const MWWorld::Ptr& ptr)")
P_ENGINE.append("            {")
P_ENGINE.append("                if (ptr.getType() == ESM::REC_STAT && !ptr.mRef->isDeleted() && ptr.getRefData().isEnabled()")
P_ENGINE.append("                    && ptr.getCellRef().getRefNum().hasContentFile())")
P_ENGINE.append("                    mStatics.push_back(ptr);")
P_ENGINE.append("                return true;")
P_ENGINE.append("            }")
P_ENGINE.append("        };")
P_ENGINE.append("        osg::ref_ptr<osg::Group> tspIntMergeBuildChunk(MWWorld::CellStore& cell, const std::set<ESM::RefNum>& excluded,")
P_ENGINE.append("            std::vector<TspIntMergeEntry>& outEntries)")
P_ENGINE.append("        {")
P_ENGINE.append("            outEntries.clear();")
P_ENGINE.append("            Resource::SceneManager* sceneManager")
P_ENGINE.append("                = MWBase::Environment::get().getResourceSystem()->getSceneManager();")
P_ENGINE.append("            const MWWorld::ESMStore& store = MWBase::Environment::get().getWorld()->getStore();")
P_ENGINE.append("            TspIntMergeCollector collector;")
P_ENGINE.append("            cell.forEach(collector, false);")
P_ENGINE.append("            std::size_t skipAnim = 0;")
P_ENGINE.append("            std::size_t skipMarker = 0;")
P_ENGINE.append("            std::size_t skipExcluded = 0;")
P_ENGINE.append("            std::size_t skipFailed = 0;")
P_ENGINE.append("            unsigned int drawablesBefore = 0;")
P_ENGINE.append("            constexpr osg::Node::NodeMask tspCopyMask = ~Mask_UpdateVisitor;")
P_ENGINE.append("            CopyOp copyop(true, tspCopyMask);")
P_ENGINE.append("            copyop.mOptimizeBillboards = false;")
P_ENGINE.append("            copyop.mDistances = { 0.f, 1.f };")
P_ENGINE.append("            osg::ref_ptr<Resource::TemplateMultiRef> templateRefs = new Resource::TemplateMultiRef;")
P_ENGINE.append("            std::map<const osg::Node*, unsigned int> templateDrawables;")
P_ENGINE.append("            typedef std::map<std::tuple<int, int, int>, osg::ref_ptr<osg::Group>> TspBucketMap;")
P_ENGINE.append("            TspBucketMap buckets;")
P_ENGINE.append("            for (const MWWorld::Ptr& ptr : collector.mStatics)")
P_ENGINE.append("            {")
P_ENGINE.append("                const ESM::RefNum refnum = ptr.getCellRef().getRefNum();")
P_ENGINE.append("                if (excluded.count(refnum) > 0)")
P_ENGINE.append("                {")
P_ENGINE.append("                    ++skipExcluded;")
P_ENGINE.append("                    continue;")
P_ENGINE.append("                }")
P_ENGINE.append("                const ESM::RefId refId = ptr.getCellRef().getRefId();")
P_ENGINE.append("                if (Misc::ResourceHelpers::isHiddenMarker(refId))")
P_ENGINE.append("                {")
P_ENGINE.append("                    ++skipMarker;")
P_ENGINE.append("                    continue;")
P_ENGINE.append("                }")
P_ENGINE.append("                try")
P_ENGINE.append("                {")
P_ENGINE.append("                    VFS::Path::Normalized model(getModel(ESM::REC_STAT, refId, store));")
P_ENGINE.append("                    if (model.empty())")
P_ENGINE.append("                    {")
P_ENGINE.append("                        ++skipMarker;")
P_ENGINE.append("                        continue;")
P_ENGINE.append("                    }")
P_ENGINE.append("                    model = Misc::ResourceHelpers::correctMeshPath(model);")
P_ENGINE.append("                    osg::ref_ptr<const osg::Node> cnode = sceneManager->getTemplate(model, false);")
P_ENGINE.append("                    if (cnode->getNumChildrenRequiringUpdateTraversal() > 0")
P_ENGINE.append("                        || SceneUtil::hasUserDescription(cnode, Constants::NightDayLabel)")
P_ENGINE.append("                        || SceneUtil::hasUserDescription(cnode, Constants::HerbalismLabel)")
P_ENGINE.append("                        || (cnode->getName() == \"Collada visual scene group\"")
P_ENGINE.append("                            && dynamic_cast<const osgAnimation::BasicAnimationManager*>(cnode->getUpdateCallback())))")
P_ENGINE.append("                    {")
P_ENGINE.append("                        ++skipAnim;")
P_ENGINE.append("                        continue;")
P_ENGINE.append("                    }")
P_ENGINE.append("                    const ESM::Position& refPos = ptr.getRefData().getPosition();")
P_ENGINE.append("                    const float scale = ptr.getCellRef().getScale();")
P_ENGINE.append("                    const osg::Vec3f nodePos(refPos.pos[0], refPos.pos[1], refPos.pos[2]);")
P_ENGINE.append("                    const osg::Quat nodeAttitude = osg::Quat(refPos.rot[2], osg::Vec3f(0, 0, -1))")
P_ENGINE.append("                        * osg::Quat(refPos.rot[1], osg::Vec3f(0, -1, 0)) * osg::Quat(refPos.rot[0], osg::Vec3f(-1, 0, 0));")
P_ENGINE.append("                    osg::Matrixf matrix;")
P_ENGINE.append("                    matrix.preMultTranslate(nodePos);")
P_ENGINE.append("                    matrix.preMultRotate(nodeAttitude);")
P_ENGINE.append("                    matrix.preMultScale(osg::Vec3f(scale, scale, scale));")
P_ENGINE.append("                    osg::ref_ptr<osg::MatrixTransform> trans = new osg::MatrixTransform(matrix);")
P_ENGINE.append("                    trans->setDataVariance(osg::Object::STATIC);")
P_ENGINE.append("                    /* Same shallow-array cloning contract as ObjectPaging::createChunk above:")
P_ENGINE.append("                       safe ONLY because templateRefs keeps every source template alive and")
P_ENGINE.append("                       needvbo() in optimizer.cpp forbids reusing the originals' BufferObjects. */")
P_ENGINE.append("                    copyop.setCopyFlags(osg::CopyOp::DEEP_COPY_NODES | osg::CopyOp::DEEP_COPY_DRAWABLES);")
P_ENGINE.append("                    copyop.mNodePath.push_back(trans);")
P_ENGINE.append("                    copyop.copy(cnode, trans);")
P_ENGINE.append("                    copyop.mNodePath.pop_back();")
P_ENGINE.append("                    AddRefnumMarkerVisitor marker(refnum);")
P_ENGINE.append("                    trans->accept(marker);")
P_ENGINE.append("                    std::map<const osg::Node*, unsigned int>::iterator known = templateDrawables.find(cnode.get());")
P_ENGINE.append("                    if (known == templateDrawables.end())")
P_ENGINE.append("                    {")
P_ENGINE.append("                        TspIntMergeCounter counter;")
P_ENGINE.append("                        const_cast<osg::Node*>(cnode.get())->accept(counter);")
P_ENGINE.append("                        known = templateDrawables.emplace(cnode.get(), counter.mDrawables).first;")
P_ENGINE.append("                        templateRefs->addRef(cnode.get());")
P_ENGINE.append("                    }")
P_ENGINE.append("                    drawablesBefore += known->second;")
P_ENGINE.append("                    const float b = sTspIntMergeBucket;")
P_ENGINE.append("                    const std::tuple<int, int, int> key(static_cast<int>(std::floor(nodePos.x() / b)),")
P_ENGINE.append("                        static_cast<int>(std::floor(nodePos.y() / b)), static_cast<int>(std::floor(nodePos.z() / b)));")
P_ENGINE.append("                    osg::ref_ptr<osg::Group>& bucket = buckets[key];")
P_ENGINE.append("                    if (!bucket)")
P_ENGINE.append("                        bucket = new osg::Group;")
P_ENGINE.append("                    bucket->addChild(trans);")
P_ENGINE.append("                    outEntries.push_back(TspIntMergeEntry{ refnum, ptr.mRef });")
P_ENGINE.append("                }")
P_ENGINE.append("                catch (const std::exception& e)")
P_ENGINE.append("                {")
P_ENGINE.append("                    ++skipFailed;")
P_ENGINE.append("                    Log(Debug::Warning) << \"TSP_INTMERGE_V1 skipped '\" << refId << \"': \" << e.what();")
P_ENGINE.append("                }")
P_ENGINE.append("            }")
P_ENGINE.append("            if (outEntries.size() < sTspIntMergeMin)")
P_ENGINE.append("            {")
P_ENGINE.append("                Log(Debug::Warning) << \"TSP_INTMERGE_V1 cell '\" << cell.getCell()->getDescription()")
P_ENGINE.append("                                    << \"' not merged: only \" << outEntries.size() << \" mergeable statics (min \"")
P_ENGINE.append("                                    << sTspIntMergeMin << \"), skipAnim=\" << skipAnim << \" skipMarker=\" << skipMarker;")
P_ENGINE.append("                outEntries.clear();")
P_ENGINE.append("                return nullptr;")
P_ENGINE.append("            }")
P_ENGINE.append("            osg::ref_ptr<osg::Group> chunk = new osg::Group;")
P_ENGINE.append("            chunk->setName(\"TSP_INTMERGE_CHUNK\");")
P_ENGINE.append("            chunk->setNodeMask(Mask_Object);")
P_ENGINE.append("            for (TspBucketMap::iterator it = buckets.begin(); it != buckets.end(); ++it)")
P_ENGINE.append("            {")
P_ENGINE.append("                SceneUtil::Optimizer optimizer;")
P_ENGINE.append("                optimizer.setIsOperationPermissibleForObjectCallback(new CanOptimizeCallback);")
P_ENGINE.append("                const unsigned int options = SceneUtil::Optimizer::FLATTEN_STATIC_TRANSFORMS")
P_ENGINE.append("                    | SceneUtil::Optimizer::REMOVE_REDUNDANT_NODES | SceneUtil::Optimizer::MERGE_GEOMETRY;")
P_ENGINE.append("                optimizer.optimize(it->second, options);")
P_ENGINE.append("                it->second->addCullCallback(new SceneUtil::LightListCallback);")
P_ENGINE.append("                it->second->getBound();")
P_ENGINE.append("                chunk->addChild(it->second);")
P_ENGINE.append("            }")
P_ENGINE.append("            chunk->getOrCreateUserDataContainer()->addUserObject(templateRefs);")
P_ENGINE.append("            chunk->getBound();")
P_ENGINE.append("            std::sort(outEntries.begin(), outEntries.end(),")
P_ENGINE.append("                [](const TspIntMergeEntry& l, const TspIntMergeEntry& r) { return l.mRefNum < r.mRefNum; });")
P_ENGINE.append("            TspIntMergeCounter after;")
P_ENGINE.append("            chunk->accept(after);")
P_ENGINE.append("            Log(Debug::Warning) << \"TSP_INTMERGE_V1 cell '\" << cell.getCell()->getDescription() << \"' statics=\"")
P_ENGINE.append("                                << collector.mStatics.size() << \" merged=\" << outEntries.size() << \" skipAnim=\"")
P_ENGINE.append("                                << skipAnim << \" skipMarker=\" << skipMarker << \" skipExcluded=\" << skipExcluded")
P_ENGINE.append("                                << \" skipFailed=\" << skipFailed << \" buckets=\" << buckets.size() << \" drawables \"")
P_ENGINE.append("                                << drawablesBefore << \" -> \" << after.mDrawables << \" statesets=\" << after.mStateSets.size();")
P_ENGINE.append("            return chunk;")
P_ENGINE.append("        }")
P_ENGINE.append("        void tspIntMergeRebuild(const MWWorld::CellStore* cell, TspIntMergeCellState& state)")
P_ENGINE.append("        {")
P_ENGINE.append("            if (state.mAttachedTo != nullptr && state.mChunk.valid())")
P_ENGINE.append("                state.mAttachedTo->removeChild(state.mChunk);")
P_ENGINE.append("            state.mChunk = tspIntMergeBuildChunk(*const_cast<MWWorld::CellStore*>(cell), state.mExcluded, state.mEntries);")
P_ENGINE.append("            if (state.mChunk.valid() && state.mAttachedTo != nullptr)")
P_ENGINE.append("                state.mAttachedTo->addChild(state.mChunk);")
P_ENGINE.append("        }")
P_ENGINE.append("    }")
P_ENGINE.append("")
P_ENGINE.append("    bool tspIntMergeEnabled()")
P_ENGINE.append("    {")
P_ENGINE.append("        return tspIntMergeMode() != 0;")
P_ENGINE.append("    }")
P_ENGINE.append("")
P_ENGINE.append("    std::size_t tspIntMergeBuildCell(MWWorld::CellStore& cell, std::vector<ESM::RefNum>& outPagedRefs)")
P_ENGINE.append("    {")
P_ENGINE.append("        outPagedRefs.clear();")
P_ENGINE.append("        if (tspIntMergeMode() == 0)")
P_ENGINE.append("            return 0;")
P_ENGINE.append("        sTspIntMergeCells.erase(&cell);")
P_ENGINE.append("        TspIntMergeCellState state;")
P_ENGINE.append("        state.mChunk = tspIntMergeBuildChunk(cell, state.mExcluded, state.mEntries);")
P_ENGINE.append("        if (!state.mChunk.valid())")
P_ENGINE.append("            return 0;")
P_ENGINE.append("        outPagedRefs.reserve(state.mEntries.size());")
P_ENGINE.append("        for (const TspIntMergeEntry& entry : state.mEntries)")
P_ENGINE.append("            outPagedRefs.push_back(entry.mRefNum);")
P_ENGINE.append("        const std::size_t count = state.mEntries.size();")
P_ENGINE.append("        sTspIntMergeCells.emplace(&cell, std::move(state));")
P_ENGINE.append("        return count;")
P_ENGINE.append("    }")
P_ENGINE.append("")
P_ENGINE.append("    void tspIntMergeNoteCellRoot(const MWWorld::CellStore* cell, osg::Group* root)")
P_ENGINE.append("    {")
P_ENGINE.append("        if (sTspIntMergeMode != 1 || root == nullptr)")
P_ENGINE.append("            return;")
P_ENGINE.append("        std::map<const MWWorld::CellStore*, TspIntMergeCellState>::iterator it = sTspIntMergeCells.find(cell);")
P_ENGINE.append("        if (it == sTspIntMergeCells.end() || it->second.mAttachedTo != nullptr || !it->second.mChunk.valid())")
P_ENGINE.append("            return;")
P_ENGINE.append("        root->addChild(it->second.mChunk);")
P_ENGINE.append("        it->second.mAttachedTo = root;")
P_ENGINE.append("        Log(Debug::Warning) << \"TSP_INTMERGE_V1 chunk attached under the cell root (\"")
P_ENGINE.append("                            << it->second.mEntries.size() << \" merged statics)\";")
P_ENGINE.append("    }")
P_ENGINE.append("")
P_ENGINE.append("    void tspIntMergeCellUnloaded(const MWWorld::CellStore* cell)")
P_ENGINE.append("    {")
P_ENGINE.append("        sTspIntMergeCells.erase(cell);")
P_ENGINE.append("    }")
P_ENGINE.append("")
P_ENGINE.append("    bool tspIntMergeExcludeRef(const MWWorld::CellStore* cell, ESM::RefNum refnum)")
P_ENGINE.append("    {")
P_ENGINE.append("        std::map<const MWWorld::CellStore*, TspIntMergeCellState>::iterator it = sTspIntMergeCells.find(cell);")
P_ENGINE.append("        if (it == sTspIntMergeCells.end())")
P_ENGINE.append("            return false;")
P_ENGINE.append("        if (!it->second.mExcluded.insert(refnum).second)")
P_ENGINE.append("            return false;")
P_ENGINE.append("        Log(Debug::Warning) << \"TSP_INTMERGE_V1 ref individuated (moved/removed) - rebuilding the cell chunk\";")
P_ENGINE.append("        tspIntMergeRebuild(cell, it->second);")
P_ENGINE.append("        return true;")
P_ENGINE.append("    }")
P_ENGINE.append("")
P_ENGINE.append("    void tspIntMergeRevalidate(std::vector<ESM::RefNum>& outUnpaged)")
P_ENGINE.append("    {")
P_ENGINE.append("        outUnpaged.clear();")
P_ENGINE.append("        if (sTspIntMergeMode != 1 || sTspIntMergeCells.empty())")
P_ENGINE.append("            return;")
P_ENGINE.append("        for (std::map<const MWWorld::CellStore*, TspIntMergeCellState>::iterator it = sTspIntMergeCells.begin();")
P_ENGINE.append("             it != sTspIntMergeCells.end(); ++it)")
P_ENGINE.append("        {")
P_ENGINE.append("            std::vector<ESM::RefNum> gone;")
P_ENGINE.append("            for (const TspIntMergeEntry& entry : it->second.mEntries)")
P_ENGINE.append("                if (entry.mLive->isDeleted() || !entry.mLive->mData.isEnabled())")
P_ENGINE.append("                    gone.push_back(entry.mRefNum);")
P_ENGINE.append("            if (gone.empty())")
P_ENGINE.append("                continue;")
P_ENGINE.append("            Log(Debug::Warning) << \"TSP_INTMERGE_V1 revalidate: \" << gone.size()")
P_ENGINE.append("                                << \" merged static(s) were disabled or deleted by a script - rebuilding the chunk\";")
P_ENGINE.append("            for (ESM::RefNum g : gone)")
P_ENGINE.append("                it->second.mExcluded.insert(g);")
P_ENGINE.append("            tspIntMergeRebuild(it->first, it->second);")
P_ENGINE.append("            outUnpaged.insert(outUnpaged.end(), gone.begin(), gone.end());")
P_ENGINE.append("        }")
P_ENGINE.append("    }")
P_ENGINE.append("    /* ==================== end TSP_INTMERGE_V1 ==================== */")
P_SC_DECLS = []
P_SC_DECLS.append("// TSP_INTMERGE_V1 - interior static merging, implemented at the end of")
P_SC_DECLS.append("// mwrender/objectpaging.cpp so it can reuse ObjectPaging's CopyOp/AnalyzeVisitor/")
P_SC_DECLS.append("// CanOptimizeCallback machinery. Declared here to avoid a header edit.")
P_SC_DECLS.append("namespace MWRender")
P_SC_DECLS.append("{")
P_SC_DECLS.append("    bool tspIntMergeEnabled();")
P_SC_DECLS.append("    std::size_t tspIntMergeBuildCell(MWWorld::CellStore& cell, std::vector<ESM::RefNum>& outPagedRefs);")
P_SC_DECLS.append("    bool tspIntMergeExcludeRef(const MWWorld::CellStore* cell, ESM::RefNum refnum);")
P_SC_DECLS.append("    void tspIntMergeRevalidate(std::vector<ESM::RefNum>& outUnpaged);")
P_SC_DECLS.append("}")
P_SC_LOAD = []
P_SC_LOAD.append("        /* TSP_INTMERGE_V1 - build one merged chunk for this interior's statics BEFORE")
P_SC_LOAD.append("           the per-object insertion below, and route the merged refnums through the")
P_SC_LOAD.append("           same mPagedRefs suppression that exterior active-grid paging uses:")
P_SC_LOAD.append("           addObject() binary-searches mPagedRefs and parks suppressed refs on")
P_SC_LOAD.append("           pagedNode, so they get physics and scripts but no individual render")
P_SC_LOAD.append("           object. The chunk itself is attached under the cell's \"Cell Root\" by")
P_SC_LOAD.append("           Objects::insertBegin via tspIntMergeNoteCellRoot. Interiors have exactly")
P_SC_LOAD.append("           one active cell, so clearing mPagedRefs here is safe (exteriors refill it")
P_SC_LOAD.append("           on their own path). */")
P_SC_LOAD.append("        if (!cellVariant.isExterior())")
P_SC_LOAD.append("        {")
P_SC_LOAD.append("            mPagedRefs.clear();")
P_SC_LOAD.append("            if (MWRender::tspIntMergeEnabled())")
P_SC_LOAD.append("                MWRender::tspIntMergeBuildCell(cell, mPagedRefs);")
P_SC_LOAD.append("        }")
P_SC_RFPR = []
P_SC_RFPR.append("        /* TSP_INTMERGE_V1 - interior branch. A merged interior ref that must")
P_SC_RFPR.append("           individuate (moved, deleted, picked apart by a script) leaves the chunk")
P_SC_RFPR.append("           here: the chunk rebuilds without it, then it is re-inserted individually")
P_SC_RFPR.append("           exactly like the exterior path below - but without reloadTerrain(), which")
P_SC_RFPR.append("           has no meaning for an interior. */")
P_SC_RFPR.append("        if (ptr.getCell() != nullptr && !ptr.getCell()->getCell()->isExterior())")
P_SC_RFPR.append("        {")
P_SC_RFPR.append("            if (refnum.hasContentFile() && removeFromSorted(refnum, mPagedRefs))")
P_SC_RFPR.append("            {")
P_SC_RFPR.append("                MWRender::tspIntMergeExcludeRef(ptr.getCell(), refnum);")
P_SC_RFPR.append("                if (!ptr.getRefData().getBaseNode())")
P_SC_RFPR.append("                    return;")
P_SC_RFPR.append("                ptr.getClass().insertObjectRendering(ptr, getModel(ptr), mRendering);")
P_SC_RFPR.append("                setNodeRotation(ptr, mRendering, makeNodeRotation(ptr, RotationOrder::direct));")
P_SC_RFPR.append("            }")
P_SC_RFPR.append("            return;")
P_SC_RFPR.append("        }")
P_SC_UPD = []
P_SC_UPD.append("        /* TSP_INTMERGE_V1 - once per frame, drop merged statics that scripts have")
P_SC_UPD.append("           disabled or deleted since the chunk was built (the chunk rebuilds without")
P_SC_UPD.append("           them). Their refnums leave mPagedRefs so a later enable inserts them")
P_SC_UPD.append("           individually through the normal path. Costs a few hundred flag reads per")
P_SC_UPD.append("           frame; does nothing unless TSP_INTMERGE=1 and an interior is active. */")
P_SC_UPD.append("        {")
P_SC_UPD.append("            static std::vector<ESM::RefNum> tspUnpaged;")
P_SC_UPD.append("            MWRender::tspIntMergeRevalidate(tspUnpaged);")
P_SC_UPD.append("            for (ESM::RefNum tspRef : tspUnpaged)")
P_SC_UPD.append("                removeFromSorted(tspRef, mPagedRefs);")
P_SC_UPD.append("        }")
P_OB_DECLS = []
P_OB_DECLS.append("    // TSP_INTMERGE_V1 - defined at the end of objectpaging.cpp. insertBegin tells")
P_OB_DECLS.append("    // the interior merger about each cell root so the pre-built merged chunk can be")
P_OB_DECLS.append("    // attached under it; removeCell drops the registry entry with the cell.")
P_OB_DECLS.append("    void tspIntMergeNoteCellRoot(const MWWorld::CellStore* cell, osg::Group* root);")
P_OB_DECLS.append("    void tspIntMergeCellUnloaded(const MWWorld::CellStore* cell);")
P_OB_NOTE = []
P_OB_NOTE.append("        tspIntMergeNoteCellRoot(ptr.getCell(), cellnode.get()); // TSP_INTMERGE_V1")
P_OB_UNLOAD = []
P_OB_UNLOAD.append("        tspIntMergeCellUnloaded(store); // TSP_INTMERGE_V1")
import sys
import time
SRC = "/root/openmw-0.51-tsp-src"
if len(sys.argv) > 1:
    SRC = sys.argv[1]
MARK = "TSP_INTMERGE_V1"
STAMP = time.strftime("%Y%m%d-%H%M%S")
F_PP = SRC + "/apps/openmw/mwrender/objectpaging.cpp"
F_SC = SRC + "/apps/openmw/mwworld/scene.cpp"
F_OB = SRC + "/apps/openmw/mwrender/objects.cpp"
INC_NEW = []
INC_NEW.append("#include \"apps/openmw/mwworld/cellstore.hpp\"")
INC_NEW.append("#include \"apps/openmw/mwworld/ptr.hpp\"")
INC_NEW.append("#include <components/resource/resourcesystem.hpp>")
INC_NEW.append("#include <cstdlib>")
def rd(p):
    return open(p, encoding="utf-8", errors="replace").read()
def survey(name, lines, pats):
    print("--- survey of " + name + " ---")
    shown = 0
    for i, l in enumerate(lines, 1):
        if any(p in l for p in pats):
            print("  %5d| %s" % (i, l[:150]))
            shown += 1
            if shown >= 40:
                print("  ... capped at 40")
                break
texts = {}
for f in (F_PP, F_SC, F_OB):
    try:
        texts[f] = rd(f)
    except OSError as e:
        print("GATE FAIL: cannot read " + f + ": " + str(e))
        sys.exit(1)
marked = [f for f in texts if MARK in texts[f]]
if len(marked) == 3:
    print("ALREADY APPLIED: " + MARK + " present in all three files. Nothing written.")
    sys.exit(0)
if marked:
    print("GATE FAIL: " + MARK + " present in " + str(len(marked)) + " of 3 files - partial state, refusing:")
    for f in marked:
        print("  " + f)
    sys.exit(1)
fail = []
def one(name, lines, needle, what):
    hits = [i for i, l in enumerate(lines) if l == needle]
    if len(hits) != 1:
        fail.append(name + ": anchor " + what + " matched " + str(len(hits)) + " lines, want 1: " + repr(needle[:80]))
        return -1
    return hits[0]
pp = texts[F_PP].split("\n")
sc = texts[F_SC].split("\n")
ob = texts[F_OB].split("\n")
A_INC = one("objectpaging", pp, "#include \"apps/openmw/mwworld/esmstore.hpp\"", "esmstore include")
A_END = one("objectpaging", pp, "        Resource::reportStats(\"Object Chunk\", frameNumber, mCache->getStats(), *stats);", "reportStats line")
pp_close = -1
for i in range(len(pp) - 1, -1, -1):
    if pp[i] == "}":
        pp_close = i
        break
if pp_close < 0:
    fail.append("objectpaging: no closing namespace brace found")
if A_END >= 0 and pp_close >= 0:
    between = [l for l in pp[A_END + 1 : pp_close] if l.strip() not in ("", "}")]
    if between:
        fail.append("objectpaging: unexpected code between reportStats and the final brace: " + repr(between[:3]))
for need in ("bool typeFilter(int type, bool far)", "class CanOptimizeCallback", "class AddRefnumMarkerVisitor", "class CopyOp : public osg::CopyOp", "Terrain::QuadTreeWorld::ChunkManager"):
    if need not in texts[F_PP]:
        fail.append("objectpaging: required machinery missing: " + repr(need))
A_TAG = one("scene", sc, "    // TSP_SCENE_V2 build tag - volatile so it reaches the binary and \"grep -a\"", "TSP_SCENE_V2 comment")
if A_TAG >= 0:
    if A_TAG < 2 or sc[A_TAG - 2] != "namespace MWWorld" or sc[A_TAG - 1] != "{":
        fail.append("scene: TSP_SCENE_V2 comment not directly inside 'namespace MWWorld {' as expected")
A_LOAD = one("scene", sc, "        // register local scripts", "register-local-scripts comment")
A_RFPR = one("scene", sc, "    void Scene::removeFromPagedRefs(const Ptr& ptr)", "removeFromPagedRefs signature")
if A_RFPR >= 0:
    if sc[A_RFPR + 1] != "    {" or sc[A_RFPR + 2].strip() != "ESM::RefNum refnum = ptr.getCellRef().getRefNum();":
        fail.append("scene: removeFromPagedRefs body does not open as expected")
A_UPD = one("scene", sc, "    void Scene::update(float duration)", "Scene::update signature")
if A_UPD >= 0 and sc[A_UPD + 1] != "    {":
    fail.append("scene: Scene::update body does not open with '    {'")
for need in ("bool removeFromSorted(ESM::RefNum refNum, std::vector<ESM::RefNum>& pagedRefs)", "std::vector<ESM::RefNum>& pagedRefs"):
    if need not in texts[F_SC]:
        fail.append("scene: removeFromSorted helper missing")
        break
A_OBC = one("objects", ob, "    Objects::Objects(Resource::ResourceSystem* resourceSystem, const osg::ref_ptr<osg::Group>& rootNode,", "Objects ctor")
A_OBN = one("objects", ob, "        osg::ref_ptr<SceneUtil::PositionAttitudeTransform> insert(new SceneUtil::PositionAttitudeTransform);", "insertBegin PAT line")
A_OBU = one("objects", ob, "        CellMap::iterator cell = mCellSceneNodes.find(store);", "removeCell find line")
if fail:
    print("ANCHOR FAILURE - NOTHING WRITTEN")
    for f in fail:
        print("  " + f)
    survey("objectpaging.cpp", pp, ["reportStats", "#include \"apps", "typeFilter", "CanOptimizeCallback"])
    survey("scene.cpp", sc, ["TSP_SCENE_V2", "register local", "removeFromPagedRefs", "void Scene::update", "removeFromSorted"])
    survey("objects.cpp", ob, ["Objects::Objects", "PositionAttitudeTransform> insert", "mCellSceneNodes.find"])
    sys.exit(1)
out_pp = list(pp)
out_pp[pp_close:pp_close] = P_ENGINE
out_pp[A_INC + 1 : A_INC + 1] = INC_NEW
out_sc = list(sc)
for idx, block in sorted(((A_UPD + 2, P_SC_UPD), (A_LOAD, P_SC_LOAD), (A_RFPR + 3, P_SC_RFPR), (A_TAG - 2, P_SC_DECLS)), reverse=True):
    out_sc[idx:idx] = block
out_ob = list(ob)
for idx, block in sorted(((A_OBU, P_OB_UNLOAD), (A_OBN, P_OB_NOTE), (A_OBC, P_OB_DECLS)), reverse=True):
    out_ob[idx:idx] = block
results = ((F_PP, pp, out_pp), (F_SC, sc, out_sc), (F_OB, ob, out_ob))
for f, old, new in results:
    res = "\n".join(new)
    if res.count("{") != res.count("}"):
        print("BRACE IMBALANCE in " + f + " - NOTHING WRITTEN: " + str(res.count("{")) + " vs " + str(res.count("}")))
        sys.exit(1)
    if res.count("(") != res.count(")"):
        print("PAREN IMBALANCE in " + f + " - NOTHING WRITTEN")
        sys.exit(1)
    if MARK not in res:
        print("MARKER MISSING from patched " + f + " - NOTHING WRITTEN")
        sys.exit(1)
frags = (("tspIntMergeBuildCell(", "".join(texts[F_PP])), )
for frag, where in (("std::size_t tspIntMergeBuildCell(MWWorld::CellStore& cell", "\n".join(out_pp)), ("MWRender::tspIntMergeBuildCell(cell, mPagedRefs)", "\n".join(out_sc)), ("tspIntMergeNoteCellRoot(ptr.getCell(), cellnode.get())", "\n".join(out_ob)), ("tspIntMergeRevalidate", "\n".join(out_sc))):
    if frag not in where:
        print("REQUIRED FRAGMENT MISSING (" + frag + ") - NOTHING WRITTEN")
        sys.exit(1)
for f, old, new in results:
    bp = f + ".before-intmerge-" + STAMP
    open(bp, "w", encoding="utf-8").write(texts[f])
    if rd(bp) != texts[f]:
        print("GATE FAIL: backup readback mismatch at " + bp + " - NOTHING WRITTEN")
        sys.exit(1)
for f, old, new in results:
    open(f, "w", encoding="utf-8").write("\n".join(new))
    print("PATCHED " + f + " : " + str(len(old)) + " -> " + str(len(new)) + " lines (backup .before-intmerge-" + STAMP + ")")
print("PATCH APPLIED: " + MARK)
