import sys
P = "/root/openmw-0.51-tsp-src/apps/openmw/mwrender/occlusionculling.cpp"
if len(sys.argv) > 1:
    P = sys.argv[1]
MARK = "TSP_INTOCC_V5"
src = open(P, encoding="utf-8").read()
if MARK in src:
    print("ALREADY APPLIED: " + MARK + " present. Nothing written.")
    sys.exit(0)
for old in ("TSP_INTOCC_V1", "TSP_INTOCC_V2", "TSP_INTOCC_V3", "TSP_INTOCC_V4"):
    if old in src:
        print("REFUSING: file still carries " + old + ". Restore the pristine backup first.")
        sys.exit(1)
A1 = "#include <cmath>"
A2 = "        std::string_view getModelPathForNode(osg::Node* node)"
A3 = "        const unsigned int numChildren = node->getNumChildren();"
A4 = "            const OccluderMesh& mesh = getOccluderMesh(child);"
A5 = "                    if (!scaledBB.contains(cv->getEyePoint()))"
A6 = "            // is reserved for culling small objects in Pass 2."
A7 = "        // Pass 2: Small objects"
A8 = "            if (skipOcclusion || mCuller->testVisibleAABB(childBB))"
CTOR = "        , mStorage(storage)\n    {\n    }\n\n    const OccluderMesh& CellOcclusionCallback::getOccluderMesh"
fail = []
for nm, a in (("A1", A1), ("A2", A2), ("A3", A3), ("A4", A4), ("A5", A5), ("A6", A6), ("A7", A7), ("A8", A8), ("CTOR", CTOR)):
    n = src.count(a)
    if n != 1:
        fail.append(nm + " matched " + str(n) + " times: " + repr(a[:70]))
if fail:
    print("ANCHOR FAILURE - NOTHING WRITTEN")
    for f in fail:
        print("  " + f)
    print("--- survey ---")
    for i, l in enumerate(src.split("\n"), 1):
        if ("scaledBB" in l) or ("getModelPathForNode" in l) or ("cmath" in l) or ("numChildren" in l) or ("getOccluderMesh(child)" in l) or ("skipOcclusion" in l) or ("mStorage(storage)" in l) or ("Pass 2" in l):
            print("  %5d| %s" % (i, l))
    sys.exit(1)
H = ""
H += "        // TSP_INTOCC_V5 - proper interior occlusion culling.\n"
H += "        //\n"
H += "        // What V1-V4 measured, so this is not guesswork:\n"
H += "        //   params  minRadius=400 maxRadius=5000 shrink=1 meshRes=7 maxMeshRes=24\n"
H += "        //           insideThresh=1 maxDist=6144 maxTriangles=30000 (4679 in use)\n"
H += "        //   V4 mode2 p1 tot=29 tst=29 cul=0 | p2 tot=218 tst=212 cul=26 of 1046 drawables\n"
H += "        // Occluders are NOT shrunk and the eye-inside guard costs 1-2 objects a frame, so\n"
H += "        // neither of those is the problem. What is: the 27 occluders are 173-triangle\n"
H += "        // simplified PROXIES of rooms built at meshRes 7-24. A proxy that coarse does not\n"
H += "        // cover a Morrowind wall, so the depth buffer has holes everywhere and nothing\n"
H += "        // behind a wall is ever fully covered. TestRect only rejects a FULLY covered rect.\n"
H += "        //\n"
H += "        // TSP_INTOCC_FULLOCC=1 replaces the proxy with the object's REAL triangles, taken\n"
H += "        // straight out of its drawables in world space and cached per node. Correct by\n"
H += "        // construction: the depth buffer then matches what is actually drawn, so it can\n"
H += "        // never over-cull, only cost CPU - and the cost is measured and printed as rast_us\n"
H += "        // with a hard per-frame triangle budget, nearest occluders first.\n"
H += "        //\n"
H += "        // It also makes the eye-inside guard unnecessary. That guard exists because a solid\n"
H += "        // box proxy around the room you stand in would occlude the whole screen. Real\n"
H += "        // geometry does not: the near walls clip away behind the camera and the FAR wall of\n"
H += "        // your own room - the single most valuable occluder in an interior - goes into the\n"
H += "        // buffer where it belongs. So EYEIN defaults ON whenever FULLOCC is on.\n"
H += "        //\n"
H += "        // Env, all read once, no rebuild needed to sweep any of them:\n"
H += "        //   TSP_INTOCC        0 upstream | 1 Pass 2 tests the real world AABB | 2 also test\n"
H += "        //                     Pass 1 large objects against the complete buffer\n"
H += "        //   TSP_INTOCC_FULLOCC=1   real-geometry occluders, nearest first (the fix)\n"
H += "        //   TSP_INTOCC_RASTBUDGET  triangles rasterised per frame (default 12000)\n"
H += "        //   TSP_INTOCC_NODETRI     triangle cap for any single occluder (default 4000)\n"
H += "        //   TSP_INTOCC_TRIBUILD    nodes whose triangle soup is extracted per frame (6)\n"
H += "        //   TSP_INTOCC_EYEIN       -1 auto (=FULLOCC) | 0 keep upstream guard | 1 ignore it\n"
H += "        //   TSP_INTOCC_MESHRES / _MAXMESHRES / _MAXTRIANGLES / _SHRINK / _INSIDE / _MINR\n"
H += "        //                     override the corresponding occlusion setting at cell load\n"
H += "        //   TSP_INTOCC_BOXBUDGET   ComputeBoundsVisitor builds per frame (64)\n"
H += "        //   TSP_INTOCC_REPORT      report every N gameplay frames, NOT the first N (120)\n"
H += "        struct TspIntOccCfg\n"
H += "        {\n"
H += "            int mMode;\n"
H += "            int mFullOcc;\n"
H += "            int mEyeIn;\n"
H += "            int mMaxOcc;\n"
H += "            int mMaxTri;\n"
H += "            int mBudget;\n"
H += "            int mRastBudget;\n"
H += "            int mNodeTri;\n"
H += "            int mTriBuild;\n"
H += "            int mReportEvery;\n"
H += "            int mBoxBudget;\n"
H += "            int mMeshRes;\n"
H += "            int mMaxMeshRes;\n"
H += "            int mMaxTriangles;\n"
H += "            float mShrink;\n"
H += "            float mInside;\n"
H += "            float mMinR;\n"
H += "        };\n"
H += "        int tspEnvInt(const char* name, int def)\n"
H += "        {\n"
H += "            const char* e = std::getenv(name);\n"
H += "            if (e == nullptr || e[0] == 0)\n"
H += "                return def;\n"
H += "            return std::atoi(e);\n"
H += "        }\n"
H += "        float tspEnvFloat(const char* name, float def)\n"
H += "        {\n"
H += "            const char* e = std::getenv(name);\n"
H += "            if (e == nullptr || e[0] == 0)\n"
H += "                return def;\n"
H += "            return static_cast<float>(std::atof(e));\n"
H += "        }\n"
H += "        const TspIntOccCfg& tspIntOccCfg()\n"
H += "        {\n"
H += "            static TspIntOccCfg sCfg;\n"
H += "            static bool sInit = false;\n"
H += "            if (!sInit)\n"
H += "            {\n"
H += "                sInit = true;\n"
H += "                sCfg.mMode = tspEnvInt(\"TSP_INTOCC\", 0);\n"
H += "                if (sCfg.mMode < 0)\n"
H += "                    sCfg.mMode = 0;\n"
H += "                sCfg.mFullOcc = tspEnvInt(\"TSP_INTOCC_FULLOCC\", 0);\n"
H += "                sCfg.mEyeIn = tspEnvInt(\"TSP_INTOCC_EYEIN\", -1);\n"
H += "                if (sCfg.mEyeIn < 0)\n"
H += "                    sCfg.mEyeIn = sCfg.mFullOcc ? 1 : 0;\n"
H += "                sCfg.mMaxOcc = tspEnvInt(\"TSP_INTOCC_MAXOCC\", 12);\n"
H += "                sCfg.mMaxTri = tspEnvInt(\"TSP_INTOCC_MAXTRI\", 512);\n"
H += "                sCfg.mBudget = tspEnvInt(\"TSP_INTOCC_BUDGET\", 8000);\n"
H += "                sCfg.mRastBudget = tspEnvInt(\"TSP_INTOCC_RASTBUDGET\", 12000);\n"
H += "                sCfg.mNodeTri = tspEnvInt(\"TSP_INTOCC_NODETRI\", 4000);\n"
H += "                sCfg.mTriBuild = tspEnvInt(\"TSP_INTOCC_TRIBUILD\", 6);\n"
H += "                sCfg.mReportEvery = tspEnvInt(\"TSP_INTOCC_REPORT\", 120);\n"
H += "                sCfg.mBoxBudget = tspEnvInt(\"TSP_INTOCC_BOXBUDGET\", 64);\n"
H += "                sCfg.mMeshRes = tspEnvInt(\"TSP_INTOCC_MESHRES\", -1);\n"
H += "                sCfg.mMaxMeshRes = tspEnvInt(\"TSP_INTOCC_MAXMESHRES\", -1);\n"
H += "                sCfg.mMaxTriangles = tspEnvInt(\"TSP_INTOCC_MAXTRIANGLES\", -1);\n"
H += "                sCfg.mShrink = tspEnvFloat(\"TSP_INTOCC_SHRINK\", -1.0f);\n"
H += "                sCfg.mInside = tspEnvFloat(\"TSP_INTOCC_INSIDE\", -1.0f);\n"
H += "                sCfg.mMinR = tspEnvFloat(\"TSP_INTOCC_MINR\", -1.0f);\n"
H += "                Log(Debug::Warning) << \"TSP_INTOCC_V5 cfg mode=\" << sCfg.mMode\n"
H += "                                    << \" fullocc=\" << sCfg.mFullOcc << \" eyein=\" << sCfg.mEyeIn\n"
H += "                                    << \" rastbudget=\" << sCfg.mRastBudget << \" nodetri=\" << sCfg.mNodeTri\n"
H += "                                    << \" tribuild=\" << sCfg.mTriBuild << \" boxbudget=\" << sCfg.mBoxBudget\n"
H += "                                    << \" report=\" << sCfg.mReportEvery\n"
H += "                                    << \" ovr meshres=\" << sCfg.mMeshRes << \" maxmeshres=\" << sCfg.mMaxMeshRes\n"
H += "                                    << \" maxtriangles=\" << sCfg.mMaxTriangles << \" shrink=\" << sCfg.mShrink\n"
H += "                                    << \" inside=\" << sCfg.mInside << \" minr=\" << sCfg.mMinR;\n"
H += "            }\n"
H += "            return sCfg;\n"
H += "        }\n"
H += "        double tspNowUs()\n"
H += "        {\n"
H += "            const std::chrono::steady_clock::time_point t = std::chrono::steady_clock::now();\n"
H += "            return static_cast<double>(\n"
H += "                       std::chrono::duration_cast<std::chrono::nanoseconds>(t.time_since_epoch()).count())\n"
H += "                / 1000.0;\n"
H += "        }\n"
H += "        unsigned int sTspFrame = 0xffffffffu;\n"
H += "        long sTspFrames = 0;\n"
H += "        long sTspBoxBuilt = 0;\n"
H += "        long sTspBoxDyn = 0;\n"
H += "        long sTriBuilt = 0;\n"
H += "        long sTriTris = 0;\n"
H += "        int sBoxThisFrame = 0;\n"
H += "        int sBoxDeferred = 0;\n"
H += "        int sTriThisFrame = 0;\n"
H += "        int sTriDeferred = 0;\n"
H += "        int sRastOcc = 0;\n"
H += "        int sRastTris = 0;\n"
H += "        double sRastUs = 0.0;\n"
H += "        int sP1Total = 0;\n"
H += "        int sP1Tested = 0;\n"
H += "        int sP1Culled = 0;\n"
H += "        int sP1TotDw = 0;\n"
H += "        int sP1CulDw = 0;\n"
H += "        int sP2Total = 0;\n"
H += "        int sP2Tested = 0;\n"
H += "        int sP2Culled = 0;\n"
H += "        int sP2Skip = 0;\n"
H += "        int sP2TotDw = 0;\n"
H += "        int sP2CulDw = 0;\n"
H += "        int sEyeSeen = 0;\n"
H += "        int sEyeRast = 0;\n"
H += "        int sEyeTris = 0;\n"
H += "        struct TspBoxEntry\n"
H += "        {\n"
H += "            osg::BoundingSphere::vec_type mCentre;\n"
H += "            osg::BoundingSphere::value_type mRadius = 0;\n"
H += "            osg::BoundingBox mBox;\n"
H += "            int mDrawables = 1;\n"
H += "            bool mDynamic = false;\n"
H += "        };\n"
H += "        struct TspCountVisitor : public osg::NodeVisitor\n"
H += "        {\n"
H += "            TspCountVisitor()\n"
H += "                : osg::NodeVisitor(osg::NodeVisitor::TRAVERSE_ALL_CHILDREN)\n"
H += "            {\n"
H += "            }\n"
H += "            void apply(osg::Drawable& drawable) override\n"
H += "            {\n"
H += "                (void)drawable;\n"
H += "                ++mCount;\n"
H += "            }\n"
H += "            int mCount = 0;\n"
H += "        };\n"
H += "        // World-space box plus subtree drawable count, cached and validated against the\n"
H += "        // node's bounding sphere. Any node whose sphere ever changes is marked dynamic and\n"
H += "        // permanently falls back to the cheap sphere box, so actors never pay for a\n"
H += "        // per-frame subtree traversal.\n"
H += "        const TspBoxEntry& tspEntry(osg::Node* child, const osg::BoundingSphere& bs)\n"
H += "        {\n"
H += "            static std::map<osg::Node*, TspBoxEntry> sCache;\n"
H += "            static TspBoxEntry sFallback;\n"
H += "            if (sCache.size() > 32768)\n"
H += "                sCache.clear();\n"
H += "            std::map<osg::Node*, TspBoxEntry>::iterator it = sCache.find(child);\n"
H += "            if (it != sCache.end())\n"
H += "            {\n"
H += "                if (!it->second.mDynamic && it->second.mRadius == bs.radius()\n"
H += "                    && it->second.mCentre == bs.center())\n"
H += "                    return it->second;\n"
H += "                if (!it->second.mDynamic)\n"
H += "                {\n"
H += "                    it->second.mDynamic = true;\n"
H += "                    ++sTspBoxDyn;\n"
H += "                }\n"
H += "                sFallback = it->second;\n"
H += "                sFallback.mBox = osg::BoundingBox();\n"
H += "                sFallback.mBox.expandBy(bs);\n"
H += "                return sFallback;\n"
H += "            }\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (c.mBoxBudget > 0 && sBoxThisFrame >= c.mBoxBudget)\n"
H += "            {\n"
H += "                ++sBoxDeferred;\n"
H += "                sFallback = TspBoxEntry();\n"
H += "                sFallback.mDynamic = true;\n"
H += "                sFallback.mBox.expandBy(bs);\n"
H += "                return sFallback;\n"
H += "            }\n"
H += "            ++sBoxThisFrame;\n"
H += "            osg::ComputeBoundsVisitor cbv;\n"
H += "            child->accept(cbv);\n"
H += "            TspCountVisitor cnt;\n"
H += "            child->accept(cnt);\n"
H += "            TspBoxEntry e;\n"
H += "            e.mCentre = bs.center();\n"
H += "            e.mRadius = bs.radius();\n"
H += "            e.mBox = cbv.getBoundingBox();\n"
H += "            e.mDrawables = cnt.mCount > 0 ? cnt.mCount : 1;\n"
H += "            e.mDynamic = false;\n"
H += "            if (!e.mBox.valid())\n"
H += "                e.mBox.expandBy(bs);\n"
H += "            ++sTspBoxBuilt;\n"
H += "            sCache[child] = e;\n"
H += "            return sCache[child];\n"
H += "        }\n"
H += "        struct TspTriCollector\n"
H += "        {\n"
H += "            std::vector<unsigned int>* mIdx = nullptr;\n"
H += "            unsigned int mBase = 0;\n"
H += "            unsigned int mLimit = 0;\n"
H += "            void operator()(unsigned int a, unsigned int b, unsigned int c)\n"
H += "            {\n"
H += "                if (mIdx == nullptr || a == b || b == c || a == c)\n"
H += "                    return;\n"
H += "                if (mLimit > 0 && mIdx->size() >= static_cast<std::size_t>(mLimit) * 3)\n"
H += "                    return;\n"
H += "                mIdx->push_back(mBase + a);\n"
H += "                mIdx->push_back(mBase + b);\n"
H += "                mIdx->push_back(mBase + c);\n"
H += "            }\n"
H += "        };\n"
H += "        // Pulls an object's real triangles into world space. Alpha-blended and explicitly\n"
H += "        // transparent geometry is skipped - a curtain or a window pane must not occlude.\n"
H += "        struct TspTriVisitor : public osg::NodeVisitor\n"
H += "        {\n"
H += "            TspTriVisitor()\n"
H += "                : osg::NodeVisitor(osg::NodeVisitor::TRAVERSE_ALL_CHILDREN)\n"
H += "            {\n"
H += "            }\n"
H += "            void apply(osg::Transform& transform) override\n"
H += "            {\n"
H += "                osg::Matrix m;\n"
H += "                if (!mStack.empty())\n"
H += "                    m = mStack.back();\n"
H += "                transform.computeLocalToWorldMatrix(m, this);\n"
H += "                mStack.push_back(m);\n"
H += "                traverse(transform);\n"
H += "                mStack.pop_back();\n"
H += "            }\n"
H += "            void apply(osg::Geometry& geom) override\n"
H += "            {\n"
H += "                if (mMesh == nullptr)\n"
H += "                    return;\n"
H += "                const osg::StateSet* ss = geom.getStateSet();\n"
H += "                if (ss != nullptr)\n"
H += "                {\n"
H += "                    if (ss->getRenderingHint() == osg::StateSet::TRANSPARENT_BIN)\n"
H += "                        return;\n"
H += "                    if ((ss->getMode(GL_BLEND) & osg::StateAttribute::ON) != 0)\n"
H += "                        return;\n"
H += "                }\n"
H += "                const osg::Vec3Array* va = dynamic_cast<const osg::Vec3Array*>(geom.getVertexArray());\n"
H += "                if (va == nullptr || va->empty())\n"
H += "                    return;\n"
H += "                osg::Matrixf mf;\n"
H += "                if (!mStack.empty())\n"
H += "                    mf = osg::Matrixf(mStack.back());\n"
H += "                const unsigned int base = static_cast<unsigned int>(mMesh->vertices.size());\n"
H += "                const std::size_t idxBefore = mMesh->indices.size();\n"
H += "                mMesh->vertices.reserve(mMesh->vertices.size() + va->size());\n"
H += "                for (unsigned int i = 0; i < va->size(); ++i)\n"
H += "                    mMesh->vertices.push_back((*va)[i] * mf);\n"
H += "                osg::TriangleIndexFunctor<TspTriCollector> tif;\n"
H += "                tif.mIdx = &mMesh->indices;\n"
H += "                tif.mBase = base;\n"
H += "                tif.mLimit = mLimit;\n"
H += "                geom.accept(tif);\n"
H += "                if (mMesh->indices.size() == idxBefore)\n"
H += "                    mMesh->vertices.resize(base);\n"
H += "            }\n"
H += "            std::vector<osg::Matrix> mStack;\n"
H += "            OccluderMesh* mMesh = nullptr;\n"
H += "            unsigned int mLimit = 4000;\n"
H += "        };\n"
H += "        struct TspRealEntry\n"
H += "        {\n"
H += "            OccluderMesh mMesh;\n"
H += "            osg::BoundingSphere::vec_type mCentre;\n"
H += "            osg::BoundingSphere::value_type mRadius = 0;\n"
H += "            bool mDynamic = false;\n"
H += "        };\n"
H += "        const OccluderMesh& tspRealMesh(osg::Node* child, const osg::BoundingSphere& bs)\n"
H += "        {\n"
H += "            static std::map<osg::Node*, TspRealEntry> sCache;\n"
H += "            static OccluderMesh sEmpty;\n"
H += "            std::map<osg::Node*, TspRealEntry>::iterator it = sCache.find(child);\n"
H += "            if (it != sCache.end())\n"
H += "            {\n"
H += "                if (it->second.mDynamic)\n"
H += "                    return sEmpty;\n"
H += "                if (it->second.mRadius == bs.radius() && it->second.mCentre == bs.center())\n"
H += "                    return it->second.mMesh;\n"
H += "                it->second.mDynamic = true;\n"
H += "                it->second.mMesh = OccluderMesh();\n"
H += "                return sEmpty;\n"
H += "            }\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (c.mTriBuild > 0 && sTriThisFrame >= c.mTriBuild)\n"
H += "            {\n"
H += "                ++sTriDeferred;\n"
H += "                return sEmpty;\n"
H += "            }\n"
H += "            if (sCache.size() > 512)\n"
H += "                sCache.clear();\n"
H += "            ++sTriThisFrame;\n"
H += "            TspRealEntry e;\n"
H += "            e.mCentre = bs.center();\n"
H += "            e.mRadius = bs.radius();\n"
H += "            TspTriVisitor v;\n"
H += "            v.mMesh = &e.mMesh;\n"
H += "            v.mLimit = static_cast<unsigned int>(c.mNodeTri > 0 ? c.mNodeTri : 4000);\n"
H += "            child->accept(v);\n"
H += "            for (std::size_t i = 0; i < e.mMesh.vertices.size(); ++i)\n"
H += "                e.mMesh.aabb.expandBy(e.mMesh.vertices[i]);\n"
H += "            ++sTriBuilt;\n"
H += "            sTriTris += static_cast<long>(e.mMesh.indices.size() / 3);\n"
H += "            sCache[child] = e;\n"
H += "            return sCache[child].mMesh;\n"
H += "        }\n"
H += "        struct TspCand\n"
H += "        {\n"
H += "            osg::Node* mNode = nullptr;\n"
H += "            float mDistSq = 0.0f;\n"
H += "        };\n"
H += "        bool tspCandLess(const TspCand& a, const TspCand& b)\n"
H += "        {\n"
H += "            return a.mDistSq < b.mDistSq;\n"
H += "        }\n"
H += "        void tspIntOccBeginFrame(unsigned int frame)\n"
H += "        {\n"
H += "            if (frame == sTspFrame)\n"
H += "                return;\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            if (sTspFrame != 0xffffffffu && (c.mMode >= 1 || c.mFullOcc))\n"
H += "            {\n"
H += "                ++sTspFrames;\n"
H += "                if (c.mReportEvery > 0 && (sTspFrames % c.mReportEvery) == 0)\n"
H += "                    Log(Debug::Warning) << \"TSP_INTOCC_V5 f=\" << sTspFrame\n"
H += "                                        << \" p1 tot=\" << sP1Total << \" tst=\" << sP1Tested\n"
H += "                                        << \" cul=\" << sP1Culled\n"
H += "                                        << \" | p2 tot=\" << sP2Total << \" tst=\" << sP2Tested\n"
H += "                                        << \" cul=\" << sP2Culled << \" skip=\" << sP2Skip\n"
H += "                                        << \" | DRAWABLES p1 tot=\" << sP1TotDw << \" cul=\" << sP1CulDw\n"
H += "                                        << \" p2 tot=\" << sP2TotDw << \" cul=\" << sP2CulDw\n"
H += "                                        << \" submitted=\" << (sP1TotDw + sP2TotDw - sP1CulDw - sP2CulDw)\n"
H += "                                        << \" | RAST occ=\" << sRastOcc << \" tris=\" << sRastTris\n"
H += "                                        << \" us=\" << static_cast<long>(sRastUs)\n"
H += "                                        << \" | eyein seen=\" << sEyeSeen << \" rast=\" << sEyeRast\n"
H += "                                        << \" | box built=\" << sTspBoxBuilt << \" dyn=\" << sTspBoxDyn\n"
H += "                                        << \" def=\" << sBoxDeferred\n"
H += "                                        << \" | tri built=\" << sTriBuilt\n"
H += "                                        << \" tris=\" << sTriTris << \" def=\" << sTriDeferred;\n"
H += "            }\n"
H += "            sTspFrame = frame;\n"
H += "            sBoxThisFrame = 0;\n"
H += "            sBoxDeferred = 0;\n"
H += "            sTriThisFrame = 0;\n"
H += "            sTriDeferred = 0;\n"
H += "            sRastOcc = 0;\n"
H += "            sRastTris = 0;\n"
H += "            sRastUs = 0.0;\n"
H += "            sP1Total = 0;\n"
H += "            sP1Tested = 0;\n"
H += "            sP1Culled = 0;\n"
H += "            sP1TotDw = 0;\n"
H += "            sP1CulDw = 0;\n"
H += "            sP2Total = 0;\n"
H += "            sP2Tested = 0;\n"
H += "            sP2Culled = 0;\n"
H += "            sP2Skip = 0;\n"
H += "            sP2TotDw = 0;\n"
H += "            sP2CulDw = 0;\n"
H += "            sEyeSeen = 0;\n"
H += "            sEyeRast = 0;\n"
H += "            sEyeTris = 0;\n"
H += "        }\n"
H += "        bool tspIntOccAllowInside(int tris)\n"
H += "        {\n"
H += "            const TspIntOccCfg& c = tspIntOccCfg();\n"
H += "            ++sEyeSeen;\n"
H += "            if (c.mEyeIn == 0)\n"
H += "                return false;\n"
H += "            if (c.mMaxTri > 0 && tris > c.mMaxTri)\n"
H += "                return false;\n"
H += "            if (c.mMaxOcc > 0 && sEyeRast >= c.mMaxOcc)\n"
H += "                return false;\n"
H += "            if (c.mBudget > 0 && sEyeTris + tris > c.mBudget)\n"
H += "                return false;\n"
H += "            ++sEyeRast;\n"
H += "            sEyeTris += tris;\n"
H += "            return true;\n"
H += "        }\n"
N1 = A1 + "\n#include <chrono>\n#include <cstdlib>\n#include <map>\n#include <vector>\n#include <osg/ComputeBoundsVisitor>\n#include <osg/NodeVisitor>\n#include <osg/TriangleIndexFunctor>"
N2 = H + A2
N3 = "        tspIntOccBeginFrame(cv->getTraversalNumber());\n"
N3 += "        std::vector<TspCand> tspP1;\n"
N3 += A3
N4 = "            ++sP1Total;\n"
N4 += "            if (tspIntOccCfg().mMode >= 1 || tspIntOccCfg().mFullOcc)\n"
N4 += "                sP1TotDw += tspEntry(child, bs).mDrawables;\n"
N4 += "            if (tspIntOccCfg().mFullOcc)\n"
N4 += "            {\n"
N4 += "                TspCand tspCnd;\n"
N4 += "                tspCnd.mNode = child;\n"
N4 += "                tspCnd.mDistSq = static_cast<float>((bs.center() - cv->getEyePoint()).length2());\n"
N4 += "                tspP1.push_back(tspCnd);\n"
N4 += "                continue;\n"
N4 += "            }\n"
N4 += A4
N5 = "                    const bool tspEyeInside = scaledBB.contains(cv->getEyePoint());\n"
N5 += "                    if (!tspEyeInside\n"
N5 += "                        || tspIntOccAllowInside(static_cast<int>(mesh.indices.size() / 3)))"
N6 = A6 + "\n"
N6 += "            // TSP_INTOCC_V5: in mode 2 the traversal is deferred until every occluder in\n"
N6 += "            // this cell has been rasterised, so child order cannot decide what occludes what.\n"
N6 += "            if (tspIntOccCfg().mMode >= 2)\n"
N6 += "            {\n"
N6 += "                TspCand tspCnd2;\n"
N6 += "                tspCnd2.mNode = child;\n"
N6 += "                tspCnd2.mDistSq = static_cast<float>((bs.center() - cv->getEyePoint()).length2());\n"
N6 += "                tspP1.push_back(tspCnd2);\n"
N6 += "                continue;\n"
N6 += "            }"
N7 = "        // TSP_INTOCC_V5: rasterise real-geometry occluders nearest-first inside a hard\n"
N7 += "        // triangle budget, then test every large object against the COMPLETE buffer.\n"
N7 += "        if (tspIntOccCfg().mFullOcc && !tspP1.empty())\n"
N7 += "        {\n"
N7 += "            std::sort(tspP1.begin(), tspP1.end(), tspCandLess);\n"
N7 += "            const TspIntOccCfg& tspC = tspIntOccCfg();\n"
N7 += "            for (std::size_t tspI = 0; tspI < tspP1.size(); ++tspI)\n"
N7 += "            {\n"
N7 += "                if (!mEnableStaticOccluders)\n"
N7 += "                    break;\n"
N7 += "                if (tspP1[tspI].mDistSq >= mOccluderMaxDistanceSq)\n"
N7 += "                    continue;\n"
N7 += "                osg::Node* tspN = tspP1[tspI].mNode;\n"
N7 += "                const OccluderMesh& tspM = tspRealMesh(tspN, tspN->getBound());\n"
N7 += "                if (tspM.indices.empty() || !tspM.aabb.valid())\n"
N7 += "                    continue;\n"
N7 += "                const int tspTris = static_cast<int>(tspM.indices.size() / 3);\n"
N7 += "                if (tspC.mRastBudget > 0 && sRastTris + tspTris > tspC.mRastBudget)\n"
N7 += "                    continue;\n"
N7 += "                if (mMaxTriangles > 0\n"
N7 += "                    && mCuller->getNumBuildingTris() + static_cast<unsigned int>(tspTris) > mMaxTriangles)\n"
N7 += "                    continue;\n"
N7 += "                if (tspC.mEyeIn == 0)\n"
N7 += "                {\n"
N7 += "                    const osg::Vec3f tspCentre = tspM.aabb.center();\n"
N7 += "                    const osg::Vec3f tspHalf\n"
N7 += "                        = (osg::Vec3f(tspM.aabb.xMax(), tspM.aabb.yMax(), tspM.aabb.zMax()) - tspCentre)\n"
N7 += "                        * mOccluderInsideThreshold;\n"
N7 += "                    osg::BoundingBox tspSB;\n"
N7 += "                    tspSB.expandBy(tspCentre - tspHalf);\n"
N7 += "                    tspSB.expandBy(tspCentre + tspHalf);\n"
N7 += "                    if (tspSB.contains(cv->getEyePoint()))\n"
N7 += "                    {\n"
N7 += "                        ++sEyeSeen;\n"
N7 += "                        continue;\n"
N7 += "                    }\n"
N7 += "                }\n"
N7 += "                const double tspT0 = tspNowUs();\n"
N7 += "                mCuller->rasterizeOccluder(tspM.vertices, tspM.indices);\n"
N7 += "                sRastUs += tspNowUs() - tspT0;\n"
N7 += "                mCuller->incrementBuildingOccluders(\n"
N7 += "                    static_cast<unsigned int>(tspTris), static_cast<unsigned int>(tspM.vertices.size()));\n"
N7 += "                sRastTris += tspTris;\n"
N7 += "                ++sRastOcc;\n"
N7 += "            }\n"
N7 += "        }\n"
N7 += "        for (std::size_t tspJ = 0; tspJ < tspP1.size(); ++tspJ)\n"
N7 += "        {\n"
N7 += "            osg::Node* tspChild = tspP1[tspJ].mNode;\n"
N7 += "            const osg::BoundingSphere& tspBS = tspChild->getBound();\n"
N7 += "            if (tspIntOccCfg().mMode >= 2)\n"
N7 += "            {\n"
N7 += "                const TspBoxEntry& tspE = tspEntry(tspChild, tspBS);\n"
N7 += "                ++sP1Tested;\n"
N7 += "                if (!mCuller->testVisibleAABB(tspE.mBox))\n"
N7 += "                {\n"
N7 += "                    ++sP1Culled;\n"
N7 += "                    sP1CulDw += tspE.mDrawables;\n"
N7 += "                    continue;\n"
N7 += "                }\n"
N7 += "            }\n"
N7 += "            tspChild->accept(*cv);\n"
N7 += "        }\n"
N7 += A7
N8 = "            ++sP2Total;\n"
N8 += "            bool tspVisible = true;\n"
N8 += "            if (skipOcclusion)\n"
N8 += "                ++sP2Skip;\n"
N8 += "            else\n"
N8 += "            {\n"
N8 += "                ++sP2Tested;\n"
N8 += "                int tspDw = 1;\n"
N8 += "                if (tspIntOccCfg().mMode >= 1 || tspIntOccCfg().mFullOcc)\n"
N8 += "                {\n"
N8 += "                    const TspBoxEntry& tspE2 = tspEntry(child, bs);\n"
N8 += "                    if (tspIntOccCfg().mMode >= 1)\n"
N8 += "                        childBB = tspE2.mBox;\n"
N8 += "                    tspDw = tspE2.mDrawables;\n"
N8 += "                }\n"
N8 += "                sP2TotDw += tspDw;\n"
N8 += "                tspVisible = mCuller->testVisibleAABB(childBB);\n"
N8 += "                if (!tspVisible)\n"
N8 += "                {\n"
N8 += "                    ++sP2Culled;\n"
N8 += "                    sP2CulDw += tspDw;\n"
N8 += "                }\n"
N8 += "            }\n"
N8 += "            if (tspVisible)"
CTORNEW = "        , mStorage(storage)\n    {\n"
CTORNEW += "        const TspIntOccCfg& tspCfg = tspIntOccCfg();\n"
CTORNEW += "        if (tspCfg.mShrink >= 0.0f)\n"
CTORNEW += "            mOccluderShrinkFactor = tspCfg.mShrink;\n"
CTORNEW += "        if (tspCfg.mInside >= 0.0f)\n"
CTORNEW += "            mOccluderInsideThreshold = tspCfg.mInside;\n"
CTORNEW += "        if (tspCfg.mMinR >= 0.0f)\n"
CTORNEW += "            mOccluderMinRadius = tspCfg.mMinR;\n"
CTORNEW += "        if (tspCfg.mMeshRes > 0)\n"
CTORNEW += "            mOccluderMeshResolution = tspCfg.mMeshRes;\n"
CTORNEW += "        if (tspCfg.mMaxMeshRes > 0)\n"
CTORNEW += "            mOccluderMaxMeshResolution = tspCfg.mMaxMeshRes;\n"
CTORNEW += "        if (tspCfg.mMaxTriangles >= 0)\n"
CTORNEW += "            mMaxTriangles = static_cast<unsigned int>(tspCfg.mMaxTriangles);\n"
CTORNEW += "        static bool sTspParamsLogged = false;\n"
CTORNEW += "        if (!sTspParamsLogged)\n"
CTORNEW += "        {\n"
CTORNEW += "            sTspParamsLogged = true;\n"
CTORNEW += "            unsigned int tspBW = 0;\n"
CTORNEW += "            unsigned int tspBH = 0;\n"
CTORNEW += "            if (mCuller)\n"
CTORNEW += "                mCuller->getResolution(tspBW, tspBH);\n"
CTORNEW += "            Log(Debug::Warning) << \"TSP_INTOCC_V5 params minRadius=\" << mOccluderMinRadius\n"
CTORNEW += "                                << \" maxRadius=\" << mOccluderMaxRadius\n"
CTORNEW += "                                << \" shrink=\" << mOccluderShrinkFactor\n"
CTORNEW += "                                << \" meshRes=\" << mOccluderMeshResolution\n"
CTORNEW += "                                << \" maxMeshRes=\" << mOccluderMaxMeshResolution\n"
CTORNEW += "                                << \" insideThresh=\" << mOccluderInsideThreshold\n"
CTORNEW += "                                << \" maxDist=\" << std::sqrt(mOccluderMaxDistanceSq)\n"
CTORNEW += "                                << \" staticOcc=\" << (mEnableStaticOccluders ? 1 : 0)\n"
CTORNEW += "                                << \" maxTriangles=\" << mMaxTriangles\n"
CTORNEW += "                                << \" mocBuffer=\" << tspBW << \"x\" << tspBH;\n"
CTORNEW += "        }\n"
CTORNEW += "    }\n\n    const OccluderMesh& CellOcclusionCallback::getOccluderMesh"
out = src
for a, n in ((A1, N1), (A2, N2), (A3, N3), (A4, N4), (A5, N5), (A6, N6), (A7, N7), (A8, N8), (CTOR, CTORNEW)):
    out = out.replace(a, n, 1)
if out.count("{") != out.count("}"):
    print("BRACE IMBALANCE - NOTHING WRITTEN: " + str(out.count("{")) + " vs " + str(out.count("}")))
    sys.exit(1)
if out.count(MARK) < 4:
    print("MARKER CHECK FAILED (" + str(out.count(MARK)) + ") - NOTHING WRITTEN")
    sys.exit(1)
for frag in ("#include <osg/TriangleIndexFunctor>", "tspRealMesh(tspN, tspN->getBound())", "sTspParamsLogged",
             "tspIntOccBeginFrame(cv->getTraversalNumber())", "mOccluderMeshResolution = tspCfg.mMeshRes",
             "sP2CulDw += tspDw", "tspChild->accept(*cv)", "std::sort(tspP1.begin(), tspP1.end(), tspCandLess)",
             "mocBuffer="):
    if frag not in out:
        print("REQUIRED FRAGMENT MISSING (" + frag + ") - NOTHING WRITTEN")
        sys.exit(1)
if out.count("tspP1.push_back") != 2 or out.count("std::vector<TspCand> tspP1;") != 1:
    print("CANDIDATE-LIST WIRING WRONG - NOTHING WRITTEN")
    sys.exit(1)
open(P, "w", encoding="utf-8").write(out)
print("PATCH APPLIED: " + MARK)
print("  bytes   : " + str(len(src)) + " -> " + str(len(out)))
print("  braces  : " + str(out.count("{")) + " balanced")
print("  markers : " + str(out.count(MARK)))
