# TSP_VBO_ORPHAN_V5 patcher for gl4es src/gl/buffers.c (input must be pristine HEAD)
BEGIN { helpers = 0; hook = 0; refused = 0 }
/TSP_VBO_ORPHAN/ { refused = 1; print "TSP_VBO_ORPHAN_V5 PATCH REFUSED: input already carries an orphan marker" > "/dev/stderr"; exit 4 }
/^\/\/#define DEBUG[[:space:]]*$/ && helpers == 0 {
    helpers = 1
    print "#include <stdio.h>"
    print "#include <stdlib.h>"
    print "#include <string.h>"
    print "/* TSP_VBO_ORPHAN_V5 - a fresh GLES buffer name for every write into a DYNAMIC/STREAM array VBO."
    print " * The full gl4es shadow is uploaded into the new name with glBufferData, the old name is deleted"
    print " * (the driver keeps its storage alive for any draw already queued on it), every attrib that"
    print " * referenced the old name is repointed, and the gles-side attrib cache is invalidated so"
    print " * realize_glenv re-issues glVertexAttribPointer before the next draw. Nothing here relies on"
    print " * the driver honouring a respec of a bound buffer (which is what V2/V3/V4 all assumed)."
    print " * STATIC_DRAW buffers keep the stock glBufferSubData path. Gate: LIBGL_TSP_ORPHAN exactly \"1\". */"
    print "void rebind_real_buff_arrays(int old_buffer, int new_buffer);   /* defined further down in this file */"
    print "static int tsp_orphan_on(void) {"
    print "    static int v = -1;"
    print "    if (v < 0) { const char* e = getenv(\"LIBGL_TSP_ORPHAN\"); v = (e && e[0] == '1' && e[1] == 0) ? 1 : 0; }"
    print "    return v;"
    print "}"
    print "static void tsp_orphan_report(long sz, int fallback) {"
    print "    static unsigned long n = 0, kb = 0, fb = 0;"
    print "    kb += (unsigned long)(sz >> 10);"
    print "    if (fallback) ++fb;"
    print "    if ((++n & 0xffff) == 1) {   /* first rotation, then every 65536 */"
    print "        printf(\"TSP_VBO_ORPHAN_V5 on=1 (fresh buffer name per dynamic write; supersedes V1-V4) rotate=%lu kb=%lu fallback=%lu\\n\", n, kb, fb);"
    print "        fflush(stdout);"
    print "    }"
    print "}"
    print "/* returns 1 when the buffer was rotated onto a fresh name, 0 when the caller must take the stock path */"
    print "static int tsp_orphan_rotate(glbuffer_t* buff, GLenum target) {"
    print "    LOAD_GLES(glGenBuffers);"
    print "    LOAD_GLES(glBufferData);"
    print "    GLuint old = buff->real_buffer, fresh = 0;"
    print "    if (!buff->data || buff->size <= 0) return 0;"
    print "    gles_glGenBuffers(1, &fresh);"
    print "    if (!fresh) return 0;"
    print "    bindBuffer(target, fresh);"
    print "    gles_glBufferData(target, buff->size, buff->data, buff->usage);"
    print "    buff->real_buffer = fresh;"
    print "    rebind_real_buff_arrays(old, fresh);   /* glstate->vao attribs that named the old buffer */"
    print "    if (glstate->gleshard) {              /* gles-side cache: force a fresh glVertexAttribPointer */"
    print "        for (int i = 0; i < hardext.maxvattrib; ++i)"
    print "            if (glstate->gleshard->vertexattrib[i].real_buffer == old)"
    print "                glstate->gleshard->vertexattrib[i].real_buffer = 0;"
    print "    }"
    print "    deleteSingleBuffer(old);"
    print "    return 1;"
    print "}"
    print ""
}
{ print }
/^    if\(\(target==GL_ARRAY_BUFFER \|\| target==GL_ELEMENT_ARRAY_BUFFER\) && buff->real_buffer\) \{$/ && hook == 0 {
    hook = 1
    print "        if(target==GL_ARRAY_BUFFER && (buff->usage==GL_DYNAMIC_DRAW || buff->usage==GL_STREAM_DRAW) && tsp_orphan_on()) {   /* TSP_VBO_ORPHAN_V5 */"
    print "            memcpy((char*)buff->data + offset, data, size);   /* shadow first: the fresh name is filled from it */"
    print "            if(tsp_orphan_rotate(buff, target)) {"
    print "                tsp_orphan_report(size, 0);"
    print "                noerrorShim();"
    print "                return;"
    print "            }"
    print "            tsp_orphan_report(size, 1);   /* could not rotate: fall through to the stock SubData below */"
    print "        }"
}
END { if (refused) exit 4; if (helpers != 1 || hook != 1) { print "TSP_VBO_ORPHAN_V5 PATCH FAILED helpers=" helpers " hook=" hook > "/dev/stderr"; exit 3 } }
